### ISSUE TITLE
Precaching: Prematurely bails out if one-of-N resources don't fetch successfully

### ISSUE THREAD

**Issue by boerwastaken** [catalpainternational/canoe#102]
What I see:

1. In the opportunistic precaching phase (called *runtime cache* in #98) of Asteroid, I repeatedly see 404s for a particular media resource, and no fetches for any other media resources 
2. Thinking there's probably more resources than just that one, and curious about why I don't see them getting fetched, I put something at the referenced location so that it may be fetched
3. It gets fetched successfully. However, the successful fetch gets followed up with a fetch for a resource that wasn't fetched before, which 404s just like the one in step \#1 (as expected, I don't have all the referents on my dev server)
4. That fetch is retried every 5 minutes ad infinitum

What I would expect to see instead:
1. A bunch of 404s for all referents that do not exist and have not been cached yet.

So what happens is that for priming the runtime cache, the fate of any resource is tied up with all resources before it (in manifest order?). Corollary: if the first (for some arbitrary definition of "first") resource fetch fails permanently, **NONE** of the ones referenced after it (in some manifest?) will be preloaded into the runtime cache.

From a resilience/robustness perspective, especially under adverse network conditions, this is very ineffective. The next resource should be tried, because:

1.  while there may be a (semi)permanent failure, such as a referential integrity calamity, leading to a 404 for one particular resource, such a calamity does not necessarily have bearing on the availability of any other resource
2.  while there may be a temporary failure (such as network), but there's no reason to break off the fetching to retry only 5 minutes later. It would make sense, however, to use some backoff mechanism *during* a fetch run. Here's an one from the Gather serviceworker that errors after a certain number of attempts or succeeds if a certain predicate asserts true: https://github.com/catalpainternational/gather/blob/85650f8/gather/surveydata/templates/sw.js#L81:L97, copy/paste responsibly ;-)

What probably helps and confuses at the same time is the fallback to network. So *as long as there is network connectivity at the exact moment the course slide is rendered*, a requested resource (such as an image) will still load and get cached at the time it is needed. Which may have made this problem go unnoticed in dev, possibly at the cost of user confusion ("I had good network for 20 minutes before going offline, and now I can't see the images, didn't they write in the brochure that this thing was supposed to precache during the good times of networkness?").

**Comment by PeteCoward** [comment]
agreed, we should catch network failures during the warming of the runtime cache.
