### ISSUE TITLE
Language setting is not persisted

### ISSUE THREAD

**Issue by boerwastaken** [catalpainternational/canoe#103]
Observed behaviour:

1. When I choose a site language, it switches to that language, as it should.

2. When I close the tab, and then navigate to the site (https://asteroid.temp.build) in a new tab, stuff appears in not-my-choice from step 1 and the language choice menu also shows not-my-choice from step 1 selected.

Expected behaviour:

- [ ]  Language choice is persisted

**Comment by PeteCoward** [comment]
This was a stretch goal. Thanks for highlighting though. I too think it's worth prioritising

**Comment by boerwastaken** [comment]
https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-LANGUAGE_COOKIE_NAME

**Comment by katevoss** [comment]
@boerwastaken I don't believe that the Django backend cares what language the frontend is in. I believe that the purpose is for end-users to be able to set their language and for their selection to persist even if they reload or refresh the page. 

@PeteCoward If we use a cookie to set their language preference, would we be required to get the user to agree to cookies? I don't believe that Timor Leste is covered under the GDPR but it might be a good idea regardless.

**Comment by boerwastaken** [comment]
> If we use a cookie to set their language preference, would we be required to get the user to agree to cookies? I don't believe that Timor Leste is covered under the GDPR but it might be a good idea regardless.

As we don't need to let any server know what language the user wants, we don't need to use a cookie, and if we'd use something local-only instead of a cookie (localstorage springs to mind) then we won't need to worry about GDPR at all :innocent: 

Btw so far afaik we haven't worried about GDPR, while at the same time in most projects we're pretty gung ho about flinging Google Analytics spyware at unsuspecting users. Hmmmm :thinking:
