### ISSUE TITLE
Bero: Animation for 'Lesson completed'

### ISSUE THREAD

**Issue by Juliana-t** [catalpainternational/canoe#1030]
### Overview
As part of the development of the visual system and assets for core Bero, we need an animation for the '[Lesson completed' screen](https://projects.invisionapp.com/d/main#/console/20251865/453511208/preview)

### Conditions of satisfaction
- [ ] Create static illustration
- [ ] Apply illustration to the mockup (to confirm if it works well on the UI)
- [ ] Approve static illustration
- [ ] Animate illustration
- [ ] Export static illustration and animation and upload it to the Bero product drive
- [ ] Inform Product lead (Juliana)

### Resources
- [Briefing and creative direction](https://docs.google.com/document/d/1o1RvoAmWyBUoVeiwVZis5A9TSs9bdS2kT7h8EOUEj1o/edit#)
- [Check list Bero visual assets](https://docs.google.com/spreadsheets/d/1qurBq1GE5VbYy1jnH34uXtWwC7R9enhm1T0-_BN_1ZE/edit#gid=1579069067)
- [Screen UI](https://projects.invisionapp.com/d/main#/console/20251865/453511208/preview)

**Comment by Juliana-t** [comment]
Daniel's proposal
![image (17)](https://user-images.githubusercontent.com/52807808/135196549-7e0327af-8e9f-4892-846b-8b7aa6a8c32e.png)
l

**Comment by Juliana-t** [comment]
Feedback and request for reviews:
- one hand only (the one holding the device), remove the other
- tick icon can be bigger 
- simplify background - remove fish elements, use grey circle only (grey circle as you have on the UI mockup you pasted on the spreadsheet

@DanielHeads once you have it, can you please post here the illustration + mockup illustration on the app UI?

**Comment by DanielHeads** [comment]
[Illustration ](https://projects.invisionapp.com/d/main#/console/21667206/459000066/preview)
[Screen Option A](https://projects.invisionapp.com/d/main#/console/21667206/459000067/preview)
[Screen Option B](https://projects.invisionapp.com/d/main#/console/21667206/459000068/preview)

**Comment by Juliana-t** [comment]
I like Option B - not sure how this would work in animation. Do you think this needs an animation or should we keep the animation just for the course completion moment, and leave the lesson completion more subtle - @andrewwapling @davidcatalpa what do you think?

**Comment by andrewwapling** [comment]
Hi @Juliana-t I also prefer the simplicity of Option B. I wonder whether the tick is too bold and whether we could refine this to align more closely with the UI tick, please see reference here: https://invis.io/4R11SX9Z6DAG It probably doesn't need to be an exact replica though a closer representation would be good to help integrate with the UI aesthetic.

In terms of animation I think we could keep it really simply. Perhaps a gently tilt or flick of the wrist and the tick animating would suffice. I think subtle and punchy is key.
