### ISSUE TITLE
Fix: HTML5 animations

### ISSUE THREAD

**Issue by Juliana-t** [catalpainternational/canoe#1031]
We are exploring [Lottiefiles](https://lottiefiles.com/) platform to prepare animations for Bero.
It allows animations to be exported as a json file, also allows to copy a little script. You can use this one as an example ( https://lottiefiles.com/share/ntpb8pjd ) - but note that download / access the code is only possible with a login (free)
We would like to use those animations in:
- app screens (like 'Lesson completed' screen or loading screen - needs an engineer to upload/implement it )
- on content cards, inside a lesson or tips (uploaded through Wagtail - can be done by a content manager
I didn't test the first scenario 
I did test the second, using the HTML5 card type - could upload (no error on Wagtail) but does not display the animation on the UI: https://jid-staging.temp.build/#/site/kumul-helt-skul/learn/course-to-test-html5-animations/test-html5:content:1 and https://jid-staging.temp.build/#/site/kumul-helt-skul/learn/course-to-test-html5-animations/test-html5:content:2

![Screen Shot 2021-09-21 at 5 52 39 PM](https://user-images.githubusercontent.com/52807808/134141736-50c0b1cf-7dbf-47e5-84f2-3f8d3f6f4fde.png)
![Screen Shot 2021-09-21 at 5 52 48 PM](https://user-images.githubusercontent.com/52807808/134141741-c74f37a4-6065-43ab-aadb-f4917c42f7c2.png)
)

### What we want to do
- [ ] Upload the lottiefiles (htlm or json) to a screen of the app and see if it runs (iOS, Android, laptop Chrome/Firefox/Safari/ ...)
- [ ] Explore why both json and html files uploaded through wagtail are breaking (see screenshots above)

**Comment by PeteCoward** [comment]
I'd much rather remove the whole html feature, and implement the lottie files upload to handle this use case.

**Comment by Juliana-t** [comment]
We can't because that would remove the ability to upload the interactive
element/content (and PeP has plans to use it)
otherwise, on KHS we advise against using that content format (for both
technical, pedagogical and accessibility reasons). But we have a program
relying on that feature, so we can remove it (or at least we need to
discuss that in advance with Kara - maybe tomorrow on the sync meeting?)

**Comment by PeteCoward** [comment]
We've never really "implemented" it we just did a few experiments. We don't test it (no content), which is why it may have broken since.

**Comment by Juliana-t** [comment]
Can we test it now with this example? Thanks

**Comment by Juliana-t** [comment]
This issue is not relevant anymore, closing it
