### ISSUE TITLE
ACIAR Learn -  Logo & Image change

### ISSUE THREAD

**Issue by sarahnarayan** [catalpainternational/canoe#1035]
Hi, 

We've had some feedback and would like to do the following changes on the ACIAR Learn App:

-UQ and Catalpa logo on top row and the ACIAR gov on second 
-ACIAR gov logo to change to inline logo. 
-Loading screen image change

Have saved the the new logo & image [here](https://drive.google.com/drive/folders/1K15B_92A8_A0KPVFoJriBxc50XiPf-E6?usp=sharing)

**Comment by Juliana-t** [comment]
@megganeturner ACIAR team requested some changes on partners logos and loading screen.
Can you please have a look at this issue and let @sarahnarayan know if you need any further information? Thanks!

**Comment by sarahnarayan** [comment]
Hi @megganeturner drive also has login vector now. Is there an estimated timeline for us?

**Comment by megganeturner** [comment]
Hi @sarahnarayan thanks for providing these updated assets! I've just created a pull request. Once it's merged it will be deployed on the next release.

For the loading screen image, ideally this should be a very small file (we don't want the entire site to download in less time than the loading screen image). I've had to compress the provided asset down quite a bit (from 2.1MB to 29KB), which has definitely decreased the quality of the image. This is why we recommend the use of SVGs here, as they are much more efficient 🙂

<img src="https://user-images.githubusercontent.com/12974326/136720409-cd19323a-5c5c-41e8-a733-06e6c73bbf17.png" width="250">
<img src="https://user-images.githubusercontent.com/12974326/136720482-017871dd-07bd-48d7-bf9d-e4dcec70e614.png" width="250">

**Comment by pedro16v** [comment]
This is what is currently published to the [staging server](https://aciar-staging.temp.build/)

| Loading | Profile |
| --- | --- |
![Screenshot 2021-10-22 at 12 23 06](https://user-images.githubusercontent.com/2813677/138388389-89a94467-2a11-4b6c-a097-40423b47b554.png) | ![Screenshot 2021-10-22 at 12 23 18](https://user-images.githubusercontent.com/2813677/138388381-55c11e70-9c9d-4b0b-82dc-b806f9c16443.png)

**Comment by sarahnarayan** [comment]
I think the logos are png. I'll add svg files to the folder. @megganeturner  Will that work ?

**Comment by megganeturner** [comment]
Yes please, thanks @sarahnarayan! SVGs are always the best format 😄

**Comment by sarahnarayan** [comment]
Hi @megganeturner thanks for this. We're going with the second option. The inline logo. 

And for the loading, we've changed the image. have put it in the same folder as above. a png & svg. 

I know we need to change that to a vector but for now we'll go with the image. 

Thank you.
