### ISSUE TITLE
Bero: Course completion illustration and animation

### ISSUE THREAD

**Issue by Juliana-t** [catalpainternational/canoe#1037]
### Overview
As part of the development of the visual system and assets for core Bero, we need an animation for the '[Course completed' screen](https://projects.invisionapp.com/d/main?origin=v7#/console/20251865/453511209/preview?scrollOffset=10060)

### Concept
Celebration, thumbs up, feeling of joy

### Conditions of satisfaction
- [ ] Create static illustration
- [ ] Apply illustration to the mockup (to confirm if it works well on the UI)
- [ ] Approve static illustration
- [ ] Animate illustration
- [ ] Export static illustration and animation and upload it to the Bero product drive
- [ ] Inform Product lead (Juliana)

### Resources
- [Briefing and creative direction](https://docs.google.com/document/d/1o1RvoAmWyBUoVeiwVZis5A9TSs9bdS2kT7h8EOUEj1o/edit#)
- [Check list Bero visual assets](https://docs.google.com/spreadsheets/d/1qurBq1GE5VbYy1jnH34uXtWwC7R9enhm1T0-_BN_1ZE/edit#gid=1579069067)
- [Screen UI](https://projects.invisionapp.com/d/main?origin=v7#/console/20251865/453511209/preview?scrollOffset=10060)

**Comment by Juliana-t** [comment]
@DanielHeads the thumbs up illustration is ready to be approved but can you please add here final illustration + mockup of it on the UI?

**Comment by DanielHeads** [comment]
[Illustration](https://projects.invisionapp.com/d/main#/console/21667206/459004900/preview)
[Screen Mockup](https://projects.invisionapp.com/d/main#/console/21667206/459004901/preview)

**Comment by Juliana-t** [comment]
I really like this one - for me it is approved - @davidcatalpa any additional comment or can we approve it?
