### ISSUE TITLE
All courses in a grid layout

### ISSUE THREAD

**Issue by katevoss** [catalpainternational/canoe#252]
CoS:

- [x] all courses in a grid 
- [x] each course has a title, and no other text on it
- [x] under heading "All Courses"
- [x] first incomplete or not-started courses
- [x] at end, complete courses
- [x] course tiles grow/shrink based on screen width

Design questions: 

- [x] How is the grid of courses responsive to a screen-width larger than 320px? 
     - Are the course tiles flexible and grow when they have additional space?
     - ~~Or are the tiles a set width/height, and as the screen grows then more tiles fit onto a row?~~

**Comment by andrewwapling** [comment]
Hi @katevoss , I would recommend course cards to increase in size increase in size incrementally for larger mobile devices. This way we retain consistent white space balance throughout the design. We still need to tackle the Tablet and Desktop breakpoints which may require some further design refinement to the way these cards appear on these larger breakpoints. 

Hope this helps and let me know if you have any further queries at all.

Thanks again, Andy

**Comment by katevoss** [comment]
@andrewwapling I've been working on making the course cards responsive and I worry that having the cards grow and shrink will be very complicated, especially with their images. I think it will be a large engineering challenge to keep the images looking great while resizing the cards, and make both look good. 

As an MVP the card dimensions will not change and on wider screens there will be more cards in a row.

**Comment by andrewwapling** [comment]
Hi @katevoss , Thanks for the update. Look forward to reviewing on staging and we can make further decisions and solutions from here. Thanks again, Andy
