### ISSUE TITLE
Show a course is in-progress, not started, or complete

### ISSUE THREAD

**Issue by katevoss** [catalpainternational/canoe#254]
CoS
- [x] course card can have these states:
   - [x] Active: no icon, no progress bar (not started)
   - [x] In-progress: progress bar, blue play icon
   - [x] Complete: progress bar 100% complete, green check icon

**Comment by andrewwapling** [comment]
Hi @katevoss, 

The key states of Course Cards are:

1. Active – No Icon, No Progress Bar
2. In Progress – Blue Arrow Button Flag, Progress Bar displaying current progress through course via Lesson Card progression
3. Complete – Green Check Flag, Progress Bar 100% complete 
4. New – New Flag sitting on edge of card

Lesson cards follow the same structure as above except there is also a state for lessons not yet ready to be completed:

1. Locked – Locked Flag, Greyed out tone and image desaturation

Hope this helps and sing out with any further queries at all.

Thanks again, Andy

**Comment by katevoss** [comment]
@andrewwapling can you export the icons for the blue "play" arrow, green "complete" check, and grey "locked" padlock? In InVision is fine https://invis.io/52Y02L9YTRF#/432778428_2C-_Course_Listing_-_Short_Version thanks!

**Comment by andrewwapling** [comment]
Hi @katevoss , No worries at all. I've marked these items as exportable and re-synced to Invision so that you can access and download these assets: https://invis.io/52Y02L9YTRF

Let me know if any queries issues at all.

Thanks again, Andy

**Comment by katevoss** [comment]
@andrewwapling Unfortunately the icons didn't export correctly, they show the words ("lock") rather than the visual (padlock)
![image](https://user-images.githubusercontent.com/2395211/98136435-ee789000-1e8e-11eb-9366-c977aa358510.png)

**Comment by andrewwapling** [comment]
Hi @katevoss , That's odd. I've just re-synced again and appears ok at this end now. Can you please check? I've also exported manually here to be doubly sure. Hope this helps, Andy
[Flags.zip](https://github.com/catalpainternational/canoe/files/5490999/Flags.zip)

**Comment by katevoss** [comment]
@andrewwapling The icons look correct on InVision now and thanks for also including them in a zip 👍🏻

**Comment by andrewwapling** [comment]
@katevoss Excellent! Thanks for confirming with me 👍
