### ISSUE TITLE
RFC: Lean boot

### ISSUE THREAD

**Issue by boerwastaken** [catalpainternational/canoe#269]
## Feature goals:

- determine minimal state set (IndexedDB, Cache, Serviceworker, Cookies, LocalStorage, ...) sufficient for booting Canoe
- adjust project code to minimize the amount of state needing special project-specific treatment from an Appelflap point of view

## Rationale

For PeP, there will need to be a way to transport state from a connected-and-updated Appeflap instance, to an Appelflap instance that hasn't ever seen the Internet (and might never). 

Condensed user story:

1. Teacher walks to the 3G tamarind tree, webapp pulls in updated lesson content & updated service worker & "app code"
2. Teacher walks to the school where there is no internet whatsoever
3. Teacher's device shares updated artefacts with student's devices
4. Student's devices, **some of which may be a blank slate, some of which may never ever see internet**, incorporate the updates

There are many pieces to that puzzle, but let's focus for a bit on the ones that concern Canoe and any Appelflapped project that needs browser state to be propagated in a P2P fashion.

### On selection
We don't necessarily always want transported state to be an exact clone of the originator state. For instance, a student likely has no business with a session cookie of the teacher, or with another student's lesson progress. So clearly, the to-be-transported state will need to be a **selection** of state, not bluntly "all state".

There's two places where such a selection could be encoded.

1. in Appelflap. Appelflap would need to know, for every Appelflapped project, exactly what things need transporting, and what things are secret/private stuff (login tokens, lesson progress). And when this selection changes - say the frontend adds a new LocalStorage item that should or should not be transported - then that would need to be reflected in the Appelflap code, which is not that easily accessible to a frontender who just wants to make a little change, and getting such a change out to devices is going to be a pain. That's clearly undesirable. 
Also — **when** is state finalized? It's clearly no good to transport half-constructed Caches. But how does Appelflap know when a Cache build has been completed? That's a decision which is up to the webapp, how would Appelflap know about that decision? :sob: 

2. in the webapp. The webapp knows when its serviceworker is updated and when its caches are complete. The webapp can also have knowledge of which things are private (session cookies, lesson progress) and which things are not. It can even decide on having separate Caches - for public stuff, and for private stuff, which opens up possibilities for easy-to-understand granularity of packing up & restoring, which we'll get to.
Clearly, this is the right place to encode selections. The webapp knows best. :raised_hands: 

### On transportable browser state item types

Every storage state item type (cookies, Caches, serviceworkers, IDB, LocalStorage, ...) needs handling for extraction and injection. Of course we want to write as little code as we can get away with, so we'd implement as little of these as possible in Appelflap. What is the minimum set?

1. ServiceWorker - the serviceworker itself, plus imported scripts. Without that, there'll be no offline functionality.
2. CacheStorage (so not the transparent browser cache). In the Canoe case, that's where lesson content is stored.

These concern almost always verbatim copies of server-originating data, so obviously these are necessary to make offline state offline-transportable.

As for the other types, for simplicity it would be good to keep them out of the essentials for a minimal-state anonymous webapp boot. Remember we're not trying to create exact clones of a webapp environment (as said, why would student A need student B's lesson progress state?), but rather, we're trying to get to just the point where have supplied enough state to the webapp so it doesn't **need** an internet connection to get on with things. The rest of the state (IDB state of lesson progress, LocalStorage state of username etc) should be reconstructed by the webapp, accommodating for the possibility it might never see a live internet connection (so don't let the user be stranded on a login screen, for instance).

### On granularity
On the target device, originator state will need to be merged in with originator state. What's the granularity for that? Individual cookies? Individual entries in individual IDB databases? Whole IDB databases? Clean-slate approach for IDB databases (remove all, add only what's defined in the incoming package)? What about caches?

For simplicity and predictability, I propose granularity on a by-name scale, coupled with replace-all.
Thus a webapp will be able to express:
- "the cache named `A` will now need to be packed up"
- "the serviceworker with origin `B` and scope `C` will now need to be packed up"

and then, on the receiving side, the strategy is append-or-replace. That is to say, an existing Cache with the same name as an incoming updated Cache will be wholly replaced, but any other Caches that exist on the target device will be preserved. Basically it's a lot like filesystem copying semantics that way! This also leaves the door open for webapps to decide on naming schemes that facilitate garbage collection — embed version info in the cache name, and have the service worker clean out previous incarnations. For instance that's what Gather does to enable atomic webapp upgrades. But for simple use cases it'll be sufficient to use the replacement mechanism and not worry about garbage collection.

### On protocol Webapp <-> Appelflap <-> peer Appelflaps+Webapps

It's too early to set anything in stone. I'm currently thinking along these lines:

1) a HTTP API (through Appelflap's built-in web server) in favour of a direct JS API (using a WebExtension bridge into native Android code). Mostly because I'm not sure I can make extension scripts available to the serviceworker context, and I would like to keep the option open for the orchestration to be done from a serviceworker context.

2) namespaces for pubsub of artefacts. In the Canoe context, this is to enable behaviour where a student app subscribes to just a subset of the artefacts published by peers. For instance, a teacher app connected to the internet might pull in Chemistry and Mathematics content. The webapp will store these in separate Caches, to be published in separate namespaces ("chemistry" and "mathematics" spring to mind as namespace name candidates). Now, say a student webapp is only subscribed to the "mathematics" namespace and not to the "chemistry" namespace (because they're not enrolled in chemistry classes). Then Appelflap will not download and incorporate any artefacts in the "chemistry" namespace. We need a subscription mechanism like that, because the teacher device doesn't know the student identities a priori, and the webapp is not involved in who-is-who-and-who-gets-what. We're not going to turn a webapp into a webserver with dynamic personalized content. 
There will be a default namespace which always gets pulled in. So for the simplest use cases one can pretend that the namespaces don't exist.

3) It may be possible to poke the serviceworker with a special push message to inform that an update has taken place. Though if the webapp is smart and uses versioning in its artefact naming schemes, the injectee webapp should be able to determine this independently with some work.

**Comment by PeteCoward** [comment]
Re-opening for more dicsussion how this might be achieved

**Comment by PeteCoward** [comment]
What I'm looking for is a when we load a page what happens... pseudocode being developed for comment

**Comment by boerwastaken** [comment]
I don't know how to read your phrasing. Are you developing that pseudocode you mentioned?

**Comment by boerwastaken** [comment]
See also https://github.com/catalpainternational/canoe/pull/287#issuecomment-734235171

**Comment by boerwastaken** [comment]
A major problem is that the app is booted before the required evidence (for distinguishing between blank slate and seeded slate) is in. That evidence can only be obtained async, so the entry page should get that evidence first, and only then mount the Riot app.

**Comment by PeteCoward** [comment]
see https://github.com/catalpainternational/canoe/pull/288 for psuedocode
```
// Canoe should
// 1. display data if it has it
// 2. display data quickly as possible ( even if old )
// 3. try to fetch data if it has to ( display something while it does )
// 4. not care if you are not logged in, if the data is present
```

I think the riot app can boot as long as it reacts to both blank and seeded states sensibly.

**Comment by boerwastaken** [comment]
I raise you, based on lessons learned in Gather:
```
// Canoe should
// 1. create & maintain internally fully coherent resource sets of serverside data
// 2. atomically switch between such resource sets (they're immutable, not updated in-place (well, not while in use))
// 4. by an automatic mechanism decoupled from navigation/display
// 5. so that webapp display code can always resolve references, guaranteed
// 6. so that webapp frontend code would never need to worry its little head about availability of certain data, whether to displays stale data, whether to try and fetch it, or whether to display something while it's fetching.
```
and for bonus points, also based on lessons learned in Gather:
```
// Canoe should
// 1. co-version data API and webapp code
// 2. so that the webapp doesn't create resource sets that can't be processed by an outdated webapp
// 3. display friendly nudges for 
//     a) logging in anew (if there's evidence that the token is no longer valid),
//     b) hopping online to refresh out-of-date resource sets
```

The bad news is that it would likely mean throwing out the cherished 750KB Workbox serviceworker. The good news is that all this and more\* is [implementable in a serviceworker weighing in less than 500 lines, including extensive comments.](https://github.com/catalpainternational/gather/blob/master/gather/surveydata/templates/sw.js).

\*) concurrent downloads, retries with backoff, progress reporting, auto-updates, signaling of dataset updates...
