### ISSUE TITLE
Make images look good enough (for now)

### ISSUE THREAD

**Issue by katevoss** [catalpainternational/canoe#311]
We have lots of images in the redesign but letting admins upload images is beyond the scope of this leg of work.

From @PeteCoward 
Maximum I would suggest is to provide different default logos for course / lesson / section I think.
Minimum is as is the little sprout for all.

**Comment by PeteCoward** [comment]
Some options for tasking and estimating improvements to this:

1. Selectable thumbnail images for courses and lessons
  - design provides X small assets for thumbnail use
  - existing content displays a single default image from that list
  - authors can select different images from the design provided images for both courses and lessons
  - these images are baked into the app code, not downloaded as content 
    - individual projects developers should be able to add/remove/delete images 
    - content authors cannot add/remove/delete images

2. Selectable thumbnail images for courses and lessons, which can be uploaded
  - existing content displays a single default image
  - authors or program staff can upload new images to an image library
  - authors can select different images from the image library to provide images for both courses and lessons
  - these images are content, need to be downloaded by the client this could impact network use
  - there is no control on image quality and suitability

**Comment by katevoss** [comment]
Hi @DanielHeads, could you make four stock images with the dimensions of 45px by 45px, in SVG format? The images will be for course, lesson, resource, and activity.

Here is a general example (that doesn't have the exact dimensions):
![image](https://user-images.githubusercontent.com/2395211/103722721-92211200-4f9e-11eb-8738-98f8ea6dfb63.png)

**Comment by DanielHeads** [comment]
Hi @katevoss, please find in this [link](https://drive.google.com/drive/folders/1Ysq42oNuPcafPUObg5FAm2Q35mFkcrn8?usp=sharing) the stock images in SVG. I did 6 different illustration 1 for course, 1 for lesson, and 3 for activity (content, objetive and text) If you need something more please let my know.

**Comment by katevoss** [comment]
@DanielHeads these are great, thank you!

**Comment by Juliana-t** [comment]
@DanielHeads illustrations are great!
I am just concerned that the blue tones used in 'Course' and 'Resource' illustrations are too close to the blue of the 'play' button. Please see the screenshot.
Maybe we can just modify colors of those 2 illustrations to lighter (or darker) tones.
![image (3)](https://user-images.githubusercontent.com/52807808/103838357-36ef3c80-50d0-11eb-8897-36993c0a7bf0.png)

**Comment by DanielHeads** [comment]
@katevoss & @Juliana-t I did the changes, Please find in the same [link](https://drive.google.com/drive/folders/1Ysq42oNuPcafPUObg5FAm2Q35mFkcrn8?usp=sharing)

**Comment by katevoss** [comment]
Thanks @DanielHeads, I've updated the images.

**Comment by Juliana-t** [comment]
Thanks @DanielHeads
I think we still need to do some more work on the course page, as you can see on the screenshot, illustration and button tones continue to be too close and would benefit from extra tone contrast.

![Screen Shot 2021-01-08 at 9 37 55 AM](https://user-images.githubusercontent.com/52807808/103961350-ab40e300-5197-11eb-9707-43a8cf3d5652.png)

**Comment by DanielHeads** [comment]
@Juliana-t Please check that I was change the illustrations this was the old color.

**Comment by Juliana-t** [comment]
Thanks Daniel! @katevoss can you please review and change the course illustration with the new one? Thanks!

**Comment by katevoss** [comment]
Here is the new course illustration
<img src="https://user-images.githubusercontent.com/2395211/104195714-fb66b200-53f0-11eb-9dac-b2695d97c7a3.png" width="400px" >

And with the continue learning banner
<img src="https://user-images.githubusercontent.com/2395211/104196529-e2123580-53f1-11eb-8c4e-adde79e3cf92.png" width="400px" >

**Comment by Juliana-t** [comment]
Cool! Much better with these tones!
