### ISSUE TITLE
How do we get to the settings page?

### ISSUE THREAD

**Issue by PeteCoward** [catalpainternational/canoe#313]
Short term solution is a settings cog icon in the top right of the profile page.

Long term solution ( implied in design system) is that the settigns are included in the profile page.

There may be a medium term solution we could consider.
Settings icon available on every page somewhere?

**Comment by Juliana-t** [comment]
@PeteCoward to keep some consistency with how the new DS is thinking profile/settings and a future implementation of that, I would say that the settings icon should be available only on the 'Profile' screen and not on every page. But happy to discuss this solution

**Comment by katevoss** [comment]
Fixed by https://github.com/catalpainternational/canoe/pull/334

**Comment by katevoss** [comment]
Closed as fixed for now
