### ISSUE TITLE
DS Screen - Course Page

### ISSUE THREAD

**Issue by PeteCoward** [catalpainternational/canoe#314]
## Current state 
<img width="206" alt="Screenshot 2021-01-07 at 11 29 51" src="https://user-images.githubusercontent.com/1092029/103843750-ba625b00-50db-11eb-9a42-ad31927f2487.png">

### Previous
<img width="30" alt="Screenshot 2021-01-06 at 11 38 55" src="https://user-images.githubusercontent.com/1092029/103722667-cedb2080-5013-11eb-8218-d800e53eb298.png">

## Design system elements
<img width="190" alt="Screenshot 2021-01-06 at 11 41 12" src="https://user-images.githubusercontent.com/1092029/103722791-1eb9e780-5014-11eb-8a4a-773cb3cb58db.png">

## Required changes
- [ ] Header
  - [ ] back to courses link
  - [ ] settgins cog link ( where search icon is )
  - [ ] no image 
- [ ] Details
 - [ ] NDS consistent styling 
 - [ ] Button ( use the blue one not the purple ) 
- [ ] Lessons
  - [ ] NDS consistent styling 
  - [ ] completed card style
  - [ ] locked / unlocked status
  - [ ] progress bar
![coursepage](https://user-images.githubusercontent.com/1092029/103723434-655c1180-5015-11eb-834f-d953f2caddd8.jpg)

**Comment by PeteCoward** [comment]
@katevoss @Juliana-t let me know if this kind of issue per page is useful

**Comment by Juliana-t** [comment]
@PeteCoward @katevoss we can ask Daniel to prepare a default image for that banner on the top of the screen

**Comment by Juliana-t** [comment]
@katevoss can we have the 'play' button to go to a lesson screen? If so, the right one is the blue circle and not this purple one

**Comment by PeteCoward** [comment]
I don't see much consistency in the design for button colour. Do we know what each means? Until we do I'd go with Blue for all buttons

**Comment by PeteCoward** [comment]
On the play button, just use whatever is there. If there is nothing, then no button needed here ( can be new issue )
On the header image I also recommend a new issue.

**Comment by Juliana-t** [comment]
A screenshot with the 'completed' and the 'play' (to start or continue a lesson) 
![Screen Shot 2021-01-06 at 1 20 59 PM](https://user-images.githubusercontent.com/52807808/103728813-56c82700-5022-11eb-9f75-2c92ba8c639e.png)
