### ISSUE TITLE
Remove logos from settings page

### ISSUE THREAD

**Issue by katevoss** [catalpainternational/canoe#328]
I believe they'll go on the Loading screen, right? @Juliana-t

**Comment by Juliana-t** [comment]
As for the MVP we will keep the settings screen, just updating its style, we can keep the logos on settings screens.
@soniasimoes we will need to discuss the new location of logos (according to the new DS) and ensure that is ok for Haroman

**Comment by katevoss** [comment]
Thanks @Juliana-t. I'll close this issue then since there are no changes to make.
