### ISSUE TITLE
Serviceworker: periodic ping

### ISSUE THREAD

**Issue by PeteCoward** [catalpainternational/canoe#35]
We need to make sure that users out there who have asteroid serviceworker actually get a new serviceworker without us having to contact every user and tell them refresh your browser please.

A simple periodic ping setup in the serviceworker to re-call register might be appropriate ( period to be discussed, but not too frequent )

**Comment by boerwastaken** [comment]
Gather implementation: https://github.com/catalpainternational/gather/blob/master/gather/js_src/swupgrader.js

In Gather the choice was made to be polite and ask the user whether they want to upgrade.

**Comment by PeteCoward** [comment]
I made the choice to get this in and up ASAP to reduce the number of stuck apps out there without waiting for official design. I'll raise this with design soon.
