### ISSUE TITLE
Get package publishing certificate from Appelflap

### ISSUE THREAD

**Issue by md8n** [catalpainternational/canoe#355]
As part of handling what packages (Manifest, Pages) can be `published` by Appelflap on Canoe's behalf (i.e. shared offline with other Canoe users),
there is a need for Canoe to get the package signing certificate from Appelflap in the first place.

This certificate may be unsigned or signed.  What Canoe does with it next is covered by separate issues

**Comment by boerwastaken** [comment]
if the cert is not signed, appelflap will refuse to create packages.

**Comment by md8n** [comment]
> if the cert is not signed, appelflap will refuse to create packages.

Correct. This issue is only about doing the `GET` of the cert.  Not what state that cert is in, and how Canoe responds to that state.
