### ISSUE TITLE
Login – Visual Design QA

### ISSUE THREAD

**Issue by andrewwapling** [catalpainternational/canoe#382]
Hi @Juliana-t ,

I have conducted visual design QA on the Canoe login screen and have identified a range of issues that would be worth resolving from a front end implementation perspective. I have marked up detailed feedback as comments on top of the screen in question.

Please see detailed annotations of the marked up staging server: https://invis.io/M410394K8N3K

Please see reference design here: https://invis.io/PAZ7H36R435

Hope this helps and kindly let me know if you have any queries at all.

Thanks again, Andy

**Comment by PeteCoward** [comment]
Recommend a pass touching most of Andy's feedback here.
Some questions...
- do we have button tapped interaction design?
- do we have deisgn for how the curve works on different screen sizes?

**Comment by Juliana-t** [comment]
I couldn't find the design for button interactions nor for the responsiveness of the curve on the inVision project but I believe there is a DSM, I don't have access to it so we need to wait for @andrewwapling

**Comment by Juliana-t** [comment]
We can move on with the review of other elements and leave this two for when Andrew gets back

**Comment by katevoss** [comment]
@PeteCoward can you or @Juliana-t do a review of the comments that Andrew made and specify what changes to make for this issue, then list them here? Similar to what Peter did for the Settings changes in #396 Thank you!

**Comment by andrewwapling** [comment]
Hi @PeteCoward @Juliana-t @katevoss @megganeturner,

Answers to your queries below:

1. Yes we have designed the tapped state of the buttons. The fully fledged DSM is still in progress however we have added the Primary button components please see: https://projects.invisionapp.com/dsm/catalpa/canoe-dsm

2. We have not yet tackled larger responsive breakpoints however I do believe these are on the roadmap for design including tablet and desktop.

I will review the FE refinements and post back if I see anything else worth attending to from a visual review perspective.

Thanks again, Andy

**Comment by andrewwapling** [comment]
Hi @katevoss @megganeturner,

The visual refinements to login look great! The are only a few small issues that I've picked up listed below:

• Let's add the tapped interaction state for the primary button here (and globally across buttons) to add the friendly tactile feel we're aiming to achieve

• The '••••••••' in the password field appear too large let's drop these in size by about 40%

• On mobile device the fields look great on Google Chrome desktop there's a white block that appears behind the in-field labels which hides some of the inner shadow of the field itself (this issue isn't persistent in Safari). This white block is also visible behind the show / hide control. Can we check and fix this?

Let me know if you require any further details at all.

Thanks again, Andy

**Comment by andrewwapling** [comment]
Hi @katevoss @megganeturner,

Further to this the the validation also displays the white block within the field on Chrome though not on Safari (please see attached screenshot).

Can we also please make the validated fields use the darker text colour (same as focused state #2A3942).

Thanks again, Andy

<img width="511" alt="Screen Shot 2021-02-16 at 5 43 31 pm" src="https://user-images.githubusercontent.com/13824612/108027756-c9dfa700-707e-11eb-8d2f-343f7c67fd66.png">

**Comment by megganeturner** [comment]
Thanks @andrewwapling! I'll get a start on these changes today.

I'm hitting a 404 on this link https://projects.invisionapp.com/dsm/catalpa/canoe-dsm - is this the right one?

**Comment by andrewwapling** [comment]
Hi @megganeturner, Thanks very much!

Yes that's the correct link. You could try this one too which links directly to the button components page: 

https://projects.invisionapp.com/dsm/catalpa/canoe-dsm/nav/5fa7cb6e8c01200018360885/asset/5f7bad97dfb1f3d2b7b67bcc/tab/design?mode=edit

The link above is to the DSM as a whole. I believe you'll need to login to Invision with your Catalpa address to view it.

Let me know how you get on.

Thanks again, Andy
