### ISSUE TITLE
Course Listing (Filters) – Visual Design QA and Translations update

### ISSUE THREAD

**Issue by andrewwapling** [catalpainternational/canoe#384]
Hi @Juliana-t ,

I have conducted visual design QA on the Canoe course listing (filters) screen and have identified a range of issues that would be worth resolving from a front end implementation perspective. I have marked up detailed feedback as comments on top of the screen in question.

Please see detailed annotations of the marked up staging server: https://invis.io/DP10395DMB8Y

Please see reference design here: https://invis.io/4G10395FNRQA

Hope this helps and kindly let me know if you have any queries at all.

Thanks again, Andy

**Comment by katevoss** [comment]
I'm adding translations to this issue since it's a very small issue on its own.

**Comment by andrewwapling** [comment]
Hi @katevoss @megganeturner ,

Due to the compromised implementation of the filters i.e. blend of modal filter styles and the in page graphical circular filter styles this issue would probably be best merged with 383 following: https://github.com/catalpainternational/canoe/issues/383

I have reviewed this one and added design recommendations to an annotated PDF in 383.

Hope this helps and let me know if you have any queries at all.

Thanks again, Andy

**Comment by pedro16v** [comment]
Closed in favour of #393
