### ISSUE TITLE
Course Detail (level 2 MVP) – Visual Design QA

### ISSUE THREAD

**Issue by andrewwapling** [catalpainternational/canoe#386]
Hi @Juliana-t ,

I have conducted visual design QA on the Canoe course detail (level 2 MVP) screen and have identified a range of issues that would be worth resolving from a front end implementation perspective. I have marked up detailed feedback as comments on top of the screen in question.

Please see detailed annotations of the marked up staging server: https://invis.io/S910395OHEMF

Please see reference design here: https://invis.io/9FZNZQNBU5H

Hope this helps and kindly let me know if you have any queries at all.

Thanks again, Andy

**Comment by PeteCoward** [comment]
- [ ] make top menu back button match design
- [ ] Current
<img width="235" alt="Screenshot 2021-02-09 at 15 15 18" src="https://user-images.githubusercontent.com/1092029/107323513-bd40d900-6ae9-11eb-9685-30ef6eba1f9e.png">
Redesign
<img width="227" alt="Screenshot 2021-02-09 at 15 15 50" src="https://user-images.githubusercontent.com/1092029/107323508-bb771580-6ae9-11eb-932f-cb423e937f19.png">

**Comment by andrewwapling** [comment]
Hi @katevoss @megganeturner,

Thanks for the updates, looking good. I've marked up a range of small visual elements that would be worth refining from a FE perspective so that we can more closely align with design.

Please see attached annotated PDF.

[CourseDetail.pdf](https://github.com/catalpainternational/canoe/files/5986703/CourseDetail.pdf)

Let me know if you have any queries at all.

Thanks, Andy
