### ISSUE TITLE
Cards – Visual Design QA

### ISSUE THREAD

**Issue by andrewwapling** [catalpainternational/canoe#392]
Hi @Juliana-t ,

I have conducted visual design QA on the Canoe card screens and have identified a range of issues that would be worth resolving from a front end implementation perspective. I have marked up detailed feedback as comments on top of the screen in question.

Please see detailed annotations of the marked up staging server: https://invis.io/FE10397XD5RQ

Please see reference design here: https://invis.io/KW1039632BJ7

Hope this helps and kindly let me know if you have any queries at all.

Thanks again, Andy

**Comment by Juliana-t** [comment]
@andrewwapling please review the screenshots and add more feedback from your visual review

**Comment by andrewwapling** [comment]
Hi @Juliana-t , 

No problem to add more feedback however  I couldn't see any screenshots attached. Can you please advise?

Thanks again, Andy
