### ISSUE TITLE
Resources Listing – Visual Design QA

### ISSUE THREAD

**Issue by andrewwapling** [catalpainternational/canoe#393]
Hi @Juliana-t ,

I have conducted visual design QA on the Canoe resources listing screen and have identified a range of issues that would be worth resolving from a front end implementation perspective. I have marked up detailed feedback as comments on top of the screen in question.

Please see detailed annotations of the marked up staging server: https://invis.io/U9103989678S

Please see reference design here: https://invis.io/3G10398H6MJX

Hope this helps and kindly let me know if you have any queries at all.

Thanks again, Andy

**Comment by PeteCoward** [comment]
My recommendations:

- [ ] make header consistent with design

<img width="205" alt="Screenshot 2021-02-03 at 17 09 01" src="https://user-images.githubusercontent.com/1092029/106717085-8f1f4d00-6642-11eb-8ff9-66d128946bd5.png">

- [ ] make tags consistent ( uppercase )

<img width="200" alt="Screenshot 2021-02-03 at 17 08 54" src="https://user-images.githubusercontent.com/1092029/106717094-90e91080-6642-11eb-8ccf-3cd6caa62119.png">

- [ ] make resource entries horizontal rows showing title and description

<img width="202" alt="Screenshot 2021-02-03 at 17 08 45" src="https://user-images.githubusercontent.com/1092029/106717090-90507a00-6642-11eb-8267-53a1f05e5bf9.png">

Resources don't currently have types, or associated images, and we need to decide about whether to always show the search or on tapping the magnifier glass ( and find or make a design for the search, it may exist already somewhere )

**Comment by Juliana-t** [comment]
@PeteCoward agreed!

**Comment by andrewwapling** [comment]
Hi @PeteCoward @megganeturner @katevoss ,

Sounds like a good compromise on implementation. Let me know if you require any additional support on this issue.

Thanks again, Andy
