### ISSUE TITLE
Resources Detail – Visual Design QA

### ISSUE THREAD

**Issue by andrewwapling** [catalpainternational/canoe#394]
Hi @Juliana-t ,

I have conducted visual design QA on the Canoe resources detail screens and have identified a range of issues that would be worth resolving from a front end implementation perspective. I have marked up detailed feedback as comments on top of the screen in question.

Please see detailed annotations of the marked up staging server: https://invis.io/Z410398MR3N8

Please see reference design here: https://invis.io/G9108GUJAMZR

Hope this helps and kindly let me know if you have any queries at all.

Thanks again, Andy

**Comment by PeteCoward** [comment]
Recommend we implement
- [ ] header bar as per design
<img width="192" alt="Screenshot 2021-02-03 at 16 48 00" src="https://user-images.githubusercontent.com/1092029/106714900-d1935a80-663f-11eb-95b1-3973dc433200.png">

We have to discuss the rest, what resources are in Canoe is a series of content cards ( like lesson content )
We can implement the Basic card display to look like the element below ( ignoring the scribbled out bits ), but we'd need to render all cards in a vertical scroll layout.
<img width="216" alt="Screenshot 2021-02-03 at 16 51 32" src="https://user-images.githubusercontent.com/1092029/106715473-73b34280-6640-11eb-94b4-be1cbb2360c9.png">

**Comment by Juliana-t** [comment]
this is the correct reference screen > https://projects.invisionapp.com/share/TBYZBD5NFRC#/screens/429853510

**Comment by andrewwapling** [comment]
Hi @PeteCoward @megganeturner @katevoss , 

This sounds like a good interim solution. I have also updated the issue with the correct screen design reference.

Let me know if there's any design queries or if I can help with anything else on this one.

Thanks again, Andy
