### ISSUE TITLE
Profile – Visual Design QA

### ISSUE THREAD

**Issue by andrewwapling** [catalpainternational/canoe#395]
Hi @Juliana-t ,

I have conducted visual design QA on the Canoe profile screen and have identified a range of issues that would be worth resolving from a front end implementation perspective. I have marked up detailed feedback as comments on top of the screen in question.

Please see detailed annotations of the marked up staging server: https://invis.io/3P10398YTXY4

Please see reference design here: https://invis.io/9U103993JE8Y

Hope this helps and kindly let me know if you have any queries at all.

Thanks again, Andy

**Comment by PeteCoward** [comment]
My recommendations...

- [ ] Make the Course Progress header consistent with design
- [ ] add box shadow to the cards
- [ ] evaluate time required to make tabbed In Progress / Completed display ( and confirm what to do with unstarted courses, just leave out I guess )

<img width="204" alt="Screenshot 2021-02-03 at 16 39 25" src="https://user-images.githubusercontent.com/1092029/106714382-208cc000-663f-11eb-9f4a-e73fa47d8503.png">

**Comment by andrewwapling** [comment]
@Juliana-t @PeteCoward It would definitely be valuable to assess tab implementation effort as they're a component that's used in a number of places.

Let me know if you required any additional design support on this one at this stage.

Thanks again, Andy

**Comment by katevoss** [comment]
@Juliana-t @andrewwapling What should we show if a user has no Completed courses? What should we show if a user has no courses that are In Progress? 
#### Options
1. show a message like "you have not completed any courses yet" and "you have no courses in progress". 
2. default to show all courses if there is nothing in that view (completed courses or in progress)
3. something else

**Comment by Juliana-t** [comment]
I thought that when users don't have any couse in progress, that section
won't be shown. Same if the user hasn't completed any course yet. But I
will like to hear from @Andrew Wapling <andrew@andrewwapling.com> if this
was designed with this specs

**Comment by andrewwapling** [comment]
Hi @Juliana-t , This would definitely be one solution and a path of least resistance for MVP. 

The other solution that I had in mind (yet to be designed) is adding descriptive text paired with an icon and CTA to direct users to start learning and exploring courses. The benefit of the latter approach is that it can help add to learning impetus and discoverability of courses.

I can create design direction for this if everyone is happy with this approach, please advise?

Thanks, Andy
