### ISSUE TITLE
Profile (Settings) – Visual Design QA

### ISSUE THREAD

**Issue by andrewwapling** [catalpainternational/canoe#396]
Hi @Juliana-t ,

I have conducted visual design QA on the Canoe profile (settings) screen and have identified a range of issues that would be worth resolving from a front end implementation perspective. I have marked up detailed feedback as comments on top of the screen in question.

Please see detailed annotations of the marked up staging server: https://invis.io/N910399DW4EH

Please see reference design here: https://invis.io/4S10399MTBZQ

Hope this helps and kindly let me know if you have any queries at all.

Thanks again, Andy

**Comment by PeteCoward** [comment]
I'd recommend for this screen addressing the following
- [ ] styling of labels
- [ ] styling of toggle
- [ ] styling of select
- [ ] styling of button

The overall layout should wait for the larger work item that is reorganising to include the settings as part of the profile screen.


Label / toggle / select 
<img width="205" alt="Screenshot 2021-02-03 at 16 20 37" src="https://user-images.githubusercontent.com/1092029/106712270-0d2c2580-663c-11eb-81eb-ff355f9faf5f.png">
Button
<img width="196" alt="Screenshot 2021-02-03 at 16 20 50" src="https://user-images.githubusercontent.com/1092029/106712263-0b626200-663c-11eb-8759-535c5f73e328.png">

**Comment by PeteCoward** [comment]
also see my response to comments in https://projects.invisionapp.com/share/N910399DW4EH#/screens/443806506/comments

**Comment by andrewwapling** [comment]
Hi @PeteCoward @Juliana-t @katevoss @megganeturner ,

Thanks very much, the FE improvements are looking good. I have marked up a range of small feedback points that would be great to action to further refine this screen.

Pleases see attached annotated PDF.

[ProfileSettings.pdf](https://github.com/catalpainternational/canoe/files/5986483/ProfileSettings.pdf)

Thanks again, Andy
