### ISSUE TITLE
Mitigate security risks from 'publishing' cached content

### ISSUE THREAD

**Issue by md8n** [catalpainternational/canoe#398]
# Description

We currently have three types of items that we cache for offlining support that we want to be publishable via Appelflap.

Caching performed by the service worker uses the original request for some url as the key, and then the response to that request as the value.
However, the original request will have security credentials held within it (`authorization` tag in the headers).

We currently have code for `Page` that cleans this sensitive data out of the request before writing it to the cache (it also cleans it out of pre-existing cache entries whenever they are referenced again by the app).

We need this same behaviour for `manifest` and `asset` classes.

**Comment by boerwastaken** [comment]
If the above request mangling becomes unwieldy, another inroad to this problem would be to pass the header keys to scrub to Appelflap when packing up a Cache. Appelflap can filter them out while serializing the Cache.

But simply not storing that data in the Cache in the first place (it's unnecessary anyway) strikes me as cleaner.

**Comment by md8n** [comment]
I've already got the code working for cached Pages, just need to get Manifest and Asset to use the same code.
It's also a good chance for a small refactor, breaking that code out into its own module.

**Comment by boerwastaken** [comment]
Might there be a potential problem around opaqueresponses though?
