### ISSUE TITLE
Request persistent Storage

### ISSUE THREAD

**Issue by PeteCoward** [catalpainternational/canoe#41]
... add more details

**Comment by boerwastaken** [comment]
the doc I referred to when I talked to you about this: https://developer.mozilla.org/en-US/docs/Web/API/StorageManager/persist

refresher: "normal storage" may get blown away when running low on disk space or $other_browser_whim, persistent storage should not get blown away unless the user explicitly tells the browser to do so:
https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria#Different_types_of_data_storage
