### ISSUE TITLE
Overridable Notifications Header

### ISSUE THREAD

**Issue by PeteCoward** [catalpainternational/canoe#42]
https://github.com/catalpainternational/canoe/pull/40/commits/e141dc8934e2bdf70e6e92a7d183b4c7ce97eaad turned our notifications header from an olgeta themed one to an asteroid themed one.

It's a shortcut for now as Asteroid is higher priority.

We need to copy the site_logo override pattern for the notifications header, and either standardise the css by updating the olgeta image, or override the css too.

I favour standardisation.

**Comment by pedro16v** [comment]
I’m considering this Done on ASTEROID. I’m not sure how I could validate it at the moment.
