### ISSUE TITLE
Canoe Course / Lesson Card Sizes

### ISSUE THREAD

**Issue by andrewwapling** [catalpainternational/canoe#437]
Hi @megganeturner @katevoss ,

I've noticed the card sizes and ratios in Canoe seem a bit off to the design. For example the current staging shows cards that are quite short in height compared to the design. This could also be impacting max character lengths.

Please see screenshots here for comparison:

Staging: 156px w x 177px h

<img width="179" alt="Screen Shot 2021-02-23 at 9 43 26 am" src="https://user-images.githubusercontent.com/13824612/108779870-ac00cd80-75bb-11eb-9000-8828616a323e.png">

Design: 133px w x 182px h

<img width="305" alt="Screen Shot 2021-02-23 at 9 43 47 am" src="https://user-images.githubusercontent.com/13824612/108779891-b622cc00-75bb-11eb-9d02-092f4e7fd294.png">

Can we kindly review and adjust to match the design sizing and ratios?

Thanks again, Andy

**Comment by megganeturner** [comment]
Just noting there'll be some crossover here between #441 and this one - it might be best to close this ticket in favour of 441?

**Comment by katevoss** [comment]
Good idea Meggan. I'll close this issue in favor of #441
