### ISSUE TITLE
All courses page

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#441]
# Overview 
Following a design review meeting, here's some fixes that would be great to get in as we transition to Release One work.

* Check the meeting's [InVision Freehand ](https://projects.invisionapp.com/freehand/document/ZUJn1e00N)
* Ping @andrewwapling in the comments if you need any further clarification

# Notes
- [x] Reduce space between main title "All courses" and text below (5-10px).
- [x] Reduce text box under the title to 80% width. (leave a right gap to the filter button)
- [x] Add "All Courses" section header
- [x] Make cards taller (+20px)
- [x] Slightly increase space between the rows of cards
- [x] Determine the text box size for the title (3 lines). Adjust font size.
  - [x] Fallback for overflowing text ?
- [x] Preserve the space for the progress bar.
  - [x] It can sit much lower
- [x] Card title should be aligned to the top, not the middle
  - [x] Line height can be tighter
- Image height can be reduced if we still need space
- Cards have fixed height but grow horizontally
  - We need it to grow consistently and have a min-width and max-width

**Comment by katevoss** [comment]
@megganeturner Would you also address the card frame issue https://github.com/catalpainternational/canoe/issues/364? I'm still seeing it on Browserstack and it would be good to fix while working on this issue
<img src="https://user-images.githubusercontent.com/2395211/108877451-3d2c7000-75cd-11eb-99f9-f01b0f0c0e8e.png" width="300">

<img src="https://user-images.githubusercontent.com/2395211/108877719-811f7500-75cd-11eb-9f52-501724b5941c.png" width="300">

**Comment by megganeturner** [comment]
> @megganeturner Would you also address the card frame issue #364? I'm still seeing it on Browserstack and it would be good to fix while working on this issue

Sure thing! Though I'll put this in a separate PR - I think it might get hacky and it would be good to have it isolated if we need to roll it back!
