### ISSUE TITLE
Course page

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#442]
# Overview 
Following a design review meeting, here's some fixes that would be great to get in as we transition to Release One work.

* Check the meeting's [InVision Freehand ](https://projects.invisionapp.com/freehand/document/ZUJn1e00N)
* Ping @andrewwapling in the comments if you need any further clarification

# Notes
- [x] Add v-padding below the title
- [x] Add v-padding between the curve and the first header title ("your lessons")
- [x] Double the height between rows (your lessons / course exam)
- [x] Make the green tick and blue start buttons bigger. Circle and icon.

**Split to new issue?**
- Need course description and category (example: "social media")
  - Course description text
  - Course details text

**Comment by katevoss** [comment]
I made a new issue for adding a category and description for courses https://github.com/catalpainternational/canoe/issues/447
