### ISSUE TITLE
Add course description and category

### ISSUE THREAD

**Issue by katevoss** [catalpainternational/canoe#447]
Add the fields to Wagtail, add them to Canoe too

- [ ] Course description text
- [ ] Course details text

Questions for @Juliana-t @KaraChesal @andrewwapling 

1. Is a course required to have a category?
2. Can a course have multiple categories? (not recommended)
     2a. If so, what's the max number of categories a course can have?
3. What is the longest a category name can be?
4. What is the longest a course description can be?
5. Is a course required to have a description? (not recommended)

**Comment by pedro16v** [comment]
Hi @katevoss, according to [this document](https://docs.google.com/document/d/1abMotyO302qfmm9A2e98G0UtjgZEewfzQ0ztV54qAZs/edit#heading=h.epdth1nxwqm5), we'll have:

- [ ] Hero image
- [ ] Course description:
  - [ ] Short text (char limit: ???, no styling allowed)   
  - [ ] Long text (char limit: ???; optional field, no styling allowed)
- [ ] Call-to-Action button (Start, Continue, Repeat)


- [ ] Course Category Subtitle (char limit: ???)
  - Note: this title is not needed for Release One. However, if it's easier to code in a placeholder and style it, do go ahead. We'll simply have to hide it as we're not feeding that information yet.

**Comment by Juliana-t** [comment]
Also related to this, I just dropped some comments on the mockup for this screen on [invision](https://projects.invisionapp.com/d/main?origin=v7#/console/20251865/445497256/comments?scrollOffset=3870) (pinging @andrewwapling )

**Comment by andrewwapling** [comment]
Thanks @Juliana-t , Just confirming I've responded back with recommendations to the queries and comments in Invision. Thanks, Andy

**Comment by PeteCoward** [comment]
@pedro16v @Juliana-t do any of those comments in invision change the description of what is required above?

**Comment by Juliana-t** [comment]
Answering to some outstanding questions from Kate:
_1. Is a course required to have a category?_ - For legacy reasons I think it shouldn't be mandatory (Haroman for example)
_2. Can a course have multiple categories? (not recommended)_ - Lets start with 1 category, review later if we find multiple categories are required by our clients
2a. If so, what's the max number of categories a course can have?
_3. What is the longest a category name can be?_ - for JID we will need some long names such as Infection Prevention Control but not sure if the current design can support this (ping @andrewwapling )
_4. What is the longest a course description can be?_ - on Pedro's comment in the issue
_5. Is a course required to have a description? (not recommended)_ - short description mandatory, long description is optional

**Comment by andrewwapling** [comment]
Hi @Juliana-t @PeteCoward ,

The above recommendations sound good to me. Responses below.

1. We could perhaps place courses that aren't in a specific category into a global or general category
3. Course category headers can currently accomodate 31 characters so yes current state design can cater for long categories such as Infection Prevention Control. If we do encounter categories longer than 31 characters we could look at the following options:
   - Truncating course category titles (perhaps borrowing from the work we've done with truncating course titles within cards)
   - Uplifting the design to cater for double line course category titles
   
Hope this helps, Andy

**Comment by pedro16v** [comment]
To be continued on #577
