### ISSUE TITLE
After selecting a category, I can see a list of Learning Activities for that category

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#456]
## Conditions of Satisfaction
* The Learning Activities are grouped by topics (in the sea, on the road, etc)
* Each Learning Activities has:
  * A reference
  * A title
  * A thumbnail
* ~~I can make the activity offline~~
  * ~~Activities are labeled as “available offline” if already downloaded~~
* Completed Learning Activities show a green tick button
* Ongoing lessons show a blue “continue” button

## Resources
* Engineering estimate: Day to Days
* Reference design: [Learning Activities - Listings](https://projects.invisionapp.com/share/6V102V1VURS9#/screens/443710124)

**Comment by katevoss** [comment]
@pedro16v as I understand from the [comments on InVision](https://projects.invisionapp.com/d/main/#/console/21052158/443710124/comments/140930409#project_console), the "click to make offline" functionality is not in Release One, is that correct?

**Comment by pedro16v** [comment]
You are correct. This issue hadn't been updated. Thanks for noticing and letting me know!

**Comment by pedro16v** [comment]
To be continued in #458
