### ISSUE TITLE
I can mark Learning Activities as complete

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#458]
## Conditions of Satisfaction
* Marking the Activity as complete will take me to the feedback screen
* This option is always accessible while navigating the Activity

## Resources
* Engineering estimate: Days (2)
* * Reference design: [Learning Activities - Detail](https://projects.invisionapp.com/share/6V102V1VURS9#/screens/443710125)

**Comment by pedro16v** [comment]
I closed #456 and I'd like to carry over two CoS here:

On the Learning Activities listing:
- [ ] Completed Learning Activities show a green tick button
- [ ] Ongoing lessons show a blue “continue” button

**Comment by katevoss** [comment]
How do we know if a teaching plan is "ongoing"? What has a user done to indicate a specific plan is in progress?

**Comment by katevoss** [comment]
Removing myself from this issue as the FE is complete but is still waiting on BE.

**Comment by pedro16v** [comment]
> How do we know if a teaching plan is "ongoing"? What has a user done to indicate a specific plan is in progress?

My bad! I have now removed that. Must've copied that from somewhere else. 

Looking at InVision, learning activities only show the green tick.

**Comment by PeteCoward** [comment]
reviewable on https://pep-staging.temp.build
