### ISSUE TITLE
Users can include animations/interactive content in cards

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#466]
Users should be able to embed pre-existing animations such as [HTML5 science simulations](https://phet.colorado.edu/)

## Conditions of satisfaction
* Users can embed HTML code in cards.

## Resources
* Engineering estimate: Week

## Notes
* Wagtail has a special way of going about embedding things.
* The examples by Kara are encapsulated files that you could upload.
* Needs investigation on the engineering side. But we trust it to be easy.

**Comment by PeteCoward** [comment]
from #380  
- [ ] html5 animation (canvas element) - [resource](https://codepen.io/juliangarnier/pen/idhuG)

**Comment by PeteCoward** [comment]
@katevoss what I suggest you investigate is just an iframe solution. User in CMS enters an Iframe url, frontend renders an iframe with that src.

We cannot allow content editors to directly upload javascript to execute in the canoe window scope, this is a security restriction.
