### ISSUE TITLE
Multiple / single choice with image card

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#467]
A new type of card for QUIZ AND EXAM TYPES

## Conditions of satisfaction
* Users are presented an image
* Users will have to pick the correct options from available choices to match the image.
* Answers can be single or multiple choice:
  * If single choice, users are only allowed to pick one answer.
  * If multiple choice, users can select more than one answer.

## Resources
* Engineering estimate: Days
* Reference design: [InVision](https://invis.io/JB10CCDPU7HF)

## Notes
* Simple task if it means we’re only adding an image to the card.
* Becomes less simple if a whole new design comes with it.
* Not a priority for JID. Nice to have for JID & PeP.

**Comment by pedro16v** [comment]
Updated with screens from InVision. https://invis.io/JB10CCDPU7HF

@andrewwapling could you confirm these are the appropriate designs for this issue? Thank you.

**Comment by andrewwapling** [comment]
Hi @pedro16v, Thanks for flagging this with me. Yes the link above is correct :)

Let me know if there's any queries or you require anything further at all on this one.

Thanks again, Andy

**Comment by PeteCoward** [comment]
@pedro16v  I think this needs a bit more info, what happens when there are more than 2 options? Can there be more than 2 options?
Do we have a design for when more than one option is correct...
screen shot of invision here for convenience
<img width="214" alt="Screenshot 2021-03-18 at 15 07 06" src="https://user-images.githubusercontent.com/1092029/111580982-cfeeb200-87fb-11eb-8688-033bbb25ee18.png">

**Comment by pedro16v** [comment]
This is all there is in InVision. I've asked @andrewwapling about this.

**Comment by andrewwapling** [comment]
Hi @pedro16v @PeteCoward ,

My thinking here is that we could let this card scroll vertically if the content is too long.

And yes we have an example of a x4 multi choice selection card here: https://invis.io/CU10IVKNP3F5

The only difference here is that there’s no image inserted at top of screen on the above design pattern.

Hope this helps, Andy

**Comment by PeteCoward** [comment]
We can proceed with that. I suspect we might have a usability issue with showing answer options that you have to scroll to see, but we'll build it and you can evaluate.
