### ISSUE TITLE
Canoe app is branded for different deployments

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#471]
## Conditions of Satisfaction
* There is a project brand identity 
* A number of visual elements of the app are styled accordingly to the brand identity developed for the project
  * Loading screen
  * Login screen
  * Banners 
  * Placeholders
    * Courses
    * Lessons
    * Objectives
    * Contents
    * Test
    * Exam
  * App icon
  * Browser favicon
* Some texts are modified for Canoe through Wagtail
  * Example:  Text on the top banner of ‘all courses’ screen 
* Language options

## Resources
* Engineering estimate: Days

## Notes
* PeP doesn’t require branding.
* Branding should be easy enough. It's content and static images. All text should be editable on Wagtail.

**Comment by katevoss** [comment]
Technical note: to make the overrides appear you need to add this stanza to your `canoe-project.js` in `catalpa_Canoe`:
```
resolve: {
            modules: [path.resolve(__dirname, "canoe-overrides")],
        },
```

Every time you add to the canoe-overrides (an image, override a riot tag, etc), you'll need to stop and re-run `run-canoe.sh` so the new file to override is picked up.

**Comment by katevoss** [comment]
I'm removing myself from this ticket and in my place I leave a draft PR (https://github.com/catalpainternational/catalpa_canoe/pull/9) which has the infrastructure to brand Canoe.

A few things to remember:
- file names must match exactly, including the file type (svgs replace svgs, not pngs)
- if you overwrite a riot tag or scss file, you have to overwrite the whole thing
- when you add (or remove) a file to overwrite, you have to restart `run-canoe.sh`
