### ISSUE TITLE
Admins can see M&E data (weeks)

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#473]
## Conditions of Satisfaction
* Storing data
* Easy access to data
  * Option to setup dashboards in Google Analytics
  * Option to setup scheduled email reports 
  * Option to port G.A data into Google Data Studio
* Capture user’s feedback (smile / frown at the end of each lesson) on Wagtail
  * Test results saved to the Wagtail Database 
* Monitor impact of training
  * Completion of training modules
  * Trainees enrolled in the training program engagement with online platforms
    * % quizzes completed
    * Number of contributions to group discussions/webinars
    * % modules completed
    * % lectures watched (real time and recorded)
  * Disaggregated by (days): 
    * health worker type, 
    * experience, 
    * age, 
    * gender, 
    * health facility/department
  * Export data / tables (days)

### Update! (2021-05-11)
* Exam results
  * First score (first attempt)
  * Best score
  * Number of attempts

## Resources
* Engineering estimate: Weeks

## Notes
* Nicer interfaces can be pushed to Release Two.

**Comment by PeteCoward** [comment]
@sandroroux to start on this I suggest that as discussed you concentrate on verifying that the data is being submitted and stored.

I think the best approach to this is to use https://docs.wagtail.io/en/stable/advanced_topics/customisation/custom_user_models.html

Individual projects would provide and configure a custom user model and custom user forms. This way the attributes are easy to change and add to per project.
You can play around in catalpa_canoe, ideally zero changes to canoe-backend should be required. 

For JID, we should try adding the following attributes

- [ ] health worker type ( foreign key to a model editable in the admin )
- [ ] experience ( no real clue so maybe another  foreign key to a model editable in the admin )
- [ ] age ( I would suggest integer Year Of Birth for this maybe current year minus 100 to current year )
- [ ] gender ( foreign key to a model editable in the admin - this list can be very dependent on culture )
- [ ] health facility/department ( foreign key to a model editable in the admin )

@Juliana-t can we discuss now which of the above should be editable for the JID deployment?
@KaraChesal we will need to discuss what attributes are needed for the PeP deployment

**Comment by pedro16v** [comment]
> I'm using #492 to meet this Pedro-described requirement:
> 
> > Capture user’s feedback (smile / frown at the end of each lesson) on Wagtail
> > Test results saved to the Wagtail Database

It's actually a Juliana-described requirement 😁 
I'll make sure to work with @Juliana-t describing these requirements further.

**Comment by Juliana-t** [comment]
@sandroroux @PeteCoward Just received inputs from JID on the user's attributes, values for each, and required/mandatory
Please see this [spreadsheet](https://docs.google.com/spreadsheets/d/1ZFWxbJZwD1h6H4pp5fioGWRj92HRkpK2OYQN1LlzWbE/edit#gid=0) and let me know if you have any further questions so I can get back to JID if needed

**Comment by sandroroux** [comment]
@Juliana-t Would you like these attributes to be mandatory (that is, when a user creates an account, they must provide answers to those fields).

**Comment by Juliana-t** [comment]
@sandroroux as you can see on row 5 of the spreadsheet, JID defined all attributes as mandatory

**Comment by sandroroux** [comment]
Awesome. My apologies for missing that. Thanks, @Juliana-t.

**Comment by sandroroux** [comment]
@PeteCoward and I agreed to a set of outcomes for this issue.

- [ ] Confirm that JID's Canoe generates the data that this spreadsheet's "Collected Data" tab lists.
- [ ] Generate queries that restructure `UserAction`s so that they're easy to analyze in data studio.
- [ ] TBD: Create Data Studio `UserAction` visualizations.

**Comment by sandroroux** [comment]
JID Production generates these UserAction types:
```python
In [5]: UserAction.objects.distinct("data__type").values("data__type")
Out[5]: <QuerySet [{'data__type': 'completion'}, {'data__type': 'exam.answer'}, {'data__type': 'exam.finalScore'}, {'data__type': 'feedback'}]>
```

**Comment by sandroroux** [comment]
## Useful SQL Queries
Showing completions in a table:
```sql
SELECT "user_actions_useraction"."id",
       "user_actions_useraction"."user_id",
       "user_actions_useraction"."action_uuid",
       "user_actions_useraction"."created",
       "user_actions_useraction"."data",
       ("user_actions_useraction"."data" -> 'course') AS "course",
       ("user_actions_useraction"."data" -> 'lesson') AS "lesson",
       ("user_actions_useraction"."data" -> 'section') AS "section"
 FROM "user_actions_useraction"
 WHERE ("user_actions_useraction"."data" -> 'type') = '"completion"'
```

**Comment by boerwastaken** [comment]
@PeteCoward Feedback items will need streamlining with the other event types as in #665. Currently they don't reference the page revision.
