### ISSUE TITLE
Resources – Visual Refinements

### ISSUE THREAD

**Issue by andrewwapling** [catalpainternational/canoe#485]
Hi @Juliana-t @katevoss @megganeturner,

I've conducted a visual review of the latest release Resources screens.

I have marked up some small visual refinements that I would recommend implementing from a FED perspective so that we align as closely as possible with the new design system.

Please see comments pinpointing issues on the Invision Prototype:

• https://invis.io/K910BUZPDBSU
• https://invis.io/2T10BUZWDN9J
• https://invis.io/5410BUZXC9GN

Hope this helps and drop me a line with any queries at all.

Thanks again, Andy

---

### InVision summary

- [x] [Boost tag size](https://projects.invisionapp.com/share/K910BUZPDBSU#/screens/445952614/comments/140923932)
- [x] [Increase padding below filters](https://projects.invisionapp.com/share/K910BUZPDBSU#/screens/445952614/comments/140923946)
- [x] [Increase padding below search field](https://projects.invisionapp.com/share/K910BUZPDBSU#/screens/445952614/comments/140923950)
- [x] [Search bar fixes](https://projects.invisionapp.com/share/K910BUZPDBSU#/screens/445952614/comments/140924018)
- [x] [Title styling](https://projects.invisionapp.com/share/K910BUZPDBSU#/screens/445952614/comments/140925258)
- [x] [Reduce quote mark](https://projects.invisionapp.com/share/2T10BUZWDN9J#/screens/445952095/comments/140924050)
- [x] [Reduce quote text size](https://projects.invisionapp.com/share/2T10BUZWDN9J#/screens/445952095/comments/140924061)
- [x] [Reduce the quote attribution size](https://projects.invisionapp.com/share/2T10BUZWDN9J#/screens/445952095/comments/140924073)
- [x] [Reduce content text size](https://projects.invisionapp.com/share/2T10BUZWDN9J#/screens/445952095/comments/140924094)
- ~~[Fixed navigation header](https://projects.invisionapp.com/share/2T10BUZWDN9J#/screens/445952095/comments/140924132)~~
- [x] [Headline styles](https://projects.invisionapp.com/share/5410BUZXC9GN#/screens/445952096/comments/140924203)
- [x] [Ninja 1px line](https://projects.invisionapp.com/share/5410BUZXC9GN#/screens/445952096/comments/140924221)

**Comment by megganeturner** [comment]
I'm going to create a separate issue for the fixed top menu, as this will be a bigger chunk of work and will impact other pages

**Comment by pedro16v** [comment]
Hi @megganeturner.

While reviewing this issue, I wasn't able to validate some items. Mostly due to the fact that I tried to find the ultimate truth 😅 between `learn` and `learn2` and that became simply too confusing.

- [ ] [Boost tag size](https://projects.invisionapp.com/share/K910BUZPDBSU#/screens/445952614/comments/140923932)
- [ ] [Title styling](https://projects.invisionapp.com/share/K910BUZPDBSU#/screens/445952614/comments/140925258)
- [ ] [Headline styles](https://projects.invisionapp.com/share/5410BUZXC9GN#/screens/445952096/comments/140924203)

**Comment by megganeturner** [comment]
Hey @pedro16v!

learn2 is the ultimate source of truth (for this task, anyway!). There's a weird bug in learn2 at the moment where you need to click into a resource, then go back to the resources page before the tags & description will show up in the list 🤔  

Also number three (headline styles) has been reverted by another PR, but I'll reinstate those styles in my next one (:
