### ISSUE TITLE
Lesson Screen – Visual Refinements

### ISSUE THREAD

**Issue by andrewwapling** [catalpainternational/canoe#486]
Hi @Juliana-t @katevoss @megganeturner,

I've conducted a visual review of the latest release Lesson screen.

I have marked up some small visual refinements that I would recommend implementing from a FED perspective so that we align as closely as possible with the new design system.

Please see comments pinpointing issues on the Invision Prototype:

https://invis.io/BJ10BV03KSTP

Hope this helps and drop me a line with any queries at all.

Thanks again, Andy

---

### InVision summary

- [x] [Increase padding below short description](https://projects.invisionapp.com/share/BJ10BV03KSTP#/screens/445952098/comments/140924313)
- [x] [Add chevron icon to "see more"](https://projects.invisionapp.com/share/BJ10BV03KSTP#/screens/445952098/comments/140924321)
- [x] [Increase padding below "see more"](https://projects.invisionapp.com/share/BJ10BV03KSTP#/screens/445952098/comments/140924345)

**Comment by pedro16v** [comment]
Closed but sadly it'll be defactored 😅
