### ISSUE TITLE
(Frontend) See a list of Learning Activities for that category

### ISSUE THREAD

**Issue by katevoss** [catalpainternational/canoe#497]
This is the frontend companion issue for https://github.com/catalpainternational/canoe/issues/456

## Conditions of Satisfaction
* The Learning Activities are grouped by topics (in the sea, on the road, etc)
* Each Learning Activities has:
  * A reference
  * A title
  * A thumbnail
* I can make the activity offline
  * Activities are labeled as “available offline” if already downloaded
* Completed Learning Activities show a green tick button
* Ongoing lessons show a blue “continue” button

## Resources
* Engineering estimate: Day to Days
* Reference design: [Learning Activities - Listings](https://projects.invisionapp.com/share/6V102V1VURS9#/screens/443710124)

**Comment by PeteCoward** [comment]
@kate as in my slack msg, I think you should start [here](https://github.com/catalpainternational/canoe/issues/454) not, err... here
