### ISSUE TITLE
BUG: I can re-answer a question without dismissing the modal

### ISSUE THREAD

**Issue by katevoss** [catalpainternational/canoe#502]
There's another (what I assume to be) merge issue on `FT-Offlining` on Lesson tests. When I answer a question I see the popup modal but I can still interact with the question.

FT-Offlining:
<img src="https://user-images.githubusercontent.com/2395211/110127319-7fa33900-7d93-11eb-846b-7317b18c70be.png" width="300">

FT-New-Design-System:
<img src="https://user-images.githubusercontent.com/2395211/110127384-9184dc00-7d93-11eb-8cfc-3a38bf538aee.png" width="300">

**Comment by megganeturner** [comment]
Resolved in #514
