### ISSUE TITLE
Audit and fix frontend issues on FT-Offlining

### ISSUE THREAD

**Issue by katevoss** [catalpainternational/canoe#504]
- [x] Pull ResourceArticle out of LessonContent (and related cleanup) 
     - [x] make ResourceArticle a vertical scroll of cards
     - [x] Resource articles, not loading
     - [x] resource tags not loading
- [x] Profile page, loading courses (needs manifest)
- [x] ~Video and audio cards, not loading~ this was a server error, media was not being correctly transcoded, pull redesign db and media to retest
- [x] Tags list, not loading - addressed in #509
- [x] back arrow link broken (ex. from ResourceArticle back to Resources)
- [x] consistency (ex: use [`showTagList()` to determine if the page is loaded and tags exist in all instances](https://github.com/catalpainternational/canoe/blob/FT-Offlining/src/riot/WagtailPages/AllCoursesPage.riot.html#L17))
- [x] remove logic to [clear state between answer selections](https://github.com/catalpainternational/canoe/blob/3ea4846d622f5fac57575c36d88f779e82341bba/src/riot/Lesson/TestSingleAnswer.riot.html#L79) 
- [x] Make "you're not logged in" banner look better
    <img src="https://user-images.githubusercontent.com/2395211/110655630-3a18ae80-818d-11eb-97a7-6bd64aa33413.png" width=230>
- [x] Video and Audio cards throw error `Uncaught (in promise) TypeError: Cannot read property 'mediapath' of undefined`

**Comment by PeteCoward** [comment]
I'll take the Profile page stuff, and am looking for volunteers for the Resources issues.
The clear state between answer selections is low priority, but feel free!

**Comment by PeteCoward** [comment]
The video and media path stuff...

They should work in the lessons, but only when a transcode has succeeded, we may need to deal better with transcode failures
They may not work yet in resources, one for tomorrow
