### ISSUE TITLE
Canoe Image Size Guide

### ISSUE THREAD

**Issue by andrewwapling** [catalpainternational/canoe#518]
Hi @Juliana-t @katevoss @megganeturner @PeteCoward ,

Please see below breakdown of image sizes, ratios, requirements and recommendations for the new Canoe design system.

**1. Course Featured Image** – this should ideally be one image upload that is cropped and resized on the fly for the following scenarios:
	- Home Page Hero Banner: 320px x 452px portrait
	- Featured Course Card: 266px x 110px landscape
	- Standard Course Card: 128px x 96px landscape
	- Course Detail Hero Banner: 320px x 162px landscape
	
Designing for larger devices such as tablet and desktop is on the roadmap for design so I would recommend an image upload of 1280px x 648px landscape as majority of use cases are landscape bar the home page hero banner. This way we can safeguard against future releases.

**2. Lesson Featured Image** – this should ideally be one image upload that is cropped and resized on the fly for the following scenarios:
	- Standard Course Card: 128px x 96px landscape
	- Start Lesson Activity Card: 140px x 140px circular (please note: reuse lesson featured image for ease of use for a content management and creation perspective it makes sense to do so. We could also allow user override of this for example a user can upload a custom image or illustration if they would like to customise the experience. This approach would be great to implement across the board to boost flexibility for content creators whilst ensuring maximum efficiency for content creators.)

**3. Activity Card Start Structure**
	- Lesson Number (1>)
	- Lesson Name (52 characters)
	- Lesson Featured Image (140px x 140px circular)
	- Short Description mapped from existing lesson description for legacy deployments (225 characters)
	- Images: Currently we have accommodated for landscape 310px x 180px and square 310px x 310px in the activity cards. It’s important that these are full width to the card element itself and can be placed at top of card or at any interval within the card to create relevance in the content. I would recommend or 930px x 540px (landscape) or 930px x 930px (square) to cater for larger screen sizes into the future.
	
**4. Other Notes & Considerations**
	- Allow re-use of images for maximum content creation efficiency, whilst providing additional options to override with custom imagery or illustrations where appropriate
	- Ensure images are optimised to straddle balance between quality and file size. It's important images looks crisp and are also fast to load
	- Cropping and resizing of images should be automated on the fly as much as possible to reduce content creation overheads. Ability to add custom cropping or predefined cropping controls such as left, top, right, bottom, top left, bottom right etc. should be investigated to allow flexibility, control and ease of use for content creators

Hope this helps and let me know if you have any queries at all.

Thanks again, Andy

**Comment by Juliana-t** [comment]
@DanielHeads please have a look at this and use these recommendations when creating courses and lessons images for JID.
Let me know when you want to have a chat with me about it

**Comment by pedro16v** [comment]
This information would be better off in the Wiki or so. I'll tidy it up.

**Comment by andrewwapling** [comment]
Thanks @pedro16v , Let me know if you need any further design support on this one.

**Comment by pedro16v** [comment]
I just realised I moved this to the Design board. I'm not sure it needs to be there.

I did add this information [to the Wiki](https://github.com/catalpainternational/canoe/wiki/Canoe-knowledge-base#image-size-guide) for future reference. Please feel free to close this issue @andrewwapling if you feel there's no more work from design.
