### ISSUE TITLE
Pre-learning survey

### ISSUE THREAD

**Issue by Juliana-t** [catalpainternational/canoe#528]
## Overview
For certain courses to be distributed on Canoe's instance for JID, a pre-learning survey is needed. This will not be a rated learning assessment, but rather a pre-learning survey to help understand the learner's level of knowledge on a certain topic. Later, it can be compared with the results from the course exam (somehow measuring the impact of the training).

## MVP 
The idea is to re-use exams, allowing content providers to set them as a `Pre-learning survey` on Wagtail. By default, exams created on Wagtail should remain as they currently are. This will be an option that the content manager will need to explicitly set on a course's exam on Wagtail.

A course can only have a regular exam **OR** a pre-learning survey.

Also, in these pre-learning surveys, we need to be able to show learners more than 5 questions (for example, for JID pre-learning survey we have 15 questions) and to show the same exact questions to every learner that takes it.

There is a [prototype of the flow here](https://docs.google.com/presentation/d/1_KivsJGXnXQecTogf527W2LbeD3VqK9skew09zNWAas/edit?usp=sharing)

## Conditions of satisfaction
- [x] On Wagtail (course exam tab) content managers can define an exam as a 'Pre-learning survey'
- For learners, on the app, if the exam is defined as a 'Pre-learning survey' then:
  - On the 'Good job' screen (slide 5 of the prototype), the text is:
    - [x] Title remains the same -> "Good job!
    - [x] First line remains the same "You just completed the lesson [lesson name here]."
    - [x] Second line changes to "Take the pre-learning survey to complete the course [name of the course]"
    - [x] 1st btn text changes to -> "Take survey"
    - [x] 2nd btn text remains the same, "Back to Course"
  - [x] Code of conduct screen won't be shown
  - Once the exam is completed, the screen (slide 7 of the prototype) some changes on the text are required:
    - [x] Heading remains the same -> "Amazing work!"
    - [x] Sub-heading remains the same -> "You've completed the course"
    - [x] Text changes to -> "You have completed the pre-learning survey and you can now keep progressing your learning."
    - [x] Buttons text remains the same, no change 
- On the pre-learning survey questions:
  - [x] All learners are shown the exact same questions (not 5 randomly sorted questions nor a sample of questions from a wider number of questions)
  - [ ] Answers are collected on our database (per user) so later we can provide disaggregated reports for M&E and allow content developers to compare results from the pre-learning survey with results from the post-course exam

## Outstanding questions
Ask Juliana asap!

**Comment by PeteCoward** [comment]
@Juliana-t there was talk of removing the 5 question limit for exams too. Is that definite? if so let's do it here
the only difference might be random order for exams, set order for pre-learning surveys

**Comment by Juliana-t** [comment]
@PeteCoward yes, that is described on the slides and on this issue. At least for the JID deployment we want to be able to add and display to the learner more than 5 questions (for example, the pre-learning survey has 15 questions). If we make the order of questions random, won't that make harder to do the analysis of the results?
Also, to clarify, pre-learning questions also have a right answer – this is needed for the post analysis of % of learners that got each answer correct – we are just not telling learners know at the end of the pre-learning survey, the % of answers they got right

**Comment by PeteCoward** [comment]
> @PeteCoward yes, that is described on the slides and on this issue. At least for the JID deployment we want to be able to add and display to the learner more than 5 questions (for example, the pre-learning survey has 15 questions). If we make the order of questions random, won't that make harder to do the analysis of the results?
> Also, to clarify, pre-learning questions also have a right answer – this is needed for the post analysis of % of learners that got each answer correct – we are just not telling learners know at the end of the pre-learning survey, the % of answers they got right

no changes to the existence of a right answer!

I should have been clearer, I am asking about behaviour of the existing and future exams ( not pre-learning surveys )
1. Do you want random question order in existing non-prelearning exams?
2. Do you want unlimited questions ( remove the random choice of 5 ) in existing non-prelearning exams

**Comment by Juliana-t** [comment]
@PeteCoward 
From what we know so far, for JID we:
1. don't want random question order in pre-learning nor exams
2. want unlimited questions in pre-learning and exams

**Comment by pedro16v** [comment]
To be continued on #576
