### ISSUE TITLE
Bug: Pre-learning survey showing answers already selected (without user's action)

### ISSUE THREAD

**Issue by Juliana-t** [catalpainternational/canoe#563]
On JID's instance:
Answers for questions 17 onwards are showing pre-selected.
After selecting an answer on question 16, the following one appeared with the same answer pre-selected.

**Comment by pedro16v** [comment]
While reviewing this, I realised if I go back one question, my choice is gone!

![Screen Recording 2021-04-15 at 18 18 08 mov](https://user-images.githubusercontent.com/2813677/114845961-2eb54480-9e17-11eb-812d-b87234d8f261.gif)

**Comment by megganeturner** [comment]
@pedro16v there's a FE fix in pull #587, but Peter is looking at simplifying this further - it should be resolved soon! 😃
