### ISSUE TITLE
Bug: applying a filter not showing results

### ISSUE THREAD

**Issue by Juliana-t** [catalpainternational/canoe#564]
JID instance:
applying a filter with a course associated to 2 courses is not showing any result

**Comment by Juliana-t** [comment]
Sure!
On this instance of Canoe we have 2 courses with the "emergency department" tag, but neither shows when filtering by that tag:

![Screen Shot 2021-04-01 at 8 44 23 AM](https://user-images.githubusercontent.com/52807808/113224516-97081000-92c6-11eb-92f8-5d22a31a6615.png)

**Comment by PeteCoward** [comment]
Cannot reproduce this on https://canoe-csp.catalpa.build/

**Comment by pedro16v** [comment]
I still get it in both https://jid-staging.temp.build and https://canoe-csp.catalpa.build/

![Screen Recording 2021-04-15 at 17 48 25 mov](https://user-images.githubusercontent.com/2813677/114841984-615d3e00-9e13-11eb-863c-29fc779008d8.gif)

On Wagtail, the tag seems to be correctly set.

![Screenshot 2021-04-15 at 17 50 16](https://user-images.githubusercontent.com/2813677/114841902-4d194100-9e13-11eb-8fdd-b72d0ebb8382.png)

**Comment by PeteCoward** [comment]
reviewable on https://jid-staging.temp.build, and https://learn.canoe-redesign.temp.build
