### ISSUE TITLE
Fix: Images are displayed with low resolution

### ISSUE THREAD

**Issue by Juliana-t** [catalpainternational/canoe#565]
JID instance
- uploaded images (course, lesson, cards) are too compressed and showing on the app with too low resolution

**Comment by PeteCoward** [comment]
@Juliana-t please give examples

**Comment by Juliana-t** [comment]
examples here @PeteCoward 
![Screen Shot 2021-03-30 at 12 18 10 PM](https://user-images.githubusercontent.com/52807808/113078035-526c6e00-920d-11eb-9ce6-4849616cc722.png)
![Screen Shot 2021-03-30 at 12 18 22 PM](https://user-images.githubusercontent.com/52807808/113078048-57312200-920d-11eb-9a30-9c963de1775a.png)

**Comment by boerwastaken** [comment]
It looks like these are vector graphics - wouldn't using the original vector image (if not svg, converted to svg) be the standard way to go about it? You can then blow the image infinitely while keeping infinite resolution.

Alternatively, AVIF (principally a bitmap format) performs surprisingly well on vector images, [see this page, scroll down to "Illustration with gradients"](https://jakearchibald.com/2020/avif-has-landed/). What's more, it's so much better than any other format on bitmap images.
AVIF is behind a flag on Firefox (which I can enable on Appelflap), and is fully supported on Chrome.

I think the following would be best:
- probe for AVIF (render a one-pixel AVIF onto a Canvas, catch errors & verify the color value of the pixel, if all good -> the browser supports avif)
- use AVIF for everything, fall back to JPEG. Increase quality factor on JPEGs to please iPhone-carrying donors who will have  bandwidth to blow anyway.
