### ISSUE TITLE
Bug: Exam and course marked as completed after failing the exam

### ISSUE THREAD

**Issue by Juliana-t** [catalpainternational/canoe#567]
JID instance, course '2. Introduction to...'
after failing the exam, the course and exam show as completed, neither should be completed as I failed the exam

**Comment by pedro16v** [comment]
The course is still marked as complete although the exam is not (I got 0%)

![Screenshot 2021-04-15 at 18 00 01](https://user-images.githubusercontent.com/2813677/114843176-8605e580-9e14-11eb-81de-1c1bd527ed21.png)

![Screenshot 2021-04-15 at 18 01 33](https://user-images.githubusercontent.com/2813677/114843312-a6ce3b00-9e14-11eb-9921-97fc227c15d5.png)
