### ISSUE TITLE
Choice button needs padding

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#575]
![Screenshot 2021-03-31 at 14 29 19](https://user-images.githubusercontent.com/2813677/113094994-a8510e00-922d-11eb-92db-ee715c60ed8f.png)

## Overview

Long text is not ideal but possible. When our answers are very long, the button doesn't adapt very elegantly. Let's try add some padding as suggested [in InVision](https://projects.invisionapp.com/share/EN10MHNVGYCU#/screens?browse). 

Also mind the there's a reserved space on the right-most side of the button for a green tick / red cross that reinforces success/error feedback.

- [ ] Add enough padding so that the button adapts to longer text
- [ ] Add success/error icons — this one can be a stretch goal

## Resources

Current | Suggestion
---|---
![Screenshot 2021-03-31 at 14 21 32](https://user-images.githubusercontent.com/2813677/113095051-c3238280-922d-11eb-8d1f-1d1195f8248a.png) | ![Screenshot 2021-03-31 at 14 24 35](https://user-images.githubusercontent.com/2813677/113095012-ad15c200-922d-11eb-9e21-c14e153b2a90.png)

**Comment by davidcatalpa** [comment]
The line height on the response text is also too large. @andrewwapling  We may need to reduce the question text size a bit as well.

**Comment by andrewwapling** [comment]
Hi @pedro16v @davidcatalpa, Thanks for flagging this one with me. I would recommend the following:

• As David mentioned I would reduce the question text size a couple of point sizes to more closely match the design, currently it appears a bit larger and weightier (please see screenshot attached)
• Reduce line-height and refer to text sizes in design to match more closely and reduce vertical height of page as a whole (please see screenshot attached)
• Add A, B, C … signifiers to lefthand side of selector (please see screenshot attached)
• Let's double check selected, correct and incorrect states to ensure they match design as closely as possible i.e. background tint, signifier colour, stroke colour, font colour and weight and background tint (please see screenshot attached)

Please let me know if there's any queries on this or any clarification required at all.

Thanks again, Andy

![Activity - Multi Choice@2x](https://user-images.githubusercontent.com/13824612/113101203-2c17f400-9248-11eb-93d2-b2a2a55303d9.png)
![Activity - Multi Choice - Incorrect@2x](https://user-images.githubusercontent.com/13824612/113101215-2f12e480-9248-11eb-85b6-e03357a969ba.png)
![Activity - Multi Choice - Correct@2x](https://user-images.githubusercontent.com/13824612/113101221-30441180-9248-11eb-9d52-a05414dc5626.png)

**Comment by andrewwapling** [comment]
No problem @pedro16v – thanks so much for your support with this :)
