### ISSUE TITLE
Reaching the end of lessons doesn't promp me to take the pre-survey

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#576]
**Splitting from #528** 

On a 1-lesson course ([this one](https://jid-staging.temp.build/#/site/learn/welcome)), the "Congratulations" screen at the end was showing only 1 option "Next Lesson >"

Given that the first lesson was also the last one, the following pattern is expected (described in #528):
- [x] Title remains the same -> "Good job!
- [x] First line remains the same "You just completed the lesson [lesson name here]."
- [x] Second line changes to "Take the pre-learning survey to complete the course [name of the course]"
- [x] 1st btn text changes to -> "Take survey"
- [x] 2nd btn text remains the same, "Back to Course"

**This is what I got at the end of lesson 1:**
![Screenshot 2021-03-31 at 15 42 17](https://user-images.githubusercontent.com/2813677/113102872-8a89a600-9239-11eb-94d4-2116433d0911.png)

**Comment by katevoss** [comment]
I think this is related to a larger issue of caching content, which I'll track in a separate issue: https://github.com/catalpainternational/canoe/issues/584

When content is hitting the cache as it should, then I do see the correct UX  and I'm not able to reproduce this bug: 
<img src="https://user-images.githubusercontent.com/2395211/113329298-61c1e900-92eb-11eb-87de-931a7b3ad45d.png" width="200">

**Comment by pedro16v** [comment]
Thanks. I'll review this later on along with #584 then.
