### ISSUE TITLE
Course detail page — Call To Action

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#577]
The course detail page features a Call-to-Action (CTA) button immediately below the short description. 

This page should show:
- [x] the category (`social media` on the example below)
- [x] the title
- [x] the full short description
- [x] the CTA button
- [x] show at least 3 lines of the full description. The remaining text can be seen after clicking `see more`.

The button should show:
- [x] `Start learning` if the user has never visited any of the lessons
- [x] `Continue learning` if the user has already started or completed a lesson.

---

[Check InVision](https://projects.invisionapp.com/d/main?origin=v7#/console/20251865/445497256/preview?scrollOffset=994) for more details.

![Screenshot 2021-03-31 at 16 44 32](https://user-images.githubusercontent.com/2813677/113108874-6bdadd80-9240-11eb-9f68-9d22f451113d.png)

**Comment by andrewwapling** [comment]
Hi @pedro16v, Kindly let me know if there's any design queries or if you'd like any design support on this one. Thanks again, Andy

**Comment by megganeturner** [comment]
Hey @pedro16v & @andrewwapling just wanted to check about the button copy/behaviour for the following scenarios:
1. if the user has completed all the lessons, but not the exam (presumably something like `take exam/pre-learning survey`)
2. if the user has completed the lessons and exam
    - should the button still be there? I don't think we can 'reset' course progress, so something like 'start again' might not make much sense - where would it start from?
    - possibly could have some `you've already completed this course` copy with a green tick or something

I'll get started on the other stuff now!

**Comment by andrewwapling** [comment]
Hi @megganeturner thanks for the queries here.

1. For simplicity sake and directness I feel that we could retain the 'Continue' wording on the button to entice users to fully complete the course

2. If we don't have ability for users to retake a course I propose the following solution 'Course Completed' with check icon and green success button colour. This creates affordance to the user that they have indeed completed the course. Kindly see design direction below: https://invis.io/52Y02L9YTRF#/451504741_Course_Detail_-_Completed

Look forward to hearing your thoughts :)
