### ISSUE TITLE
"Invalid login credentials" should clear when re-attempting

### ISSUE THREAD

**Issue by boerwastaken** [catalpainternational/canoe#58]
Currently on the login page,  when "Invalid login credentials" is shown (because you may have mistyped your password), it keeps on showing when you've POSTed anew (with corrected credentials). As this can take a while, of may never finish at all, if your network is bad or has gone away, it becomes confusing - is the new attempt underway? is it still wrong? should I try another password now?
And it stays this way while the real error condition might be "network broken" or "server down".

Suggestion: clear this text as soon as a new attempt is underway.

**Comment by PeteCoward** [comment]
@katevoss fancy having a go at this?

**Comment by katevoss** [comment]
Sure thing, shouldn't be too tricky.

**Comment by pedro16v** [comment]
Sure, makes it simpler :)
