### ISSUE TITLE
Some data doesn't load when I first login

### ISSUE THREAD

**Issue by katevoss** [catalpainternational/canoe#584]
### Steps:
1. Open an incognito window
2.  go to Localhost where you're running canoe
3. login
4. look at the All Courses list
**Result**: None of the courses are complete
<img src="https://user-images.githubusercontent.com/2395211/113329509-a9e10b80-92eb-11eb-9c1e-e46b7aba6aed.png" width="200">
5. refresh the page
6. look at All Courses list

**Result**: The correct courses are marked complete
<img src="https://user-images.githubusercontent.com/2395211/113329616-c7ae7080-92eb-11eb-99b5-6be8a9734730.png" width="200">

For those of who you prefer a screen recording of the action:
https://user-images.githubusercontent.com/2395211/113330353-9da97e00-92ec-11eb-81e5-a157222d3300.mov

Rewinding to step 4 (before refreshing the page):
5. I go into a course
**Result**: the lessons are not complete
6. I complete a lesson
**Result**: the one lesson is marked complete
7. I refresh
**Result**: all lessons are now magically complete!

I suspect that certain types of content are not loading the first time you visit a page. I also suspect this is responsible for not showing the pre-learning button (https://github.com/catalpainternational/canoe/issues/576), and not filtering courses (https://github.com/catalpainternational/canoe/issues/564).

**Comment by pedro16v** [comment]
This still sort of happens on a fresh run. I believe it has to do with slow network and the loading of those statuses. We'll keep an eye on it.
