### ISSUE TITLE
Bug: video not playing

### ISSUE THREAD

**Issue by Juliana-t** [catalpainternational/canoe#590]
On https://canoe-csp.catalpa.build/
a tester reported that couldn't play Doctor Garry Nou video - course 2 / lesson 3 / card 11

Devices used by the tester:
I use MacBook Air Big Sur Version 11.2.3 and iPhone 8Plus.
I use Safari & Google Chrome.

**Comment by PeteCoward** [comment]
It's not clear if the video failed on all the devices used and how it failed.
Will try later to reproduce
