### ISSUE TITLE
Fix: on cards, need to scroll down to see the navigation buttons (on the lesson cards)

### ISSUE THREAD

**Issue by Juliana-t** [catalpainternational/canoe#592]
Feedback from a tester:
On phone it requires scrolling down to click next even when only small amount of text on the screen

Tester was accessing through:
IPhone 11 Pro running iOS 14.4.2 and Safari
and
IPhone 12 and Safari

**Comment by pedro16v** [comment]
@megganeturner I still think height is a bit off (now is too short on an actual device). But if I "install" the app on the phone, it fits nicely.

**Comment by pedro16v** [comment]
The original bug is fixed but I still experience short cards on device. I'll wait for newer updates and open an issue if I see it again.
