### ISSUE TITLE
Bug: next card showing image from previous card

### ISSUE THREAD

**Issue by Juliana-t** [catalpainternational/canoe#593]
Even on a fast connection, the testers are reporting (several times) that when navigating from one card to the next one, frequently the image shown is the one from the previous card.
If the image is not loaded yet, we should show a placeholder or a loader, while it is being loaded, instead of the previously displayed image

![Screen Shot 2021-04-12 at 5 16 28 PM](https://user-images.githubusercontent.com/52807808/114362925-d2ea8180-9bb2-11eb-8201-8dca8f157a83.png)

**Comment by pedro16v** [comment]
Still noticeable in `https://jid-staging.temp.build/` and `https://canoe-csp.catalpa.build/`


https://user-images.githubusercontent.com/2813677/117419473-97479b00-af57-11eb-97fb-0bcb153a1cd4.mov

**Comment by pedro16v** [comment]
I can still see it @PeteCoward . Is this on JID staging and/or prod?

**Comment by pedro16v** [comment]
Much better now!
