### ISSUE TITLE
Design: modal for the quiz questions feedback

### ISSUE THREAD

**Issue by Juliana-t** [catalpainternational/canoe#595]
We are using it to provide opportunities for positive reinforcement and to review key lesson concepts
Using it for the JID program, we realized that we need more space to show the feedback than what we currently have (see example, where feedback text was cut due to the size) 
- [x] Can this modal window grow when needed? 
- [x] Can we have an example, and provide some max height to the engineers? 
- [x] Also, what happens when showing in a smaller screen, where the text can't all be shown? allow scroll inside the modal?

Engineering
- [ ] Allow for longer feedback, up to 230 characters, on Wagtail
- [ ] On the FE/app, allow the modal window to grow in height when longer feedback is defined as per the design (links on the issue comments)

**Comment by andrewwapling** [comment]
Hi @Juliana-t,

Yes I would see this roll up modal gate growing in height if required to accomodate additional content. Please see design recommendations below:

1. Roll Up Modal Gate (standard content): https://invis.io/BZ10396LPHF9
2. Roll Up Modal Gate (longer content): https://invis.io/C710QDT2DGU8
3. Roll Up Modal Gate (much longer content / scrollable pane): https://invis.io/CD10QDT9YSHU

Hope this helps and let me know if there's any further queries.

Thanks again, Andy

**Comment by Juliana-t** [comment]
@PeteCoward this is the design issue on enabling longer feedback on quiz questions.
As you will see on Andrew examples, he added that but also the possibility to add rich text (paragraph breaks, bold, italic, lists), which could be handy. I want to check with you if converting the current title + single line feedback into a title + text editor would be feasible and the effort required.
Depending on the effort, we could decide on keeping the title + single line text but showing longer feedback for now, and implementing the text editor in a later stage

**Comment by pedro16v** [comment]
This issue is confusing. I could indeed test that we allow for longer Feedback Text on Multiple Choice (way more than 230 chars) but no formatting.

What should I be looking at @Juliana-t @PeteCoward ?

**Comment by andrewwapling** [comment]
Hi @pedro16v @Juliana-t @PeteCoward , Do you require any design support on this one? Would you like me to remove formatting and simply provide unformatted text styles for this? Thanks, Andy

**Comment by Juliana-t** [comment]
Thanks Andy, if you can remove the formatting it would be great. @megganeturner do you need any additional information on the design?

**Comment by pedro16v** [comment]
Just tested this on`https://jid-staging.temp.build/` by adding custom feedback to a `Multiple Choice` card.

The current behaviour needs tuning, according to what has been discussed above.

* The field `Feedback text` is accepting 1000 characters (above I can see a [requirement](https://github.com/catalpainternational/canoe/issues/595#issue-856494005) for 230).
* When using the whole 1000 characters, the modal header is hidden and I have no way of scrolling
* Entering text with exactly 230 characters doesn't seem to match the "longer content" scenario that Andy accounted for (example on the [comment](https://github.com/catalpainternational/canoe/issues/595#issuecomment-819127764) above)

**Entering text on Wagtail**
![Screenshot 2021-05-07 at 14 58 25](https://user-images.githubusercontent.com/2813677/117404661-4c248c80-af45-11eb-8855-8d73f55453b6.png)


1000 characters | 230 characters
--- | ---
![Screen Recording 2021-05-07 at 14 51 21 2 mov](https://user-images.githubusercontent.com/2813677/117404829-9443af00-af45-11eb-9937-f941d80589c0.gif) | ![Screenshot 2021-05-07 at 14 55 45](https://user-images.githubusercontent.com/2813677/117404846-9dcd1700-af45-11eb-8328-3d87941450cb.png)

**Comment by andrewwapling** [comment]
Hi @pedro16v @Juliana-t @megganeturner just confirming that I've updated the design in the core DSM prototype to reflect no formatting and pure body text capability for this modal roll up alert. Please see prototype link below: https://invis.io/TG10XXEQSFK8

Also just confirming that the height of the pane is variable based on the amount of copy. The max height is viewable in this screen: https://invis.io/52Y02L9YTRF#/449619332_Activity_-_Modal_Gate_-_Correct_-_Long

For very long content it should be scrollable within the card as per: https://invis.io/52Y02L9YTRF

Hope this helps and kindly drop me a line with any queries at all.

**Comment by andrewwapling** [comment]
Hi @pedro16v looks as though the Invision link had changed. I've updated the very long scroll content version in the comment above :)
