### ISSUE TITLE
Design: thumbnail for video

### ISSUE THREAD

**Issue by Juliana-t** [catalpainternational/canoe#596]
We allow content admins to add a thumbnail to the video element on Wagtail, but content managers tend to not upload one. 
![Screen Shot 2021-04-13 at 10 56 06 AM](https://user-images.githubusercontent.com/52807808/114485436-da5b6a80-9c46-11eb-940c-9ff4080e166d.png)
 
As we are not automatically generating a thumbnail from the video content, we were thinking on having a generic but themed "video is loading" or just a generic video thumbnail placeholder of our design, then switch it out for the first frame as soon the element is loaded.

**Comment by andrewwapling** [comment]
Hi @Juliana-t , Please see below design direction for the Canoe core illustration fallback to solve this issue:

https://invis.io/52Y02L9YTRF#/449627509_Activity_-_Content_-_Video_Fallback

The idea being that if no custom thumbnail image is uploaded in the CMS then the above image would show.

Kindly review and let me know your feedback.

Thanks again, Andy

**Comment by boerwastaken** [comment]
> As we are not automatically generating a thumbnail from the video content

We are though! See catalpainternational/canoe-backend#146

It'd still be good to have a fallback placeholder image though, just in case.

**Comment by andrewwapling** [comment]
@boerwastaken @pedro16v let me know if you require any additional design support on this issue.

**Comment by pedro16v** [comment]
I'm closing this one for now are we should have automatically generated thumbnails for all videos. If that ends up not being true, I or someone else will report a bug.
