### ISSUE TITLE
Newly added courses and lessons have a “new” badge icon

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#608]
## Overview
We want users to quickly know when new content is available and to be able to tell it apart from older content.

### First time a user opens the app:
* No courses or lessons or Learning activity topic or Learning activity are labeled as new

#### When is a **COURSE** labeled as new?
  * If a **new course** was originally published after the user’s first visit to the app, then:
    * For the next 7 days **OR** until the user completes at least one lesson in that course.
  * If a **new lesson** is published (not updated) in an **existing course**

#### When is a **LESSON** labeled as new?
  * Only if a **new lesson** is added to a course that exists for more than **3 days**, then:
    * For the next 7 days **OR** until the user completes the lesson

#### When is a **LEARNING TOPIC** labeled as new?
  * If a **new learning topic** was originally published after the user’s first visit to the app, then:
    * For the next 7 days **OR** until the user completes at least one learning activity in that topic
  * If a **new learning activity** (inside the topic) is published (not updated) in an existing learning topic

#### When is a **LEARNING ACTIVITY** (the units inside the Learning topics) labeled as new?
  * Only if a **new learning activity** is added to a learning topic that exists for more than **3 days**, then:
    * For the next 7 days **OR** until the user completes the learning activity

## Resources
- Reference design: [InVision](https://invis.io/PBZPZ9VCYSX)

**Comment by pedro16v** [comment]
Hi @megganeturner @PeteCoward , please review the new rules on the original post above.

**Comment by PeteCoward** [comment]
Hmm, "first time a user opens the app" and "times a user opens the app" is not simple to track. 
Moving back to todo to track the priority of this.

Need to think about how to implement this

**Comment by pedro16v** [comment]
This is lower priority than Sync, Casting, and Formative Assessment. We can hide the badges until we know more.

**Comment by PeteCoward** [comment]
@andrewwapling  my question is...
should

#### When is a **COURSE** labeled as new?
  * If a **new course** was originally published after the user’s first visit to the app, then:
    * For the next 7 days **OR** until the user completes at least one lesson in that course.
  * If a **new lesson** is published (not updated) in an **existing course**

be 

#### When is a **COURSE** labeled as new?
  * If a **new course** was originally published after the user’s first visit to the app, then:
     * For the next 7 days **OR** until the user completes at least one lesson in that course.
  * If a **new lesson** is published (not updated) in an **existing course**
    * For the next 7 days **OR** until the user completes at least one lesson in that course.


and similarly for the teaching activities

**Comment by andrewwapling** [comment]
@PeteCoward I believe the second scenario is correct i.e the same logic should apply to the duration of the new flag being displayed for courses in both scenarios.

**Comment by PeteCoward** [comment]
For sanity I am very tempted to request a change

1. **newPublishDate** is a page's latest published date(including descendants).
2. Any page is **new** if **newPublishDate** is in the last 7 days
3. Any page is **newToUser** if **new** and **newPublishDate** is after user's first login
4. We show badges on a page card if **newToUser** and the user has not completed the page or any of its descendants since **newPublishDate**

**Comment by pedro16v** [comment]
> Basically we show new badges if content was created after the user joined and in the last 7 days, and hide them once something is completed

Sounds correct, yes.

**Comment by joanico** [comment]
This is a new badge on PeP, I have been testing this for 7 days, I can see the new badge for the first time I login and also for the new user.

<img width="314" alt="Screen Shot 2022-01-24 at 2 55 29 PM" src="https://user-images.githubusercontent.com/12932898/150729869-b8c9f02a-99f7-4733-a06c-ca2ed23ac0c4.png">  <img width="307" alt="Screen Shot 2022-01-24 at 2 55 50 PM" src="https://user-images.githubusercontent.com/12932898/150729909-3e5b325c-7e02-4593-93f4-cce9e08289be.png">
