### ISSUE TITLE
On a discussion, I can add comments

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#612]
## Conditions of Satisfaction
- [x] There is a text box where I can enter a new comment
- [x] I can reply to an existing comment
- [x] I can't reply to a reply
- [ ] A comment (or reply) has a max of 350 chars

**Comment by Juliana-t** [comment]
@megganeturner I updated the limit of chars in comments and replies.
Please let me know if you have any further questions

**Comment by pedro16v** [comment]
Current comment max size is 280chars.
