### ISSUE TITLE
I am informed if other user replies to my comment

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#614]
## Conditions of Satisfaction
- [x] A toast message appears, showing:
  - [x] The name of the user who replied
  - [x] The corresponding discussion topic title
  - [x] In the format: "[user first name] just replied to your comment in [discussion topic title]"
- [x] Toast messages will disappear after 6 seconds
- [x] Toast messages can be dismissed
- [x] Tapping the toast message, takes me to the reply on the discussion board

## Resources
* Check the [InVision prototype](https://projects.invisionapp.com/d/main?origin=v7#/console/20251865/449205663/preview?scrollOffset=2127)

<img width="321" alt="Screenshot 2021-07-30 at 13 36 45" src="https://user-images.githubusercontent.com/2813677/127653926-1a117d62-1797-4463-8321-4a1a2d4f8633.png">

**Comment by pedro16v** [comment]
The initial aim was to simply show toast messages should anyone reply while a user is navigating the app. Ping Peter before starting this for clarity regarding notifications in general.

**Comment by Juliana-t** [comment]
I just reviewed this issue and found that we need to review the UI implementation. While the [toast messages displayed when, for example, I posted a comment with success ](https://projects.invisionapp.com/d/main#/console/20251865/449205656/preview)is showing in the correct position and styling, other notifications that are shown using the toast messages are not implemented according to the design. 
These are:
1 - When an user replies to a commented I posted
2 - When I receive a 'CMS' notification

Also one more issue, is the message we are showing on the toast notification. For some reason it seems to be showing some other message (a previous one), while the in-app and notification center are showing the correct one (someone replied to something).

@ellijayne can you please review the UI to meet this design - https://projects.invisionapp.com/d/main#/console/20251865/449205663/preview ?
And while you are in there, please have a look at the original conditions of satisfaction in this user story. As they are not displaying correctly in the FE, I can't confirm if they are implemented accordingly to the specs.
(FYI @joanico @andrewwapling I am moving this to the to do as it requires some review)

**Comment by ellijayne** [comment]
I have fixed all this :) except for users name - as it's not being returned from the backend. Lee said he was attending to this so once its added i can do that :) but otherwise my [PR ](https://github.com/catalpainternational/bero/pull/663) fixes all the other stuff

**Comment by md8n** [comment]
The user's name is already in the changed push notification title and body text.

**Comment by Juliana-t** [comment]
Reviewed and all working well now! Thanks :)
I am closing this issue
