### ISSUE TITLE
After completing an exam, I can review my answers

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#618]
![Screenshot 2021-04-15 at 15 07 46](https://user-images.githubusercontent.com/2813677/115186680-19912c00-a11d-11eb-81e7-c7f8c67a257c.png)

## Overview
After completing the exam, users that get at least one wrong answer have the option to review those answers. Users are first shown a summary screen detailing which questions they failed. They can then proceed to review each individual wrong answer. While navigating through these question cards, extended information (added by the content manager - each answer option has an associated feedback) is displayed. Once users are done with the review, they can either retake the full exam or go back to the course page.

## Conditions of Satisfaction
- [x] I can see a summary screen, listing my incorrect choices
  - [x] I have the option to start reviewing
- [x] I can navigate through the wrong answers
  - [x] Each one of these is similar to the equivalent question card
  - [x] There is extended information contextualising the question
  - [x] Only my choices are highlighted
    - [x] In cases where I can pick multiple answers, my correct answers show in green and wrong answers in red.

- [x] After reviewing all answers, I can
  - [x] Retake the exam
  - [x] Go back to the course page

## Resources

two choices, two wrong | two choices, one wrong | single choice, wrong
---|---|---
<img width="322" alt="Screenshot 2021-04-29 at 15 28 26" src="https://user-images.githubusercontent.com/2813677/116510268-9ed7c600-a8ff-11eb-976a-632edbbee4fd.png"> | <img width="320" alt="Screenshot 2021-04-29 at 15 27 42" src="https://user-images.githubusercontent.com/2813677/116510290-a6976a80-a8ff-11eb-94c8-435387c76953.png"> | <img width="322" alt="Screenshot 2021-04-29 at 15 28 17" src="https://user-images.githubusercontent.com/2813677/116510282-a39c7a00-a8ff-11eb-9f8a-6982420ab39e.png">

**Comment by andrewwapling** [comment]
Hi @pedro16v thanks for getting this through to me. Just confirming I have created a high-fidelity prototype flow here for review:

https://invis.io/FV10TRZQC7SM

Kindly review and let me know your feedback.

Thanks again, Andy
