### ISSUE TITLE
As a content manager, I can add text feedback to each question on the exam

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#620]
## Overview
This feedback will be shown to users after they finish the exam and if they select to review. Each question will have dedicated feedback for incorrect responses that further contextualizes the learner by providing extended information.

## Conditions of Satisfaction
- [x] Content managers can set feedback text for each exam question for incorrect responses
- [ ] The overall character limit is 500 characters
- [x] Allowed formatting includes:
  - [x] Line breaks
  - [x] Bold and italic
  - [x] Lists

## Resources

* Note that some types of questions can have customized feedback text. This issue is not about that feedback.
* The table below is an attempt to make it clearer to whoever gets to implement this:

Type | Question type | Possible answers  | Check answer | Feedback per answer | Feedback per question
--- | --- | --- | --- | --- | ---
Exam | Multiple Choice | 1 | no | no | yes
Exam | Checkboxes | all | no | no | yes
Quiz | Multiple Choice | 1 | yes | yes | no
Quiz | Checkboxes | all | yes | no | no

**Comment by megganeturner** [comment]
Hey @pedro16v - just wanted to check two things:
1. Should the revision note be a required field in Wagtail for each question?
2. What should the helper text be in Wagtail to explain the field?

**Comment by megganeturner** [comment]
For number 2 right now I've got:
`At the end of an exam, students are given the opportunity to review the questions they answered incorrectly. Revision notes are displayed alongside these questions to assist the user in reconsidering their answer, so they can get it right when they retake the exam.`

**Comment by pedro16v** [comment]
Hi @megganeturner 

1. No. We can have questions without having to specify revision notes.
2. Your suggestion seems fine. We can stick with it unless @Juliana-t says otherwise.

**Comment by Juliana-t** [comment]
All good! thanks Meggan!
Revision notes on exam questions are highly recommended but not mandatory.
