### ISSUE TITLE
When a user returns to Canoe, they see a home screen

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#621]
## Overview
In order to make Canoe a more dynamic app, we'll be adding a home screen which will present different actions according to the user's progress. The typical action will be to resume an ongoing course or activity. It can also display dynamic information such as recommended or featured content.

## Conditions of satisfaction
- [x] I see a home screen with several navigation options
- [x] There is a highlighted link prompting me to start a lesson
- [x] I see lists of different content:
  - [x] Ongoing courses (thee ones the user started but didn't complete)
  - [ ] Categories and/or Topics

## Resources
* Reference design: [InVision](https://invis.io/52Y02L9YTRF#/431201684_Home)

**Comment by pedro16v** [comment]
Hi @andrewwapling @Juliana-t, we've been chatting about what options are useful for a first iteration of the home page. Here's the outcome for you to analyse.

<img width="1272" alt="Screenshot 2021-06-11 at 11 59 14" src="https://user-images.githubusercontent.com/2813677/121676636-c1d3c900-caac-11eb-8a36-5d02294ccd57.png">

What? | When can I see it? | What does it list? | Which order? | Card links to | Arrow links to | Notes
-|-|-|-|-|-|-
Panel 1 | always | N/A |N/A|N/A |`Courses Home` OR `Course Categories Home` OR `Learning Activities Home`|Should have a default image. Link should be configurable.
Panel 2 |if `Learning Activities Home` exists|Learning Topics| Same as `Learning Activities Home`| Learning  Activities list (for that topic) | `Learning Activities Home`| 
Panel 3 | if `Courses Home` exists and there's only 1 course category |Courses|Same as `Courses Home`| Course detail page |`Courses Home`|Exception for implementations that have no categories (will only have the `Other` category)
Panel 4 | if `Course Categories Home` exists |Course categories|Same as `Course Categories Home`| Course category list (for that category) |`Course Categories Home`|
Panel 5 | if `Resources Home` exists |Resources|Latest first| Resource |`Resources Home`|

**Comment by PeteCoward** [comment]
OK @megganeturner , this translates to:

1. A new BeroHome page type in wagtail
  - has card_image ( inheriting from APIPReviewablePage gives us this )
  - has a ForeignKey field to a Page, with the choices limited to the children of the HomePage
2. Updating the code in Routing to point to that new home when the hash is empty
3. Implementing a new BeroHome page type and riot tag that reads from the manifest to implement the panels mentioned

**Comment by andrewwapling** [comment]
Hi @PeteCoward @megganeturner (fyi @pedro16v @Juliana-t @KaraChesal), Please see below link to the updated design direction for the home page based on the new configuration outlined above.

https://invis.io/52Y02L9YTRF#/454482332_Home_-_New_MVP

Kindly review and let me know your thoughts, queries and feedback. Please review and mark up comments on the prototype or respond with commentary and questions here.

Thanks again, Andy

**Comment by pedro16v** [comment]
Hello @megganeturner !

The screen seems to work as intended. No remarks there.

On the design side, I saw a few things that might need tweaking. I'll post them here, but I'll hand the ball to @andrewwapling 🤠 

---

On the following screens, we can see:
* Excessive top margin (logo to top)
* Excessive swoop curve 
* The illustration doesn't seem to fit for the same screen size

Live | InVision
---|---
<img width="320" alt="Screenshot 2021-07-08 at 14 03 21" src="https://user-images.githubusercontent.com/2813677/124926336-5e4fa380-e038-11eb-8409-933e47fc2593.png"> | <img width="320" alt="Screenshot 2021-07-08 at 13 45 35" src="https://user-images.githubusercontent.com/2813677/124925579-8b4f8680-e037-11eb-9508-5f9cdb093917.png">


On the next screens, we can see:
* Right arrows larger than InVision (but maybe that's a new global size)
* Section header titles are larger than InVision

Live | InVision
---|---
<img width="320" alt="Screenshot 2021-07-08 at 13 46 16" src="https://user-images.githubusercontent.com/2813677/124925566-88ed2c80-e037-11eb-94af-34df8a638824.png"> | <img width="320" alt="Screenshot 2021-07-08 at 13 46 09" src="https://user-images.githubusercontent.com/2813677/124925573-8a1e5980-e037-11eb-9f82-b568a60753bb.png">

**Comment by andrewwapling** [comment]
Hi @megganeturner great work! Looking really good :) @pedro16v thanks for these updates – I agree with all of the tweaks above :)

I'll mark up some minor feedback as well and post back here shortly.

Thanks again, Andy

**Comment by andrewwapling** [comment]
Hi @megganeturner @pedro16v I've marked up some additional design feedback in the following prototype:

https://invis.io/Q311CC2PAJCX

Hop this is helpful and let me know if you have any queries at all.

**Comment by pedro16v** [comment]
Checklist for the above:

- [ ] Top nav margin
- [ ] Low rez hero image
- [ ] JID branded illustration
- [ ] Swoop curve
- [ ] Section header titles are small and light. Kerning needs slight increase.
- [ ] Arrow too horizontally stretched and light

**Comment by pedro16v** [comment]
I took these screenshots hoping to show how the font size differs between device and desktop but I now realise it looks exactly the same 😆 

I added an InVision screenshot for easier comparison but although it looks different, it's not _that_ noticeble.

Lastly, I can see that InVision defines `12px` as the font size for those header titles but we're setting them to `0.9em` which translated to `14.4px` on my browser 🤷 

Lastly, the arrow **does** seem stretched.

Desktop | iPhone | InVision
--- | --- | ---
![Screenshot 2021-07-09 at 13 13 15](https://user-images.githubusercontent.com/2813677/125077390-037f8000-e0fc-11eb-9cf6-ff1e29a9a515.png) | ![IMG_1655](https://user-images.githubusercontent.com/2813677/125077405-08443400-e0fc-11eb-994b-c5e4f84ebf24.PNG) | ![Screenshot 2021-07-09 at 14 01 16](https://user-images.githubusercontent.com/2813677/125081672-3b3cf680-e101-11eb-8dcc-2879dac3622c.png)
