### ISSUE TITLE
On the course listing, courses are organized by category

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#622]
## Overview 
When creating courses, content managers can set their category. This should enable the course listing to be organized taking that information in consideration. 

## Conditions of Satisfaction
- Courses can be associated with a category
  - We can use the “tag” field as the category (already on Wagtail)
  - If a course is not associated with a category/tag, will be displayed on the app under “Other courses” category (for non-defined courses)
- Courses are grouped by category, on the course listing
  - For this release, ignore the circle avatars of categories on the top banner
  - Add one section per category with
    - Title
    - List of courses under that title
    - For now ignore the carousel navigation, courses will appear listed as they currently are on the course list
- Categories are alphabetically ordered on the all courses page

## Resources
* Reference design: [InVision](https://invis.io/MV10QV3Y9S2N)
* Possible solutions: [Google Slide](https://docs.google.com/presentation/d/1353MdkSb2xpF-NF10J59R-RkpC3-nNJH7MFUgs4MBlk/edit)

**Comment by pedro16v** [comment]
Added `possible solutions` document. Current decision is to follow "Option 2" from [that document](https://docs.google.com/presentation/d/1353MdkSb2xpF-NF10J59R-RkpC3-nNJH7MFUgs4MBlk/edit#).

**Comment by pedro16v** [comment]
@PeteCoward @megganeturner here's a few categories for you https://docs.google.com/spreadsheets/d/1HUfMfBq0SFN_7lZ1sKyTLaeqgppy4Y9TRAUEHLPnMD4/edit

**Comment by megganeturner** [comment]
Hey @pedro16v just to clarify what we need to do here:

Front end wise, we want to get rid of the tag filters at the top of the page
<img src="https://user-images.githubusercontent.com/12974326/126250805-c4a73d50-955c-4730-ac77-8adf85daed7b.png" width="250">

and instead display each course under its category
<img src="https://user-images.githubusercontent.com/12974326/126250938-d95274fd-7ef2-448a-8d13-15495a083eca.png" width="350">

In terms of carousel navigation this is easy enough to do if we want it in to start with. I've done this on the homepage. Let me know.

In terms of backend functionality
- if courses can only belong to one category, we can modify the `tag` field
- however the `tag` field is in use for resources too - do we want resources to fit under one category too? And should resources & courses have the same categories available, or different? 

When you say go with option 2 from that document ("Create Courses within an existing category") do you mean we should create a new parent page for courses? and in wagtail it should go `translatable root` > `categories` > `courses`? This is how I'm interpreting it but it doesn't sound right 😅

**Comment by pedro16v** [comment]
Let's see if I can provide a proper answer 😁 

### 1. Regarding filters.

I didn't mean to say to remove the tag filters. Simply to not add the category filters [as seen on InVision](https://projects.invisionapp.com/d/main?origin=v7#/console/20251865/433066584/preview?scrollOffset=1007).

<img width="321" alt="Screenshot 2021-07-20 at 12 45 09" src="https://user-images.githubusercontent.com/2813677/126318796-dafdc33f-3691-49ab-a67e-748e91592642.png">

### 2. Displaying each course under its category

Yes, that's it. Courses will be able to have 1 category and will be listed under that heading.

### 3. Carousel navigation

Yes, please 😃 

### 4. Tags vs Categories

Nevermind tags. You shouldn't need to touch them.

The proposed solution was that you wouldn't associate a category to a course. You would nest a course to a category page. That way, you get:
1. Translatable root — listing categories home + learning activities + resources
2. Categories home — listing categories
3. Category — listing courses

If done like this, content manager would have to first create a new Category and then add Courses to it. Or add new courses to an existing Category. In the exact same way you add Lessons to Courses. But please confirm this with @PeteCoward

**Comment by pedro16v** [comment]
Maybe this helps

<img width="848" alt="Screenshot 2021-07-20 at 13 18 30" src="https://user-images.githubusercontent.com/2813677/126322513-7cc32fdf-c05b-4493-9ff8-b66a2019aabc.png">

**Comment by megganeturner** [comment]
Thanks @pedro16v! This is all very helpful!

I'm not sure I see the value in having both the tag filters & the categories, but happy to be convinced otherwise - something to discuss in this afternoon's design-engineering sync 😄

**Comment by pedro16v** [comment]
Works as expected... however!... We need a better way to handle cases where there's no categories. The current solution adds too much entropy. I have sketches!

@andrewwapling @Juliana-t @PeteCoward 

## The current state

If no categories exist, we end up showing the same exact content in 3 different screens. The only difference is that when reaching the actual course listing, courses are not on an horizontal carousel. It only makes sense when it allows users to take a quick look at courses from different categories.

<img width="1032" alt="Screenshot 2021-07-30 at 14 19 34" src="https://user-images.githubusercontent.com/2813677/127659296-4ee52781-ba15-4b86-9fb6-5d6a0451c030.png">

## A suggested solution

If possible, in the case where no categories have been set, we could have the app jump directly to the course listing, saving users a confusing step.

<img width="1025" alt="Screenshot 2021-07-30 at 14 19 43" src="https://user-images.githubusercontent.com/2813677/127660038-c90263e6-14a0-49d9-afef-d035895fab96.png">


## Comparing the two 

What will people be looking at? Notice how content is always the same for `Situation A`

| - | Home Page (courses section) | Category listing | Course listing | 
| - | - | - | - | 
| Situation A | A preview of all available courses, sorted by date, completion, etc | A preview of all available courses, sorted by date, completion, etc | All available courses, sorted by date, completion, etc
| Situation B | A diverse number of courses, from all categories, sorted by date, completion, etc | A preview of the latest/ongoing courses from each category, sorted by date, completion, etc | All available courses, sorted by date, completion, etc |

**Comment by pedro16v** [comment]
You can now disregard my previous comment as I forked it into a new issue.

There's a situation that need attention though before I can close this. Empty categories shouldn't be listed.

| On the home page | On the Course listing | 
| - | - | 
<img width="375" alt="Screenshot 2021-08-03 at 14 23 03" src="https://user-images.githubusercontent.com/2813677/128023402-26124936-3468-430f-8495-263994684b3f.png"> | <img width="375" alt="Screenshot 2021-08-03 at 14 22 31" src="https://user-images.githubusercontent.com/2813677/128023406-40b97585-4f96-41d8-9df3-610ae4963748.png">

**Comment by andrewwapling** [comment]
Hi @pedro16v if a Bero deployment isn't utilising any categories I would recommend utilising the screen design below which basically lists all courses as cards. This version contains a continue learning component at the top of the listing which is there to help learners jump back into courses that they may have started though not yet completed. The search and tag filtering is persistent as per other course listing screens.

https://invis.io/8911I5TDCQ5S

Kindly review and let me know if you're happy with this approach?

**Comment by pedro16v** [comment]
Perfect. That seems to be the default behaviour that engineering now implemented. Taking a fresh look at InVision, I noticed that we currently still don't have horizontally scrolling "continue learning". I'll open an issue to add that.

**Comment by andrewwapling** [comment]
Hi @pedro16v thanks for confirming and teeing up the continuing learning module. The concept here is that it would help users with course progression by surfacing any started though not yet completed courses. Basically a launching pad back into the course detail in question to prompt users to continue their learning and complete courses. Let me know if you require any further details on this one? Thanks again, Andy

**Comment by pedro16v** [comment]
I've opened #938 to follow up on the "continue learning" carousel work

**Comment by pedro16v** [comment]
Hi @megganeturner — Mr. Nitpicking here 😁 

All working great, just one last thing. When I have no course categories, the section header doesn't have the same formatting it should (should be uppercase H4)

<img width="375" alt="Screenshot 2021-08-09 at 12 39 05" src="https://user-images.githubusercontent.com/2813677/128701148-f2937085-ea68-431f-8e71-68f6b2d56198.png">

**Comment by megganeturner** [comment]
> Hi @megganeturner — Mr. Nitpicking here 😁
> 
> All working great, just one last thing. When I have no course categories, the section header doesn't have the format it should (should be uppercase H4)
> 


🐞 👌  <-- pretend that's a nit and I'm flicking it away

No worries @pedro16v! Snuck this fix into https://github.com/catalpainternational/canoe/pull/943
