### ISSUE TITLE
JID: 1 user attribute is missing

### ISSUE THREAD

**Issue by Juliana-t** [catalpainternational/canoe#624]
- [x] Add user attribute attribute 'Speciality'
Please see this [document](https://docs.google.com/spreadsheets/d/1ZFWxbJZwD1h6H4pp5fioGWRj92HRkpK2OYQN1LlzWbE/edit#gid=0)

**Comment by PeteCoward** [comment]
reviewable on https://admin.jid-staging.temp.build/admin/

**Comment by Juliana-t** [comment]
Thanks Peter! It seems looks good on staging
