### ISSUE TITLE
Wagtail: make page type titles clearer

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#625]
![Screenshot 2021-04-20 at 14 33 46](https://user-images.githubusercontent.com/2813677/115342678-97206f00-a1e5-11eb-8ec3-7c8f03e93a05.png)

After a few iterations, we ended up with page type titles that can be confusing. Can we make so that:

- [ ] Learning Home --> Courses Home
- [ ] Resources List --> Resources Home

**Comment by PeteCoward** [comment]
reviewable on https://admin.jid-staging.temp.build, and https://canoe-redesign.temp.build

**Comment by pedro16v** [comment]
I can see it on https://admin.pep-staging.temp.build only @PeteCoward
