### ISSUE TITLE
Empty structure causes Canoe to fail

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#630]
If no items have been added to `Translatable Root` (in other words, if there's no home pages for Courses or Learning Activities) then Canoe had nothing to display. 

We could display a static page to make it fail more elegantly. Maybe a maintenance page that could be used somewhere else? @Juliana-t @KaraChesal @andrewwapling  ?

The browser console shows this:
`TypeError: Cannot read property 'getLanguagePageType' of undefined`

![Screenshot 2021-04-22 at 14 46 32](https://user-images.githubusercontent.com/2813677/115668831-89ecb700-a382-11eb-9aa8-eda9f4a404f7.png)

**Comment by pedro16v** [comment]
I should add that this is something that no user will ever have to worry with unless we promote Canoe installations with absolutely no content.

**Comment by PeteCoward** [comment]
We used to have a "low priority' label that was meant for situations like this

**Comment by andrewwapling** [comment]
Hi @pedro16v yes it could be good to have a designated design solution for a' 404' or 'Oops, something went wrong' to handle this (and any other critical failure) in an elegant way. Shall we move this into 'to do' for 'design'? I can then create a global design direction for this so that we have it in the DSM if needed. Thanks, Andy

**Comment by pedro16v** [comment]
@Juliana-t agrees with that. Thanks @andrewwapling .

**Comment by andrewwapling** [comment]
Ok great thanks for confirming @pedro16v @Juliana-t , I'll create a design direction for this and post back soon.

**Comment by andrewwapling** [comment]
Hi @pedro16v @Juliana-t ! @PeteCoward as promised please see 404 error screen for the unlikely event we encounter an error that's fatal to a users experience: https://invis.io/FR10XKHUJ5EB

**Comment by pedro16v** [comment]
Thanks @andrewwapling. We'll try to add this to the pipeline as soon as we get rid of the current big milestones.

**Comment by megganeturner** [comment]
Peter has added some basic error handling over in PR #677, and set up the site to handle three scenarios:
- manifest didn't load (server error - site content cannot be retrieved)
- the requested page doesn't exist (user error - usually produced by an incorrect url)
- any other unknown error

This design is great Andy, but I think we should remove the explicit `404` from the illustration (or have another illustration for server side issues)

The 'solution' copy & CTA also needs to reflect the nature of the error; if it's a server/manifest issue, refreshing/trying again may resolve it. However if it's a 404, a refresh will never fix it, and the user will need to navigate back to another page.

This is what we've done with it for now:

For a 404 (note navigation is still visible)
<img src="https://user-images.githubusercontent.com/12974326/118417156-1bd3af80-b6f6-11eb-9eb6-5bb12892f7ea.png" width="250">


For a server error:
<img src="https://user-images.githubusercontent.com/12974326/118417159-1d9d7300-b6f6-11eb-90e9-a620c0fa396e.png" width="250">

Any other errors will look as above, but the copy will be "Sorry, an unexpected error has occurred."

**Comment by pedro16v** [comment]
Thanks for the input @megganeturner ! Implementing this screen will have it's own issue for the next release.

**Comment by andrewwapling** [comment]
Thanks @megganeturner looking great! In light of this info I agree that the illustration is incorrect and recommend that we perhaps go for a generic image here that can cover all bases in terms of error types. I'll update the design accordingly and report back.

**Comment by andrewwapling** [comment]
@megganeturner I've update the error screen to utilise a generic error type illustration for time being, please see: https://invis.io/FR10XKHUJ5EB

Once we have all error type scenarios it would be great to list these and ensure we have appropriate headline, sub copy and call to actions for each scenario so that we cater to users needs :)

**Comment by andrewwapling** [comment]
@megganeturner I also think we may need to double check type sizes as it looks a bit small compared to the design currently

**Comment by pedro16v** [comment]
Closing in favour of #684
