### ISSUE TITLE
Course progress fails when Canoe has no Courses

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#631]
When Canoe has no `Learning Home` page (Courses home) and the user visits the profile, Canoe breaks.

`TypeError: Cannot read property 'coursesInProgress' of undefined`

---

According to [InVision](https://projects.invisionapp.com/d/main?origin=v7#/console/21052158/443710130/preview?scrollOffset=3480), the Course Progress page doesn't exist in PeP which means that it shouldn't exist in versions of Canoe that don't feature Courses. [InVision shows](https://projects.invisionapp.com/d/main?origin=v7#/console/21052158/443710130/preview?scrollOffset=3480) the profile as being the equivalent to settings on Canoe (under the cog icon)

**Question for** @PeteCoward : Can we make so that if Canoe doesn't have a published `Learning Home` page (Courses home), then the profile is just the settings screen? And when it does have, then it'll keep the current behaviour (profile with split in progress / complete, plus the cog icon that takes you to settings)?

**Question for** @Juliana-t @KaraChesal @andrewwapling : Is the above the expected outcome?

---

Broken Course Progress | PeP profile page on Invision
--|--
![Screenshot 2021-04-22 at 14 55 26](https://user-images.githubusercontent.com/2813677/115669982-e13f5700-a383-11eb-819c-5f8cbd18102c.png) | ![Screenshot 2021-04-22 at 16 01 55](https://user-images.githubusercontent.com/2813677/115670183-18ae0380-a384-11eb-99ad-54226a05dba8.png)

**Comment by PeteCoward** [comment]
When in pep, and click profile, go to current settings

**Comment by PeteCoward** [comment]
@pedro16v The PRs mentioned above allow us to configure a project to point the profile link to the settings page. A short term fix that we can use for PeP until we engineer a better solution. @md8n reviewing, can be published to pep-production if it passes his review.

**Comment by andrewwapling** [comment]
Hi @pedro16v @PeteCoward, I agree that we require a profile fall back for Canoe deployments that don't include Canoe learning elements or metrics. Presenting the user with a focused profile settings screen that doesn't display superfluous componentry would be ideal. I have created a settings focused screen design for consideration, please see attached.

Thanks again, Andy

![Profile - Pure Settings@1x](https://user-images.githubusercontent.com/13824612/116327402-0b709900-a80a-11eb-9aa4-257e61ccb53d.png)

**Comment by PeteCoward** [comment]
@pedro reviewable on https://pep-staging.temp.build

@andrewwapling implementing that design is a bigger feature, it's mostly achievable eventually, we can add profile picture uploading, email and name editing ability.
The one issue with it is "How often I want to receive Notifications" no real idea how that would work. We currently send notifications when an admin sends them, and I have seen plans in the social feature to send when your comment is replied to. How would this setting have affect on these features is not clear.

**Comment by Juliana-t** [comment]
Yes, I agree with Peter. At this stage we don't have a design decision on
how the frequency of notifications will work. For now, this shouldn't be
part of the settings and later on we can add. Probably the frequency will
need to come with a broader work on the 'notifications list' on the profile
or similar.

**Comment by pedro16v** [comment]
I will take @andrewwapling 's suggestion and attach it to a future issue once we're able to rework user settings.

**Comment by pedro16v** [comment]
Behaviour no longer breaks. Further work on #647

**Comment by andrewwapling** [comment]
Hi @pedro16v @PeteCoward @Juliana-t regarding notifications yes I believe there is a larger piece of work to design and define this in the pipeline. Also if profile image / avatar work is also not support we could simply omit these elements and create a very basic profile settings screen to accomodate the current use case as follows:

Screen: 
![Profile - Pure Settings Simple@1x](https://user-images.githubusercontent.com/13824612/116345734-15a38f00-a82c-11eb-8e46-cca0a7f977aa.png)

Invision: https://invis.io/AW10UKOXCJTX
