### ISSUE TITLE
When going through a Learning Activity, I can consult flash cards showing tips

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#639]
## Overview
The aim is to support teachers with supplementary information while preparing for a Lesson. These will feature supportive content, not necessarily lesson content.

## Conditions of Satisfaction
- [x] I can see a preview for the first tip on the Plan and Teach sections of the Learning Activity
- [x] I can open the flash card to see more tips
- [x] I navigate through the cards as I do in Activity cards
- [x] Flash cards have the same formatting options and types as Activity cards
- [x] When I reach the last flash card, I can go back to Plan or Teach, depending on where I started

## Resources
Reference design: [InVision](https://invis.io/T310SINEA2DN)

**Comment by PeteCoward** [comment]
@pedro16v I raised some questions about this [here](https://docs.google.com/document/d/1Zla5q3-MLbbmtzhzcarTxn3rTZs-HWWsHlB7kmiItFs/edit#heading=h.fa3oexeegw22) with @KaraChesal not sure if we have full answers for them yet.
The design does not seem to include the other non cards screens, and there is no clear answer about the completion/m&e data

**Comment by pedro16v** [comment]
Thanks Peter. We expect to be able to follow up on this during this week's engineering-design sync meeting.

**Comment by pedro16v** [comment]
On PeP staging, adding tips is breaking the lesson.

I have:
- On Wagtail, created a [child page](https://admin.pep-staging.temp.build/pages/74/edit/) for `Introducing bacteria and viruses`, under `Microorganisms`.
- Added that tip to the[ Plan section](https://admin.pep-staging.temp.build/pages/58/edit/#tab-plan) of `Introducing bacteria and viruses`
- The [lesson page](https://pep-staging.temp.build/#/site/pep-learning-activities/microorganisms/introducing-bacteria-and-viruses) now stops rendering correctly and shows the following error in the console:

<img width="570" alt="Screenshot 2021-06-07 at 14 43 46" src="https://user-images.githubusercontent.com/2813677/121027354-ce9ba880-c79e-11eb-8191-00b9cf9b9645.png">

**Comment by megganeturner** [comment]
@pedro16v This was fixed in this PR https://github.com/catalpainternational/canoe/pull/717, not sure if it's been deployed yet though

**Comment by PeteCoward** [comment]
deployed to https://pep-staging.temp.build
