### ISSUE TITLE
Resources: make available offline

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#645]
## Overview

Our current implementation of offline Resources works exactly like Courses. This option will not scale well over time. Courses have a discrete number of Lessons that can be downloaded but Resources can be a much longer list of items.

The latest direction seems to be to create a trigger to individually download each Resources in the same way Learning Activities.

Current implementation | Current implementation  | PeP solution
---|---|---
![Screenshot 2021-04-28 at 12 06 40](https://user-images.githubusercontent.com/2813677/116341251-87271180-a81b-11eb-8052-30082e3605ab.png) | ![Screenshot 2021-04-28 at 12 16 41](https://user-images.githubusercontent.com/2813677/116341313-9dcd6880-a81b-11eb-8895-15f0e9f8f47a.png) |  ![Screenshot 2021-04-28 at 12 10 05](https://user-images.githubusercontent.com/2813677/116341216-76769b80-a81b-11eb-93ca-79f063dadd31.png)

---

## Update

![Screenshot 2021-05-07 at 13 39 44](https://user-images.githubusercontent.com/2813677/117398640-b800f800-af39-11eb-9085-7f2ee0ffd9a3.png)

* Reference design: [InVision](https://projects.invisionapp.com/share/52Y02L9YTRF#/screens/429853508_Resources_List)

**Comment by pedro16v** [comment]
@PeteCoward would it be too much trouble to wire those individual download buttons (screen 2) to each card on the Resources listing (screen 1) so that it would behave like PeP (screen 3)?

**Comment by megganeturner** [comment]
> @PeteCoward would it be too much trouble to wire those individual download buttons (screen 2) to each card on the Resources listing (screen 1) so that it would behave like PeP (screen 3)?

@pedro16v Shouldn't be too much trouble at all as this is effectively what the modal is already doing. This would just require moving some code around (:

**Comment by pedro16v** [comment]
@andrewwapling would it make sense to mock up how this would look like on the specific case of Resources? 

According to the design, the Resources List can have an image preview which would interfere with a download button. We're not supporting this at the moment, which can also mean that a quick solution would be to replicate what happens on Learning Activities. The problem would resurface though as soon as we move forward with making Resources List more complete.

CC @Juliana-t 

![Screenshot 2021-05-07 at 11 28 30](https://user-images.githubusercontent.com/2813677/117389686-b1698500-af27-11eb-8d86-aa1c21d2a2a7.png)

**Comment by andrewwapling** [comment]
Hi @pedro16v , Yes I can definitely mock up a solution for this. Leave it with me and I'll report back with a design direction for review.

**Comment by andrewwapling** [comment]
Hi @pedro16v kindly see below link to uplifted resourced design that contains a 'Make Offline' function on a per listing basis: https://invis.io/52Y02L9YTRF#/429853508_Resources_List

Look forward to hearing your feedback.

**Comment by pedro16v** [comment]
Hi @megganeturner and @andrewwapling 

I can see [from the prototype](https://projects.invisionapp.com/share/52Y02L9YTRF#/screens/429853508) that we're only showing the offline state of a Resource. Meggan has implemented it so that the icon turns green and shows "Downloaded" below it.

It feels cramped, so I have two questions/suggestions:
1. The section on the left feels like it could have a 20px margin to the "make offline" button.
2. I can see [from the PeP prototype](https://projects.invisionapp.com/d/main?origin=v7#/console/21052158/443710124/preview?scrollOffset=1703) that the "downloaded" state looks different. Should this be the way to go @andrewwapling ?
  2.1 If the above is not feasible at the moment, maybe using "Available" instead of "Downloaded" is a good idea to achieve a better balance? (or a better and shorter word you can come up with)

Let me know what you think.

**Comment by andrewwapling** [comment]
Hi @pedro16v @megganeturner just confirming I'd prefer the top right flag as per the PeP example. I feel this is visually cleaner and more succinct. I've updated Bero core to display this: 

https://invis.io/52Y02L9YTRF#/429853508_Resources_List

I also feel we should lose the resource type tagging. I believe this may be a hangover from a previous iteration of resources? I don't think Raw, Basic etc. adds any real value to a user. Plus it takes up precious vertical space. Of more value would be a thumbnail image or poster image for video with associated flag if appropriate as per design.

**Comment by pedro16v** [comment]
I'll eventually spin up a new issue for us to review this card altogether then!

**Comment by andrewwapling** [comment]
Ok great thanks @pedro16v :)
