### ISSUE TITLE
As a user, I can flag comments as being inappropriate

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#654]
## Overview
We want to enable Canoe users to take down inappropriate comments on the Discussion section. These comments should be immediately removed for that individual user but subject to moderation by a content manager. Should the content manager consider the comment is inappropriate, then it gets hidden from all users. If not, the comment is restored.

## Conditions of Satisfaction
- [x] I can flag a specific comment
- [ ] The comment is highlighted
- [x] A toast message informs me if the comment has been successfully flagged
  - [x] The toast goes away after 6s
- [ ] The comment is hidden from me after 6 seconds.

## Resources
- Reference design: [InVision](https://projects.invisionapp.com/d/main?origin=v7#/console/21265373/448758612/preview?scrollOffset=503)

![Screenshot 2021-04-29 at 14 48 18](https://user-images.githubusercontent.com/2813677/116509391-27556700-a8fe-11eb-8174-4ac2850c8b36.png)

**Comment by pedro16v** [comment]
@Juliana-t everything works except for the comment to be immediately hidden for the user who reported it.

**Comment by Juliana-t** [comment]
perfect! we can deploy as is and next week work on hidding it for the user
who reported it?

**Comment by pedro16v** [comment]
@megganeturner can we momentarily highlight the reported comment in the same we highlight it when we just post it?
