### ISSUE TITLE
PeP Design Tweaks

### ISSUE THREAD

**Issue by megganeturner** [catalpainternational/canoe#657]
A number of FE tweaks flagged in PeP (though the changes are appropriate across canoe):
https://pep-production.catalpa.build/

### Higher Priority
- [x] list styles from `richtext` components does not match the styles for the `listcard`, but they should
- [x] the header image height on the learning activity detail screen needs to be about 20% taller
- [x] card image heights on topics index need to be consistent (same as course listing on canoe)
- [x] bottom swoop is too pronounced
- [x] character limits for the learning outcomes / overview list items are too short (55 right now) (BE task) [example of cut off content](https://pep-production.catalpa.build/#/site/pep-learning-activities/microorganisms/how-bacteria-reproduce)

### Lower Priority
- [ ] marking an activity as complete does not persist, and does not show any status on the cards
- [x] external links in `richtext` should have `target="_blank"` to open in new tab
- [ ] portrait images take up too much vertical space - is there a way to crop this to be square (with option to expand?)
- [x] images need border radius (8px)
- [x] full screen button is not aligned properly on image
- [x] lines between cards missing in FE
- [x] reorder header/image for activity cards (so that the header is above the image) in a basic card (only for activity page!)
- [ ] video previews / youtube links (not immediate, needs wider discussion)

**Comment by pedro16v** [comment]
To be continued on #662

**Comment by Juliana-t** [comment]
@pedro16v @megganeturner could we have 
- [x] external links in `richtext` should have `target="_blank"` to open in new tab
on all instances of Bero? Looking forward to have that on Kumul Helt Skul as well

**Comment by pedro16v** [comment]
Tracked in #724. Please don't reuse this issue.
