### ISSUE TITLE
JID branding

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#671]
Time to customize JID! Or should I say... KUMUL HELT SKUL!

<img width="376" alt="Screenshot 2021-05-11 at 17 49 43" src="https://user-images.githubusercontent.com/2813677/117787311-52867180-b281-11eb-850b-cfb9aac70022.png">

## Resources
- [ ] Check the prototype on [InVision](https://invis.io/JP10KR0VA748) for guidance.
- [ ] Please follow the[ theming checklist here](https://github.com/catalpainternational/canoe/wiki/Canoe-knowledge-base#theming).

### Some specific variables

**Settings screen logo order** (left to right)
- PNG Department of Health
- PNG-Aus Partnership
- JID
- Catalpa

**Custom styles**
- Button colour (solid and outline): JID primary green colour `#14994D`
- Button radius: 100% (as per core)
- Tab and toggle highlights: JID primary green colour `#14994D`
- Top and bottom swoosh device: `#F4F8FA` to `#D9E2E7` linear gradient @ 75% opacity as per core design

#### Project brand
- Project logotype and versions - [Link](https://drive.google.com/drive/u/1/folders/1K7R3V8ykflro5sjg1PLuMyrjIprPsaUD)

#### Images required for branding Canoe instance
- site logo - [Link](https://drive.google.com/drive/u/1/folders/1K7R3V8ykflro5sjg1PLuMyrjIprPsaUD)
- app icon for mobile home screen [Link](https://drive.google.com/drive/u/1/folders/1K6pgagWPuG91uwBneCmVfELrKLUns00_)
- favicon (as svg) - [Link](https://drive.google.com/drive/u/1/folders/1K2cXcqlk9xu6NuYGiukthyWHPXTv15EI)
- default placeholder for course image - [Link](https://drive.google.com/drive/u/1/folders/1Lyp8W0C73cgLPfZd8EtENi4ELDebYgBB)
- default placeholder for lesson image - [Link](https://drive.google.com/drive/u/1/folders/1LxVZFVyk3tJNA7CN4wrkq17YnXl3jn04)
- default placeholder for exam image - [Link](https://drive.google.com/drive/u/1/folders/1LuxdqM3S42eEtHEGY0Quwn-NNrkd_S1f)
- loading image
  - illustration - [Link](https://drive.google.com/drive/u/1/folders/1LrI75xl5eNamczpomR3IwIROl4FnAgcL)
  - UI (with illustration) - [Link](https://invis.io/JP10KR0VA748)
- login page - [Link](https://invis.io/ND10XL747GC6)
- finished lesson ('Great job' after finishing with all content in a lesson) - [Link](https://drive.google.com/drive/u/1/folders/1Lv9huZ8AgGGgh-TgCTjXwKfZwBwBEMJg)
- submitted feedback [Link](https://drive.google.com/drive/u/1/folders/1Lzmqc64VrWMvSIblKqiXQ8b3LgbvDWq1)
- finished course/exam ("Congratulations" card) - [Link](https://drive.google.com/drive/u/1/folders/1Lvti8epM6dP_hJb2_Vpa0IpiWNQ7MWnN)
- logos on the settings screen with the following order - [Link](https://invis.io/JP10KR0VA748#/448221869_Profile_-_Settings)

#### Resources (for Design only)
- Example - [issue for branding Canoe instance for Hamahon](https://github.com/catalpainternational/hamahon/pull/182)
- [Logos](https://drive.google.com/drive/folders/1q4FP_KMDmYe38lEqZWYKBPFO9AfZXFCA) @Juliana-t to follow-up with JID to discuss what logos need to be in the app
- [Results from the survey](https://docs.google.com/forms/d/1eTPAeFBgjbNP1br6p8EFllZa3P9IK0uo4M5rpZtzk24/edit#responses)
- Images and design resources (to be added by @DanielHeads when ready)

**Comment by megganeturner** [comment]
Some notes here:
- I'll put [this illustration](https://drive.google.com/drive/u/1/folders/1LrI75xl5eNamczpomR3IwIROl4FnAgcL) in for the loader for now, but this needs to change. In the core canoe project, the loader is one svg and the FE simply displays the SVG. In the design for the JID implementation, there are multiple elements (illustration, swoop, logos) which the FE is not set up to support, particularly in terms of overrides. For this to work I need that whole design (illustration, swoop & partner logos and text) to be one svg
- Canoe is no longer using placeholder images specifically for a `course`, `lesson`, or `exam` - we simply have 5 placeholder images and they get randomised. I don't know if the JID exam placeholder image really makes sense in the other contexts, so this will need to be discussed. I also need these images as SVGs, not pngs (I've tried converting them but haven't had any luck with any of the tools I've tried - they're either really bad quality or they're black and white - so hoping a designer can work some magic here ✨ )

**Comment by Juliana-t** [comment]
On this:
> * I'll put [this illustration](https://drive.google.com/drive/u/1/folders/1LrI75xl5eNamczpomR3IwIROl4FnAgcL) in for the loader for now, but this needs to change. In the core canoe project, the loader is one svg and the FE simply displays the SVG. In the design for the JID implementation, there are multiple elements (illustration, swoop, logos) which the FE is not set up to support, particularly in terms of overrides. For this to work I need that whole design (illustration, swoop & partner logos and text) to be one svg
@andrewwapling should be able to provide you what you need - Andy, please have a look

On this:
> * Canoe is no longer using placeholder images specifically for a `course`, `lesson`, or `exam` - we simply have 5 placeholder images and they get randomised. I don't know if the JID exam placeholder image really makes sense in the other contexts, so this will need to be discussed. I also need these images as SVGs, not pngs (I've tried converting them but haven't had any luck with any of the tools I've tried - they're either really bad quality or they're black and white - so hoping a designer can work some magic here ✨ )
I need to understand this better.

**Comment by andrewwapling** [comment]
Hi @megganeturner @Juliana-t thanks for these queries.

1. Regarding the loading image I have liaised with @megganeturner and supplied a 'pseudo' SVG that encapsulates all of the elements. This approach should hopefully get us out of trouble as an interim measure. I've contacted @DanielHeads and requested the SVG versions of the illustrations to be supplied. I believe there could also be and opportunity to create a more immersive branded / illustration based loading screen that uses bolder colour. I would love @DanielHeads input here? Alternatively once I receive SVG assets I can explore a more graphic approach that's in line with core canoe design seen here: https://invis.io/E210YPDW8WCN

2. I believe I raised the potential for the need for fallback images for the course, lesson and exam cards and hero banner images in another issue. The main use case for these I believe are legacy deployments and scenarios where a user doesn't upload an image. I would value @DanielHeads input here from a branding and illustration perspective for what could work best here. From experience in Canoe core and Hamahon a more abstract pattern based approach is effective. Light schemes work best for the cards and darker for the hero banner area.

Hope this helps and drop me a line with any queries at all.

**Comment by Juliana-t** [comment]
@megganeturner here are the assets in svg for you, please let me know if anything is missing
- [ ] [4 images for the placeholders for lessons/courses/exams](https://drive.google.com/drive/u/0/folders/1OBf_3g0eTBYJTQd7WRiGkUq6kSTs9Xsp) - We still have 1 missing, can we start with this 4 and add one more later?
- [ ] [Login](https://drive.google.com/drive/u/0/folders/1O2Whub5IU-jAJ3yIChVZVeT1UST8WlCn)
- [ ] [Course completed](https://drive.google.com/drive/u/0/folders/1NyW2y7h-A9sB-6OTdJGXj1kPs3g64cqp)
- [ ] [Exam passed ](https://drive.google.com/drive/u/0/folders/1Lvti8epM6dP_hJb2_Vpa0IpiWNQ7MWnN)
- [ ] [Thanks for submitting feedback](https://drive.google.com/drive/u/0/folders/1Lzmqc64VrWMvSIblKqiXQ8b3LgbvDWq1)
- [ ] [Lesson completed](https://drive.google.com/drive/u/0/folders/1Lv9huZ8AgGGgh-TgCTjXwKfZwBwBEMJg)
- [ ] [Image for the loading screen](https://drive.google.com/drive/u/0/folders/1LrI75xl5eNamczpomR3IwIROl4FnAgcL)

**Comment by megganeturner** [comment]
Thanks @Juliana-t! Have pushed those updates to https://github.com/catalpainternational/jid/pull/8 for @PeteCoward's review (:

**Comment by andrewwapling** [comment]
Hi @megganeturner just noticed a couple of little visual tweaks needed for the loading and login page as follows (screenshots attached):

1. Loader
• The image seems about half size and needs to increase to match design more closely
• The Powered By copy appears to default to a serif font and needs to use the sans serif in design 'Circular'
• The curve device doesn't reach edge to edge

2. Login
• The image seems about half size and needs to increase to match design more closely
• The password field text when typing defaults to a serif font and needs to use the sans serif in design 'Circular'

Thanks again, Andy
![screen_shot_2021-05-17_at_2 44 47_pm](https://user-images.githubusercontent.com/13824612/118566378-1e4a0e00-b7b7-11eb-8711-0e5f15ccdbc6.png)   
![screen_shot_2021-05-17_at_11 37 21_am](https://user-images.githubusercontent.com/13824612/118566391-2144fe80-b7b7-11eb-98b3-b326ca816482.png)

**Comment by andrewwapling** [comment]
Hi @megganeturner @Juliana-t and I have been chatting about some concerns around the partners logos on the login screen falling too far past the fold on small devices. 

In an order to alleviate this I have put together a range of design recommendations for review and implementation:

• Reduce the login illustration size slightly by around 10% (this may save us 10-20px approx)
• Hide the Login title on this screen as it’s already apparent to a user that this is a login screen due to both the format of the page and the login button (this may save us 40px approx)
• Sneak a bit of padding top and bottom of image to recover another 20px or so in vertical heught
• Halve the padding after the curve and before the fields where we could also save around another 30px
• On another note can we introduce the circle element with the login illustration to more closely match the design?

Using the above adjustments we could recover almost 100px in vertical height approx.

Hope this helps and sing out with any queries at all.

Thanks again, Andy

**Comment by Juliana-t** [comment]
For @megganeturner 
We are using the same illustration for the 'Good job' screen when a learner completes a lesson and for the 'Amazing work!' when a learner completes a course.
![Screen Shot 2021-06-04 at 11 09 06 AM](https://user-images.githubusercontent.com/52807808/120785931-8b82d080-c525-11eb-8854-bf2f43eed831.png)
![Screen Shot 2021-06-04 at 11 10 00 AM](https://user-images.githubusercontent.com/52807808/120785935-8cb3fd80-c525-11eb-9519-8f5df9379ed7.png)

We should be using this illustration on the Lesson completed screen
And [this other illustration](https://drive.google.com/drive/u/0/folders/1Lvti8epM6dP_hJb2_Vpa0IpiWNQ7MWnN) on Course completed screen

**Comment by megganeturner** [comment]
Hey @Juliana-t thanks for picking this up! In Bero core the image used here is the same. In order for them to be different in JID, we'll need them to be different in Bero - @andrewwapling are you able to provide an appropriate additional asset for bero here?

**Comment by andrewwapling** [comment]
Hi @megganeturner thanks for flagging this. Please see links below to the lesson confirmation screen and course confirmation that both have slightly different success based illustrations. 

The course confirmation has the confetti illustration / animation element to make it more celebratory than the lesson one.

Lesson Success Screen: https://invis.io/YS114JAEVDN9
Course Success Screen: https://invis.io/GN10397PBAQK

Hope this helps and let me know if you need anything else at all.

**Comment by megganeturner** [comment]
PRs in for this:
https://github.com/catalpainternational/jid/pull/13
https://github.com/catalpainternational/canoe/pull/726

**Comment by pedro16v** [comment]
Hi @andrewwapling @Juliana-t @megganeturner 

Just to confirm that we're using the following illustrations

lesson completed | course completed
--|--
<img width="256" alt="Screenshot 2021-06-10 at 11 35 21" src="https://user-images.githubusercontent.com/2813677/121510920-0ba2ad80-c9e0-11eb-8bb7-957978ea0a22.png"> | <img width="592" alt="Screenshot 2021-06-10 at 11 34 02" src="https://user-images.githubusercontent.com/2813677/121510935-10676180-c9e0-11eb-8d3d-d61a89baaffc.png">

Another thing I'd like to follow up is the available actions for each screen. How do these organise in every possible situation?

**Lesson complete can have:**
* As primary actions
  * Next lesson
  * Take exam / survey
* As secondary actions
  * View resources
  * Join the discussion
  * Back to course

**Course complete can have:**
* As primary actions
  * Back to Courses
* As secondary actions
  * View resources
  * Join the discussion

**Comment by pedro16v** [comment]
Illustrations seem to be correct. I'll close this one and spin a new one to sort out primary and secondary actions.
