### ISSUE TITLE
Content projection: teachers can cast media

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#682]
## Overview
Some important notes while designing a solution:
* Teachers need to easily know how and when they need to project lesson activity content in my classroom
* Teacher have an easy way to jump into projection mode and back into the “teach” flow
* Teachers using the app for the first time feel supported and confident to setup the projection of the activity content

## Conditions of satisfaction
* Media in a lesson can be casted using an external network device
* Media in a lesson shows a casting symbol, informing users that they can cast that content

## Resources
- Reference design: [InVision](https://invis.io/6V102V1VURS9#/443710126_Learning_Activities_-_Detail_-_Teach)

**Comment by pedro16v** [comment]
Latest design from @andrewwapling https://invis.io/6V102V1VURS9#/443710126_Learning_Activities_-_Detail_-_Teach

**Comment by andrewwapling** [comment]
Thanks for setting this up @pedro16v – let me know if you require any additional design support on this one.

**Comment by pedro16v** [comment]
Some notes to help with future direction [here](https://docs.google.com/document/d/1YulOVeTxdOW8rfphGiBTqi56SsUo0koqa_5kJ3_bXJI/edit)

**Comment by pedro16v** [comment]
In light of recent conversations, there are a few questions that **need answers.**

The [most updated design](https://projects.invisionapp.com/share/6V102V1VURS9#/screens/443710126_Learning_Activities_-_Detail_-_Teach) is a simple dismissible help text box informing the user about the benefits of casting media. You can also see a casting icon over the video.

The rationale is straightforward: show help next to the castable element.

<img width="320" alt="Screenshot 2021-07-16 at 10 59 06" src="https://user-images.githubusercontent.com/2813677/125930667-89121aec-6816-4e18-919e-c366e1308e24.png">

---

Now, I seem to recall @PeteCoward say that it's not easy to just make that help text box appear in different locations. It's easier to define a static position on the card. Am I correct @PeteCoward? 

**Thoughts**:
- Having to manually add casting help to cards that contain media (in the same way we add tips) seems odd. Unlike tips, the content here will always be the same. You'll see the same help text for every media element.
- If we can't position the help text box next to the media element, the alternative would be to find a place for it somewhere else in the interface. 
  - The very top? The very bottom? — we loose context
  - Some sort of roll up or banner? — would it appear every time we visit a card that contains media? Super annoying.
- Even if we can show the help text box next to the media element, what happens if a card has multiple? Do we multiply those boxes too? Too cluttered... See examples below:
  - Screen A shows how out of context the box would be at the end of the card
  - Screen B shows how cluttered the interface gets with one box per media element
  - Screen C is an alternative to B where only the first media element would have a help text box
  - Screen D uses the roll up. It forces users to dismiss it to be able to continue

<img width="950" alt="Screenshot 2021-07-16 at 12 01 41" src="https://user-images.githubusercontent.com/2813677/125938643-ca2a309a-3e1f-41f0-b311-60824ad61588.png">

@andrewwapling heeeeeeeelp!

**Comment by pedro16v** [comment]
From @megganeturner [on slack](https://catalpa.slack.com/archives/C0189F7P0UR/p1626439595047900?thread_ts=1626434024.047500&cid=C0189F7P0UR):

Just chiming in here with some thoughts and to explain what I went with when building it:
* Casting tip appears immediately under the video card in the learning activities only (won’t appear in a course/lesson). Given that video content blocks in this section can come through with text too, currently the tip would appear below the text, (so if the text block is long the tip could appear quite far down scrolling-wise). This is relatively easy to fix so that it is immediately below the video.
* Currently it would appear many times (like in your beautiful option B drawing) which I agree is kinda ugly and crowded. It would be easy to modify this so that it only appears on the first one for option C
* A question I had: the tip has a little cross button to dismiss it. If you dismiss the tip and refresh the page, should you see the tip again, or should it disappear forever? And if you dismiss it once, should they never appear again anywhere ever?
* The casting icon over the video concerns me a little - we can’t bake any functionality into this button right now. The casting functionality just exists in the native video element for whichever browser/OS is being used. Placing elements on top of videos can hide actual controls and can get fiddly for cross browser/OS compatibility, so I’d proceed with caution there

**Comment by andrewwapling** [comment]
Hi @megganeturner @pedro16v thanks for the input above. In light of these comments I've adjusted the design direction for your review and feedback. Kindly see updated prototype links above. Key points:

• I believe option 'C' whereby we present a single casting tip directly below the media would be best (without repeating it across each media element). My feeling with the modal roll up option is that it would be too brusque and I feel the inline approach is more subtle and contextual as it allows users to either scroll by, read more and dismiss either permanently or on a session basis. I believe it's best to reserve the roll up pattern for more critical actions i.e. successful response, unsuccessful response, confirmations and approvals etc.

• I have utilised the modal roll up for a dismiss confirmation i.e. giving the user the ability to hide casting tips permanently, hide temporarily on a session basis or cancel and return to what they were doing

• Good pickup @megganeturner re: casting icon control over the media itself. I tend to agree that considering we're not baking in native casting controls into the Bero app at this point in time that we should defactor this element

• I have updated the copy in the casting tip flow would love feedback on this from @andrewerbs @KaraChesal 's perspective to ensure it hits the mark in terms of what we would like to convey to teacher's here. Likewise would like @megganeturner @PeteCoward 's feedback on whether we offer the iOS & Android helper screenshots or whether we need to tweak this screen's content to make it more generic?

Casting tip component located under media in the Learning Activity Teach tab: https://projects.invisionapp.com/d/main?origin=v7#/console/21052158/443710126/preview?scrollOffset=2126

Casting tip flow commencement: https://projects.invisionapp.com/d/main?origin=v7#/console/21052158/452323680/preview?scrollOffset=2126

Casting tip component hide confirmation modal roll up: https://projects.invisionapp.com/d/main?origin=v7#/console/21052158/455573697/preview?scrollOffset=2126

Kindly review and let me know your thoughts, queries and whether you're happy with this approach? Thanks again, Andy

**Comment by pedro16v** [comment]
Makes sense to me @andrewwapling. 

I agree to:
1. Having the tip just under the first media element
2. The tip allows the user to go through an explainer flow
3. The tip is dismissible

On how it is dismissible, I see value on your suggestion @andrewwapling but will leave it to @KaraChesal and @Juliana-t to decide from a product perspective. My recommendation is to add permanent dismissal as a stretch goal, for the moment.

**Comment by andrewwapling** [comment]
Hi @pedro16v thanks for confirming, sounds like a good approach to me. Let me know if you require any additional design support on this one :)

**Comment by Juliana-t** [comment]
Thanks everyone, agreed with all. Soft dismiss for now would be preferred. Teachers may share devices in some schools.
We can work on the permanent dismissal (as an additional alternative) in a future iteration.

**Comment by pedro16v** [comment]
> Just when I thought I was out, they pull me back in!

_— Michael Corleone, The Godfather Part III_

---

Ok, a number of things:
1. **Tall videos generate tall video placeholders**. We seem to have some videos on PeP that have been produced for smartphone, so they have a tall ratio. Makes sense from the content point of view but make the page look weird when not being played.
2. **Video title and description should be above the video**. Adding these below the video makes it seem that it belongs to some other element. Things get worse when there's another video below — the title and description of the first video appear to relate to the second one. I remember saying that the casting tip should be immediately below the video, which is correct but the text simply doesn't work.

I took some screenshots and played around a bit to see if we can get quick feedback from @megganeturner and @andrewwapling . Thoughts are welcome.

**A** — This is how it's looking now
**B** — Notice how the text seems to belong to the second video
**C** — How it looks like when text is before the video
**D** — Same as **C** but with reduced preview height

| A | B | C | D | 
| - | - | - | - |
<img width="180" alt="Screenshot 2021-07-23 at 11 22 36" src="https://user-images.githubusercontent.com/2813677/126769294-73458b38-032c-48d7-a573-7e494bc35776.png"> | <img width="181" alt="Screenshot 2021-07-23 at 10 50 26" src="https://user-images.githubusercontent.com/2813677/126768500-a206a50f-f9d1-45eb-8d21-68197c6ba292.png"> | <img width="180" alt="Screenshot 2021-07-23 at 10 52 01" src="https://user-images.githubusercontent.com/2813677/126768537-20bd8e49-f4bc-4d75-a0f5-b96aca4a14cf.png"> | <img width="180" alt="Screenshot 2021-07-23 at 10 54 10" src="https://user-images.githubusercontent.com/2813677/126768562-756c8d12-f7dd-4118-b1b6-59ded8da3ece.png">

**Comment by andrewwapling** [comment]
Hi @pedro16v @megganeturner thanks for sharing this and apologies for the delay in getting back to you. My recommendations would be as follows:

1. Ensure we render video player viewport as 16:9 ratio regardless of source video to avoid awkward space and pushing down of content deep in the fold
2. Render the poster image thumbnail for portrait videos with black bars either side to avoid awkward see-through feel to the video player viewport
3. Text that's associated with a video would make more sense sitting above the video. In this way it would act as an intro and description of the video that's about to follow
4. The casting tip could then sit directly below the video or media in question

Let me know if you require any further details on this one or have any queries at all.

Thanks again, Andy
