### ISSUE TITLE
Content managers can set an exam score

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#685]
Currently, Bero is using a fixed value of 75% to approve exams. We want content managers to be able to set that value for each individual exam.

## Conditions of satisfaction
* Content managers can set the needed score for each exam.
* The default score remains at 75%

**Comment by pedro16v** [comment]
Two things I've found.

1. I can set the score for Pre-learning surveys. Can we hide that option on Wagtail for this type?
2. I see a console error when loading the Course List page

<img width="535" alt="Screenshot 2021-06-10 at 12 18 23" src="https://user-images.githubusercontent.com/2813677/121517857-bb2f4e00-c9e7-11eb-939f-82a4a81231af.png">

**Comment by megganeturner** [comment]
> Two things I've found.
> 
> 1. I can set the score for Pre-learning surveys. Can we hide that option on Wagtail for this type?

Yes, this is addressed in https://github.com/catalpainternational/canoe-backend/pull/213

> 2. I see a console error when loading the Course List page
> 
> <img alt="Screenshot 2021-06-10 at 12 18 23" width="535" src="https://user-images.githubusercontent.com/2813677/121517857-bb2f4e00-c9e7-11eb-939f-82a4a81231af.png">
Snuck the fix for this into https://github.com/catalpainternational/canoe/pull/725

**Comment by pedro16v** [comment]
Waiting for https://github.com/catalpainternational/canoe-backend/pull/213 to be merged
