### ISSUE TITLE
Social Learning Design Review

### ISSUE THREAD

**Issue by andrewwapling** [catalpainternational/canoe#688]
Hi @megganeturner @pedro16v @PeteCoward as promised I have conducted a design review of the social learning implementation. 

I've marked up a number of small visual refinements I would recommend us making to more closely match the design direction and achieve a more polished and visually consistent design and experience. I have marked these design review comments up in an Invision prototype so that we can see them in-situ on screenshots. I felt this was the best way to pinpoint the issues plus it should also make it easy to ask any questions directly via the comment tool or here on GitHub.

https://invis.io/WM110G7WGR4X

Let me know if you have any queries at all or require further design support on this one. Thanks for all your work on this it's looking really great :) 

Thanks again, Andy

**Comment by andrewwapling** [comment]
Hi @megganeturner let me know if it's beneficial to arrange a time to have a quick design review catchup to chat through the comments and answer any queries? Also hit me up directly with any questions here on Slack and and I'll do my best to provide answers and recommendations. Thanks again for your help, Andy

**Comment by pedro16v** [comment]
Thanks for this @andrewwapling !
@megganeturner do you need me to split Andy's feedback on separate issues or does this work for you? If any of the review items take too long, it might be a good idea to put them on their own issues so we can prioritise and track as needed.

**Comment by megganeturner** [comment]
@pedro16v I'll work from this ticket and then any bigger ticket items I come across, I'll pull into separate issues (:

**Comment by andrewwapling** [comment]
Thanks for your support @pedro16v @megganeturner – kindly let me know if you require any additional detail at all :)

**Comment by pedro16v** [comment]
I'm still seeing some discrepancies between the review and what has been published. I'll open a new issue if there's any leftovers.

**Comment by andrewwapling** [comment]
Hi @pedro16v let me know if you'd like design support reviewing the updates?

**Comment by andrewwapling** [comment]
Sounds like a good plan of attack @pedro16v :)

**Comment by pedro16v** [comment]
Hi @megganeturner, reviewing this more carefully I found a couple of things. I'll link to the specific comments on InVision below.

- [ ] Font size on the "no discussions" warning — [InVision](https://projects.invisionapp.com/share/WM110G7WGR4X#/screens/452133294/comments/143085903)
- [ ] Check icon size on toast message (and I think font size too) — [InVision](https://projects.invisionapp.com/share/WM110G7WGR4X#/screens/452133298/comments/143086035)
- [ ] Start/Continue button chevron is still sticking to much to the right — [InVision](https://projects.invisionapp.com/share/WM110G7WGR4X#/screens/452133300/comments/143086113)

Are these fixes you could easily accommodate? Thanks!
