### ISSUE TITLE
Bug: Can't login

### ISSUE THREAD

**Issue by Juliana-t** [catalpainternational/canoe#701]
On the app I can't login on Kumul Skul prod > https://kumulheltskul.com/#login (credentials are correct)
but I can login to Wagtail prod using the same credentials

**Comment by pedro16v** [comment]
I'm seeing the same also for `https://canoe-redesign.temp.build/` and `https://pacificlearn.io/`. In all cases, the browser console shows a 403 error. Credentials work on all staging sites.

**Comment by PeteCoward** [comment]
fixed on both deployments
