### ISSUE TITLE
Course progress is lost on refresh or logout/login

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#706]
Seen both on `jid-staging.temp.build` and `kumulheltskul.com`

**Method 1**
1. Complete some lessons
2. Verify that progress is shown (icons, progress bars, etc)
3. Log out and log back in. Progress is lost

**Method 2**
1. Execute steps 1-3 above
2. Refresh the browser. Progress is lost

---

The video below shows a user completing a lesson, checking the progress, and logging out. Once the users logs back in, the progress information is lost.

![Screen Recording 2021-06-01 at 14 14 44 mov](https://user-images.githubusercontent.com/2813677/120329908-36a44780-c2e4-11eb-967e-a20bfe058f09.gif)

**Comment by PeteCoward** [comment]
fix reviewable on https://jid-staging.temp.build/

**Comment by pedro16v** [comment]
Works great. All changes are now also quickly reflected across devices 👍
