### ISSUE TITLE
Clean up styling for cards

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#719]
It's not always easy to predict the final result of what is entered on Wagtail's editor. Elements like headers, lists, normal text behave differently and could probably use some work. Here's an example of how the final version doesn't match the spacing seen on Wagtail.

![Screenshot 2021-06-03 at 10 42 01](https://user-images.githubusercontent.com/2813677/120813884-3e632680-c546-11eb-9803-8fb67f3292fa.png)

Even when I add multiple returns, some elements will still be immediately on the next line (H4, lists).

@andrewwapling can we have your recommendation on default margins for each element:
- H2
- H3
- H4
- Numbered list
- Bulleted list
- Line break (?)

Thanks!

**Comment by andrewwapling** [comment]
Hi @pedro16v @megganeturner thanks for getting this through to me. Please see below styles package that defines optimal recommended spacing for the following elements:

• H1
• H2
• H3
• H4
• Body Copy
• Ordered Lists
• Unordered Lists
• Pull Quotes

https://invis.io/52Y02L9YTRF#/453255697_Activity_-_Content_-_Styles_Package

Sing out with any queries or let me know if you require any additional details at all.

Thanks again, Andy

**Comment by andrewwapling** [comment]
A pleasure @pedro16v! @megganeturner feel free to reach out with any queries at all or if you require anything further on this one :)
