### ISSUE TITLE
Video thumbnails not displaying

### ISSUE THREAD

**Issue by PeteCoward** [catalpainternational/canoe#722]
The thumbnails exist, but are referenced wrong causing not founds which show up as CORS issues
https://kumulheltskul.com/#/site/learn/course-5-triage-and-flow-in-practice/lesson-1-triage-in-practice:content:9

We are missing a `/media/` in the paths used by the frontend

- The manifest [get_media_manifest function](https://github.com/catalpainternational/canoe-backend/blob/RC-3.0/elearning_content/manifest.py#L153) returns paths from the db ( which do not include the MEDIA_URL )
- The [VideoCard riot tag](https://github.com/catalpainternational/canoe/blob/RC-3.0/src/riot/Lesson/VideoCard.riot.html#L7) uses the [Asset thumbnail getter](https://github.com/catalpainternational/canoe/blob/RC-3.0/src/ts/Implementations/Asset.ts#L270) to place those paths in the DOM.

Neither of these places add the `media/` prefix

Options:

1. add `media/` in canoe, quick to dev( but hardcoded )
2. add MEDIA_URL prefix in canoe-backend ( better because MEDIA_URL is controlled and changed by the backend, but slower and we should consider doing this for ALL assets not just thumbnails ( images and media files )

**Comment by pedro16v** [comment]
I seem to be the only one still complaining about this. Let's get rid of this one and open a new one should the problem persist.
