### ISSUE TITLE
"make available offline" & LAN sync interaction questions

### ISSUE THREAD

**Issue by boerwastaken** [catalpainternational/canoe#729]
Related: #604 

Problem description:

As I understand it, currently, one can "make available offline" a lesson, but that won't include its videos by default. If that is untrue then we can disregard this issue ;-)

So what then could happen is that a teacher is in a village-with-internet, dutifully "makes available offline" the appropriate lessons, and then starts seeding in the school-without-internet through LAN sync. But the recipient peers will not get any videos, because the teacher didn't "make available offline" those videos.

Questions:

1. Had the teacher gone through each lesson, "make offline"-ing each and every video, would the peer in the school have synced those videos?
2. If so, is this the desired workflow for a teacher? Is it reasonable to expect them to do all these manual actions? Or would they be accommodated with a button "MAKE UTTERLY OFFLINE" next to the "make available offline" button? We could opt to show the "utterly" button only in Beiro-on-Android.
3. What would the video format priority look like? Since the video will be *redistributed*, probably we'll just want to download the video with the widest compatibility, rather than smallest size or highest quality or suchlike.

**Comment by PeteCoward** [comment]
> If that is untrue then we can disregard this issue
This is untrue now, the make course / lesson offline buttons download all assets including media

The format chosen is the format for the device which initially makes offline, currently this would be no different to the format desired by anyone who received a sync.

**Comment by boerwastaken** [comment]
Ok, all good then, makes sense. The videos are an integral part of the lessons \* and so you either have a lesson available offline with all its videos, fit for redistribution via LAN sync etc, or you don't have that lesson available offline (and it won't be redistributed through LAN sync etc). Is that correct?


\*) (hopefully, as they're awfully large to have lying around if they're not actually all that useful)
