### ISSUE TITLE
Card not showing available video rendition

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#754]
Continued from [here](https://github.com/catalpainternational/canoe-backend/issues/134)

On JID staging, I'm still seeing the infamous `Sorry: This video is missing` even if the original video file is available.  This is the card I used [on this card](https://jid-staging.temp.build/#/site/learn/introduction-to-emergency-care/the-value-of-emergency-care:content:1)

I found out that the original [is present](https://admin.jid-staging.temp.build/media/media_transcodes/12-original-video.kogz5ldh.mp4) in the manifest but not being loaded on the card:

```
<videocard>
  <div>
    <p class="error-message">Sorry: This video is missing.</p>
    <h3 class="media-title">Udan Boot</h3>
    <p class="media-description">jgcvjt</p>
  </div>
</videocard>
```

And here's the media object in the manifest

```
{
    "id": "12",
    "type": "video",
    "renditions": {
        "original-video": {
            "path": "media_transcodes/12-original-video.kogz5ldh.mp4",
            "size": 5698246
        }
    }
}
```

@boerwastaken is already trying to figure out why the transcoding didn't work for this file but the original file should cover for this, no?

**Comment by PeteCoward** [comment]
OK, I've had a look, I think I have found the problem, working on a fix
