### ISSUE TITLE
New illustrations for KHS

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#764]
Hi @DanielHeads @megganeturner ,

We have new illustrations for the following screens:

1. Not quite — when you haven't scored high enough on the exam
2. Summary screen — when you review all your wrong answers after the exam
3. Retake exam — confirmation screen for when you're about to take the exam again

@DanielHeads — can you please attach the SVG files that @megganeturner will need in order to make this changes? _Graciarrr_

**These are the current Bero illustrations**
1 | 2 | 3
---|---|---
![Screen Shot 2021-06-08 at 12 02 59 PM](https://user-images.githubusercontent.com/2813677/122556482-7af94c80-d033-11eb-833d-2079e20c2bea.png) | ![Screen Shot 2021-06-08 at 12 03 09 PM](https://user-images.githubusercontent.com/2813677/122556454-6e74f400-d033-11eb-87d1-6332ab0b1ff3.png) | ![Screen Shot 2021-06-08 at 12 02 54 PM](https://user-images.githubusercontent.com/2813677/122556491-7e8cd380-d033-11eb-9a5e-4c435dbdc894.png)

**Comment by PeteCoward** [comment]
@DanielHeads  do you have the assets we can use for this?

**Comment by DanielHeads** [comment]
@PeteCoward I don't have the assets that are in this picture but I did another for Kumul Helt Skul I think that you are referring  this ones. 
[Not Quite](https://drive.google.com/open?id=1-n-Jszr7QbH0uBwIOYDJCd9SVDHVAkhX&authuser=daniel%40catalpa.io&usp=drive_fs)
[Review Exam](https://drive.google.com/open?id=1-qLLQBLk5Sxdi8wOwF56PDI9-xMYX1Ok&authuser=daniel%40catalpa.io&usp=drive_fs)
[Retake Exam](https://drive.google.com/open?id=1-nKt5AYZ-90VriRgcG7BlbBPsOAw4IrB&authuser=daniel%40catalpa.io&usp=drive_fs)
[Folder with all general images](https://drive.google.com/drive/folders/1-hQiiF0zKU6NCAgVVG6QLaNo5iCm5C5k)

**Comment by pedro16v** [comment]
Not the ones above! The ones to replace them! 😅 

@PeteCoward this should be it:

Review Exam | Retake Exam | Not Quite
--- | --- | ---
https://drive.google.com/file/d/1-qLLQBLk5Sxdi8wOwF56PDI9-xMYX1Ok/view | https://drive.google.com/file/d/1-nKt5AYZ-90VriRgcG7BlbBPsOAw4IrB/view | https://drive.google.com/file/d/1-n-Jszr7QbH0uBwIOYDJCd9SVDHVAkhX/view
