### ISSUE TITLE
User having trouble logging in

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#810]
From @andrewerbs 

User in Papua New Guinea has had trouble logging in from their personal Google pixel phone.

Using a Google pixel 5 with Android 11

**Comment by pedro16v** [comment]
@andrewerbs could you provide some more info such as:

- User's identity
- What sort of trouble did they find? (loading screen, error message?...)

**Comment by andrewcatalpa** [comment]
User is running Android 11 on their Pixel 5 phone.
