### ISSUE TITLE
KHS - Consent table on Metabase

### ISSUE THREAD

**Issue by Juliana-t** [catalpainternational/canoe#821]
As part of the M&E analysis, our partners requested us to include a question on the Pre-learning survey of Course 1 - Welcome of Emergency Department, to request learners to provide their consent. Find it here > https://kumulheltskul.com/#/site/learn/welcome:exam:1
We need a new table on Metabase with information on which answer each learner selected on this question.
Conditions of satisfaction
- [x] Table on metabase, contains the following info:
  - [x] Title: 'Research consent - ED module'
  - [x] User ID
    - [x] We will need to include user ID in other tables, so later the researcher doing the analysis can (on a spreasheet software, for example), exclude data from certain users (using the User ID) 
  - [x] Answer (yes / no)
  - [x] Answer from users with value 'Tester' or 'n/a' for the Healthcare Worker Role attribute, should be excluded from the list
  - [ ] Needs to be filterable by answers (e.g. I want to see only a list of users who said yes, or a list of users who said no)

**Comment by Juliana-t** [comment]
@PeteCoward @boerwastaken I prepared this issue for the Metabase table we discussed today. Please let me know if you need any further information

**Comment by boerwastaken** [comment]
please see https://stats.kumulheltskul.com/question/22

Notes:
- It doesn't work yet but will start working when catalpainternational/canoe-backend#227 is merged & deployed
- I havent excluded any particular roles, instead opted to simply add role information, filters via Metabase can do the rest.

**Comment by boerwastaken** [comment]
I've updated the Metabase query to include the question that the user was seeing at the time that they gave the answer. So it's safe to invert the question. The researchers will have to human-interpret question-answer-pairs to determine whether they constitute consent or not. It'll probably be obvious.
