### ISSUE TITLE
KHS - changes to existing Metabase questions

### ISSUE THREAD

**Issue by Juliana-t** [catalpainternational/canoe#822]
Conditions of satisfaction:
- [ ] All tables/questions include the User ID (for researches to be able to manually exclude data from certain users based on their ID and answer to the first question of the pre-learning survey)
- [ ] All tables/questions to exclude data from users with the values 'Tester' or 'n/a' on the Healthcare Worker Role attribute

**Comment by PeteCoward** [comment]
@boerwastaken I think juliana needs help with this as the questions are SQL, can you assist

**Comment by boerwastaken** [comment]
Certainly, I'm aware of this and I'll come around to this soon

**Comment by Juliana-t** [comment]
Can we exclude the 'tester' using a segment? Still I will need Wicher support to apply the segments on the SQL questions.
Now that we have a table informing which users provided consent (or not), we will need the user ID in other tables, so researchers/M&E team can exclude the usage data from those users based on their ID
