### ISSUE TITLE
Wagtail - Statistics

### ISSUE THREAD

**Issue by Juliana-t** [catalpainternational/canoe#823]
We have concerns about some of the user's private data that we are showing on Metabase (first name, last name and user name).
While certain admins of the system (kumulheltskul.com) will need to see what courses were complete by individual users or who completed a certain course, this information shouldn't be accessible to others that may be granted access to Metabase (e.g. researches working on the M&E).
One solution could be to keep the first data (who completed what, identifiable) on Wagtail, not showing it on Metabase. Having said that, on Metabase we will need to include user IDs (system IDs) for several proposes, in a way that can be crossed and people can not be identified by researchers, for example.
On Metabase we will also want to provide data per attributes and values, in order to disaggregate stats  for the research and analysis (e.g. number of users that are doctors at the ANGAU hospital that completed course X).
In parallel we need to:
- solve outstanding issues in the 'Reports' on Wagtail
OR
- agree on a way to have that information hidden on Metabase, and only accessible to a restricted group (is this a possibility? is it the best option?)

Some issues identified so far on Wagtail 'Reports' are:
- [LEARNING ACTIVITY BY USER ](https://admin.kumulheltskul.com/reports/learning)-> it is counting everytime a user completes a course (no matter if the course was already completed before), so for example, while we only have 10 courses so far on KHS, it says my user completed 84 courses), so this information is not accurate for the content managers/system admins
- [LEARNING ACTIVITY BY USER ](https://admin.kumulheltskul.com/reports/learning)-> I can see what courses were completed by each user (we will need to know exactly what courses were completed in order to do analysis such as 'Did user X completed all courses of our ED module?'
- [LEARNING ACTIVITY BY COURSE](https://admin.kumulheltskul.com/reports/courses) -> same issues as with the learning activity by user, it seems to count for everytime a user completes the course, AND I can't understand who are the learners who completed each course
- [LEARNING ACTIVITY BY COURSE](https://admin.kumulheltskul.com/reports/courses) -> also would be beneficial to have the option to filter by lesson / course / resource / category (once we have categories in here) in this page

**Comment by Juliana-t** [comment]
I need @PeteCoward and @boerwastaken to have a look at this. Please let me know if we need to discuss this further

**Comment by PeteCoward** [comment]
Some improvments up on https://admin.jid-staging.temp.build/

- users report entries now show unique number of courses and lessons complete
- users report rows links to new user report page
- user report has information on exam scores
- page reports users complete is distinct by user
- page reports rows links to new page report but it is empty

Some obvious items of work
- [ ] user report scores to percentages ( currently decimal 0-1 )
- [ ] user report timeline improvements
- [ ] page report implementation
- [ ] styling pass

Generally getting feedback for what people who view these reports want to use them for would be great

**Comment by Juliana-t** [comment]
I agree with Peter

to start, I would recommend @sandroroux that you could have look at:
- user report scores to percentages ( currently decimal 0-1 )
- page report implementation, when clicking on them (like Peter did for the users report) https://admin.jid-staging.temp.build/reports/pages to open the detail of that page: which users completed it, when, with what score (for courses, in case there is an exam)
this second is one of the initial reports our partners are looking for

**Comment by Juliana-t** [comment]
This issue is being detailed and expanded as part of Release 4
I suggest we close this issue and add new ones (from the design document of Release 4), with further details per report to follow up this work
@PeteCoward @sandroroux let me know if you agree
