### ISSUE TITLE
Poke Appelflap API to set language

### ISSUE THREAD

**Issue by boerwastaken** [catalpainternational/canoe#826]
With catalpainternational/appelflap#102 the webapp can set the language that the (sparse, but present) Appelflap UI elements are presented in. There are just a few of them, but it would be nice if users would see them in their own language.

Currently enabled (but not yet translated) are `en`, `bi`, `pis` and `sm` with `en` being the default.

Canoe-web should poke Canoe-android via its HTTP API to set the Android language in sync with the webapp language.

The Appelflap side of this equation is complete, [documentation here](https://github.com/catalpainternational/appelflap/blob/c4138be88a490efe080049116b0ee01b549f258b/docs/API/settings.md#ui-language#ui-language).

**Comment by PeteCoward** [comment]
not a prioritytight now, single language deployments only
