### ISSUE TITLE
Bero via PeP – Discussion Tab Affordance

### ISSUE THREAD

**Issue by andrewwapling** [catalpainternational/canoe#849]
**Overview**
Through user testing of the Bero platform via the PeP deployment conducted by @KaraChesal some users didn't see the or understand the Discussion tab located within the course detail screen.

**Job to be done**
Explore UX / UI solutions to help boost discoverability and understanding of the Discussion tab.

**Comment by andrewwapling** [comment]
Hi @KaraChesal @Juliana-t @pedro16v please see below proposed solution to boost discussion tab affordance. Rather than move back through a visual redesign process for the tab itself I would suggest some educational onboarding to help with discoverability could be a more beneficial approach. 

This approach is in line with the guiding hand principle of Bero with the underlying proposition that once a user has used the social learning aspect once and understands the pattern, they will moving forward be able to return to this whenever they desire. I believe this behavioural approach could be more meaningful than re-skinning the tab itself.

I propose two key opportunities for this as follows:

1. Inline onboarding tooltip that highlights the function in context of the screen and is user dismissable: https://projects.invisionapp.com/share/52Y02L9YTRF#/455859748_Course_Detail_-_Discussion_Onboarding

2. Confirmation screen call to actions x3: 
• Lesson Complete Confirmation: https://projects.invisionapp.com/share/52Y02L9YTRF#/453511208_Confirmation_-_Success_Lesson
• Course Complete Confirmation: https://projects.invisionapp.com/share/52Y02L9YTRF#/453511209_Confirmation_-_Success_Course
• Course Complete Commence Exam Confirmation: https://projects.invisionapp.com/share/52Y02L9YTRF#/455577687_Confirmation_-_Success_Last_Lesson

Kindly review and let me know your thoughts.

**Comment by Juliana-t** [comment]
1. Great, I really like the solution on point 1. It can be used for the offline/download and for a couple more cases where users need some tips to get started with a feature.
By the way, on KHS, in order to help with the on-boarding (while we don't have an on-boarding feature), we include an initial lesson on the first course of each module, where we tell learners what the module is about and how they will learn using Kumul Helt Skul. We have one card where we explain the core navigation menu, one to explain the discussion feature, one for the offiline, ... Just to say, we take a similar design approach to solve it.
2. Already implemented and in core Bero (no exactly with that hierarchy of CTA buttons, but the 'join the discussion' is there on those screens

**Comment by pedro16v** [comment]
Point 1 looks great.

@andrewwapling — is point 2 the same as the discussion happening on #753

**Comment by andrewwapling** [comment]
Hi @Juliana-t @pedro16v thanks for your feedback and glad you like.

1. Yes, I agree this approach is really flexible and adaptable. It would be a really intuitive way to highlight a wide range of features to users and boost affordance of existing features if deemed necessary

2. Yes, in answer to your question @pedro16v it's the same pattern i.e. confirmation screen. I feel these confirmation screens have a lot of power in terms of helping users understand and discover new pathways or next best actions from existing flows. They are also in essence educational and can promote behaviour change by delivering users to certain sections, new flows or particular content. Once a user has accessed the social learning once or perhaps twice this will help in recognition. Further to this once we have notifications integrated i.e. 'Mary replied to your comment in Lesson Name' CTA: View Discussion etc. this will also help boost front of mind and engagement with this functionality

**Comment by pedro16v** [comment]
The first part of this work has been assigned to issue #972
