### ISSUE TITLE
Sync - Set Manifest sharing versions appropriately

### ISSUE THREAD

**Issue by md8n** [catalpainternational/canoe#866]
# Description

The manifest is the key document for Bero's operation.

For its synchronisation it needs the minimum version numbers set just right.  This is assuming that Bero already has a manifest.

- `p2p_version_min` (part of identifying the version being shared with peers) should be set to the manifest's current version.
- `injection_version_min` (part of identifying the range of version values being subscribed to) should be set to the manifest's current version + 1.

**Comment by boerwastaken** [comment]
This last changed with #958.
Is further rumination required or can we close this here issue?

**Comment by PeteCoward** [comment]
@md8n can we close this? If not we should transfer to bero repo

**Comment by md8n** [comment]
@PeteCoward Yes - we can close this
