### ISSUE TITLE
Bero Wagtail Data Usage Report Design Recommendations

### ISSUE THREAD

**Issue by andrewwapling** [catalpainternational/canoe#871]
**Overview**
In line with @PeteCoward's work to integrate usage data and reporting for Bero in the WagTail CMS, there has arisen a need for design recommendations for how best display these insights. There is also an opportunity to uplift standard screen furniture such as header, search or filter, table, in some a timeline. 

**What needs to be solved**
For these design enhancements to commence and be measurable and effective we require use cases and user stories to be defined to ensure we're designing for peoples needs and communicating data effectively for different users needs. Ping @Juliana-t @pedro16v

**Comment by pedro16v** [comment]
I'm a bit on the dark with this one. Need @Juliana-t to step in 😁

**Comment by Juliana-t** [comment]
@andrewwapling reports and data is being defined on the design doc for release 4
Reference - https://docs.google.com/document/d/1KlyfxkXCzYujUm5CAcTeP40ktUvD91WuSvhvD6JPzQ4/edit#heading=h.ttwzm93en126
We will get to the get back to this issue when we have reports defined and implemented, in order to understand opportunities for design to improve the data analysis experience
(will be on hold for now)

**Comment by andrewwapling** [comment]
No worries thanks for the update here @Juliana-t :)

**Comment by PeteCoward** [comment]
@Juliana-t can we close this?

**Comment by andrewwapling** [comment]
@Juliana-t would you like any design action on this one? Or is it still considered a backlog task?

**Comment by Juliana-t** [comment]
Backlog for now - especially as Peter is testing Metabase embed options.
Metabase has a pretty standard style and I don't think we will be able to
change much, apart from organization of the page elements and sizes/some
margins.
Depending on if we decide to keep some Wagtail reports (lists of learners
or pages), we may need later on to review the style a little bit to make it
easier to read. But this second part if on the backlog for now

**Comment by andrewwapling** [comment]
Hi @Juliana-t no worries, thanks for confirming with me.
