### ISSUE TITLE
Sync - Check on `isPublishable` status of 'parent' pages

### ISSUE THREAD

**Issue by md8n** [catalpainternational/canoe#873]
# Description

Syncing requires a few different statuses to tell it whether it can 'publish' (i.e. share) a page, and whether the page is available offline.  These are related ideas, but different in their purpose.

Somewhere along the way it seems that Publishable got confused. 
The result of this is that 'parent' pages may be complete (in terms of what's cached), but won't get shared, because we don't have all of their descendent pages.

**Comment by PeteCoward** [comment]
What is the status of this @md8n ?

**Comment by md8n** [comment]
@PeteCoward This can be closed because it was dealt with (indirectly) via other issues / PRs
