### ISSUE TITLE
The return of incorrect completions

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#878]
## Overview
This was reported by someone using Kumul Helt Skul in PNG.

> I’m trying to figure out what’s happening on KHS when viewing whether courses are complete. I’ve attached screenshots from a user who dropped by this morning. 
> 
> In her profile it looks like she has 13 lessons remaining, but when you go through every course and exam she has done them all. They appear complete on her profile section, but the bar appears not quite complete in the courses section. When you click on the courses, all lessons are ticked off as complete. 

## Resources
| Profile shows Courses are complete | Course listing shows Courses incomplete | 
|-|-|
![image1](https://user-images.githubusercontent.com/2813677/126974392-a8fb7043-e58c-4242-ae99-92c70e99a632.jpeg) | ![image2](https://user-images.githubusercontent.com/2813677/126974406-a9d4387c-7287-42c5-b6c6-51ba349df33d.jpeg)

| What the profile says | All lessons completed (exam?) |
|-|-|
![image0](https://user-images.githubusercontent.com/2813677/126974378-20c44b6c-6e2d-41e5-adfb-31e4b794b37d.jpeg)  | ![image3](https://user-images.githubusercontent.com/2813677/126974417-da0e85ee-7cec-4b91-a8f2-261d503d3be6.jpeg)

**Comment by pedro16v** [comment]
I took a look at my own account and found this:

* 11 lessons completed vs 4 reported
* 31 courses remaining vs 40 reported
* 1 course without a complete exam shows as completed and goes to the bottom of the course listing


A — Incomplete course showing at bottom of list
B — Incomplete course showing in Profile page

| A | B |
| - | - | 
<img width="376" alt="Screenshot 2021-07-26 at 11 50 33" src="https://user-images.githubusercontent.com/2813677/126978574-85bd6036-8064-495b-9d50-d2d9a5bd92e1.png"> | <img width="375" alt="Screenshot 2021-07-26 at 11 51 53" src="https://user-images.githubusercontent.com/2813677/126978566-05c87494-9e0c-462a-8c6a-aa83cfd36cad.png">

| C | D |


<img width="375" alt="Screenshot 2021-07-26 at 11 51 50" src="https://user-images.githubusercontent.com/2813677/126978568-27b98575-7b66-4f7f-99b1-4acec23acfb5.png">
<img width="375" alt="Screenshot 2021-07-26 at 11 51 04" src="https://user-images.githubusercontent.com/2813677/126978570-70269a04-2db8-4227-9c37-0a421b2e44f7.png">


<img width="375" alt="Screenshot 2021-07-26 at 11 52 11" src="https://user-images.githubusercontent.com/2813677/126978561-386f50c6-f377-4489-b375-7b5cea1a4e27.png">

**Comment by PeteCoward** [comment]
Hmm, so this comes down to design and implementation confusion about what counts as a lesson :)
The implementation is currently wrong, but there is a question about what is right...

Should 'lessons completed', and 'lessons remaining' include exams as lessons?

Should we also display 'courses completed' and 'courses remaining'?
Should we also display 'exams completed' and 'exams remaining'?

**Comment by PeteCoward** [comment]
I can easily do something like this ( using Pedro's account )
<img width="280" alt="Screenshot 2021-07-28 at 17 31 39" src="https://user-images.githubusercontent.com/1092029/127290920-f088b677-c4b6-4dbf-907c-e15330dfd5ef.png">

**Comment by PeteCoward** [comment]
will look into the other part (course without completed exam showing as complete) tomorrow

**Comment by Juliana-t** [comment]
@PeteCoward your approach is correct
Lessons should mean lessons (no exams counted on that stat)
Courses are courses, and it's completion is considered when:
1 - all lessons in a course are completed (when there is no exam in the courses)
2 - all lessons in a course are completed + user passed the exam (when there is an exam in the course)

**Comment by pedro16v** [comment]
Agreed with the above, regarding exams not counting towards lesson count.

Adding courses to stats seems useful but I would run that through design. There is an argument for grouping information. Something like:
* 2 courses completed (11 lessons)
* 10 courses remaining (36 lessons)

**Comment by pedro16v** [comment]
> Agreed with the above, regarding exams not counting towards lesson count.
> 
> Adding courses to stats seems useful but I would run that through design. There is an argument for grouping information. Something like:
> 
> * 2 courses completed (11 lessons)
> * 10 courses remaining (36 lessons)

I forgot to ping @andrewwapling on this one!

When I said there was an argument for grouping information I meant to have Andy drop in his thoughts. I think duplicating squares might be a bit clonky. I might also be wrong and it looks just fine 😃

**Comment by andrewwapling** [comment]
Hi @pedro16v thanks for looping me in on this one. I agree that exams shouldn't count as lessons. I also like the idea of displaying remaining as it inherently communicates the idea of progression to a learner.

I do think we could display all of this content in a much more succinct and economical way that doesn't replicate the existing boxes and icons. The duplication invades a lot of space and could be a visually verbose.

I'll look at a fresh take on this based on the above discussions and post back soon :)

**Comment by pedro16v** [comment]
Completions are now correct. I'll create a new issue for the visual review.

**Comment by PeteCoward** [comment]
So you have actually completed the pre-learning survey, and ED Course 8, but the progress bars were not respecting this.
Fix is in pr https://github.com/catalpainternational/canoe-backend/pull/244

**Comment by andrewwapling** [comment]
Hi @pedro16v @PeteCoward please see refined design direction based on the above insights adjustments:

https://invis.io/52Y02L9YTRF#/456497854_Profile_-_Settings_Alt_Insights

Have basically updated the icons to link to notion of courses and lessons, removed the additional remaining boxes and added the remaining as a countdown figure within the completed boxes to give a sense of progression, whilst minimising vertical height and scroll.

Kindly review and let me know if you're happy with this approach.

**Comment by Juliana-t** [comment]
This looks great @andrewwapling 
On the mockups for PeP profile, did we had the 'learning topics' 'learning activities' stats as well? If so, we will need the design for it

**Comment by pedro16v** [comment]
> This looks great @andrewwapling

Agreed! I'll open a new issue for engineering to tackle this!


> On the mockups for PeP profile, did we had the 'learning topics' 'learning activities' stats as well? If so, we will need the design for it

@Juliana-t  — No. PeP never had it. 

Might be worth reviewing that in a next release as PeP can now also have courses. Also, the teaching component might eventually need it. 

I would hold any design work on that until we brainstorm a bit about what needs to change in there.

**Comment by andrewwapling** [comment]
Sounds good @pedro16v @Juliana-t – we could even tackle this one as part of the profile design uplift for Release 4 :)
