### ISSUE TITLE
M&E data - create reports for Kumul Helt Skul

### ISSUE THREAD

**Issue by Juliana-t** [catalpainternational/canoe#895]
Although we do have a number of reports on Metabase, our partners are asking for specific tables in order for them to perform an initial analysis of the data. All this reports were initially described on issue #473 but not all have been addressed (at least on Metabase).

We need 5 new reports:
- [x] Report 1 - Staff enrolled who completed - done https://stats.kumulheltskul.com/question/2-course-completion-log
- [ ] Report 2 - Pre-learning survey results (finds more info on comments)
- [x] Report 3 - Number of staff that completed each lesson  (finds more info on comments)
- [ ] Report 4 - Number of ED staff that completed each lesson 
- [x] Report 5 - lessons feedback

The design for each report and conditions of satisfaction can be found here:
[Reports for Kumul Helt Skul](https://docs.google.com/spreadsheets/d/1-C6gT0wujefNzliOOv_0Q1uoUCU6u8IEGWNc2PSNN_U/edit?usp=sharing)

**Comment by Juliana-t** [comment]
@boerwastaken is having a look at the existing tables and will provide directions in this issue

**Comment by Juliana-t** [comment]
For report 2
@boerwastaken 's recommendation:

> use the exam_useranswer_evaluation table as a base (contains all user's answers to all questions) and roll from there.  see also https://github.com/catalpainternational/canoe/issues/870#issuecomment-886605230

**Comment by Juliana-t** [comment]
For report 3 Wicher made [this](https://stats.kumulheltskul.com/question/25-a-base-for-report-3)

**Comment by boerwastaken** [comment]
For report 5 there's https://stats.kumulheltskul.com/question/39-sentiment-log on which can be befiltered and beaggregated.

**Comment by boerwastaken** [comment]
isn't report 3 easily based on https://stats.kumulheltskul.com/question/2-course-completion-log , but for lessons instead of courses (which is also easily inspired by that same question - just substituting `ez_courseitem` for `ez_course`)?

**Comment by Juliana-t** [comment]
@andrewerbs @jbunefa you may also want to have a look at this issue and comments as Wicher prepared some tables to enable the creation of the reports

**Comment by jbunefa** [comment]
I will be looking at this and wil get back to you @Juliana-t

**Comment by jbunefa** [comment]
Did report 3 https://stats.kumulheltskul.com/question/93-report-3-number-of-staff-that-completed-each-lesson
Did a manual count by exporting to excell and did a manual count on few selected lessons and seems correct.

**Comment by Juliana-t** [comment]
Thanks @jbunefa just thinking that it may be helpful to add another column for the 'Course title' so you can easily understand to which course each lesson belongs too. You should be able to join that info. Another thing that could bring value, would be to add 2 more reports based on this - one just counting lesson completion for ANGAU users and one for PMGH users. Do you think this will be helpful to Sarah B and the ACEM team?
Also just to confirm, are we excluding testers on that counting right? We are just interested in completion of 'real' users

**Comment by boerwastaken** [comment]
As it appears you can complete a lesson multiple times (yes! first time it's complete, second time it's completer, third time it's even completerer! :clown_face: ), @jbunefa I think you're double- (and triple-, quad-, ...) counting completions in https://stats.kumulheltskul.com/question/93-report-3-number-of-staff-that-completed-each-lesson .
Likely you'll want to filter on the `seq` (= "sequence") column's value being exactly `1`, that is, you'll want to count only the *first* time someone completes a lesson.

**Comment by jbunefa** [comment]
Yes @Juliana Teixeira ***@***.***> , this will be really helpful as
we would like to know how many staff from Port Moresby General Hospital
(PMGH) completed lessons and also from ANGAU Memorial Hospital complete.
Will do that
*Joe Bunefa*
Catalpa International
*m:* +675 71573839 /76876175 /78080858
*e:* ***@***.***
*w: *www.catalpa.io

**Comment by jbunefa** [comment]
Thanks and will have a look at that by filtering by seq. its the count on
all lessons completed so a staff can complete multiple lessons 1 for the
different courses etc
*Joe Bunefa*
Catalpa International
*m:* +675 71573839 /76876175 /78080858
*e:* ***@***.***
*w: *www.catalpa.io
