### ISSUE TITLE
Handling only one category

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#906]
Stripped from #622

Works as expected... however!... **We need a better way to handle cases where there's no categories**. The current solution adds too much entropy. I have sketches!

@andrewwapling @Juliana-t @PeteCoward 

## The current state

If no categories exist, we end up showing the same exact content in 3 different screens. The only difference is that when reaching the actual course listing, courses are not on an horizontal carousel. It only makes sense when it allows users to take a quick look at courses from different categories.

<img width="1032" alt="Screenshot 2021-07-30 at 14 19 34" src="https://user-images.githubusercontent.com/2813677/127659296-4ee52781-ba15-4b86-9fb6-5d6a0451c030.png">

## A suggested solution

If possible, in the case where no categories have been set, we could have the app jump directly to the course listing, saving users a confusing step.

<img width="1025" alt="Screenshot 2021-07-30 at 14 19 43" src="https://user-images.githubusercontent.com/2813677/127660038-c90263e6-14a0-49d9-afef-d035895fab96.png">

## Comparing the two 

What will people be looking at? Notice how content is always the same for `Situation A`

| - | Home Page (courses section) | Category listing | Course listing | 
| - | - | - | - | 
| Situation A | A preview of all available courses, sorted by date, completion, etc | A preview of all available courses, sorted by date, completion, etc | All available courses, sorted by date, completion, etc
| Situation B | A diverse number of courses, from all categories, sorted by date, completion, etc | A preview of the latest/ongoing courses from each category, sorted by date, completion, etc | All available courses, sorted by date, completion, etc |

**Comment by pedro16v** [comment]
Oh! I see you addressed my suggestion @megganeturner. I was hoping to get some insights from @andrewwapling first but hopefully he's happy with this solution 😁

**Comment by Juliana-t** [comment]
I agree with this solution! Andy, what do you think?

**Comment by andrewwapling** [comment]
Hi @pedro16v @megganeturner @Juliana-t yes I'm in agreeance if there are no categories for a Bero deployment then we should display an overall card listing layout. 

Please see design recommendation from #622 @902 below for reference:

> If a Bero deployment isn't utilising any categories I would recommend utilising the screen design below which basically lists all courses as cards. This version contains a continue learning component at the top of the listing which is there to help learners jump back into courses that they may have started though not yet completed. The search and tag filtering is persistent as per other course listing screens.
> 
> https://invis.io/8911I5TDCQ5S

**Comment by andrewwapling** [comment]
Hi @megganeturner just checking where's the best place to view the implementation? Can you please share the direct link? :)

**Comment by pedro16v** [comment]
> Hi @megganeturner just checking where's the best place to view the implementation? Can you please share the direct link? :)

That should be https://jid-staging.temp.build/#courses but it's currently configured with multiple categories. It's on my plans to test it today by adding and removing categories. I can attach screenshots here if that's helpful.

**Comment by andrewwapling** [comment]
Thanks @pedro16v – let me know if you require support reviewing this one.

**Comment by pedro16v** [comment]
Hi @andrewwapling here's a summary of what you can see in both situations — one vs multiple categories.

## One Category

Notes:
* Navigation remains exactly as it was before
* Courses header link navigates to **(2)**
* Courses nav link navigates to **(2)**

| (1) Home | (2) Course listing | 
| - | - |
<img width="375" alt="Screenshot 2021-08-09 at 12 46 56" src="https://user-images.githubusercontent.com/2813677/128702053-57914ceb-0990-4b77-9e55-a7b15405a302.png"> | <img width="375" alt="Screenshot 2021-08-09 at 12 47 06" src="https://user-images.githubusercontent.com/2813677/128702049-8ce06297-d4d5-4f9f-bce4-97d6d452fc92.png">

## Multiple categories

Notes:
* Homepage now shows categories. 
  * Course categories link navigates to **(2)**
  * Category links navigate to **(3)**
* Category header link navigates to **(3)**
* Courses nav link navigates to **(2)**

| (1) Home | (2) Course category listing | (3) Course listing |
| - | - | - |
<img width="375" alt="Screenshot 2021-08-09 at 12 49 06" src="https://user-images.githubusercontent.com/2813677/128702512-ef9e7a81-1d20-4495-9041-bf5f4d94887b.png"> | <img width="375" alt="Screenshot 2021-08-09 at 12 49 53" src="https://user-images.githubusercontent.com/2813677/128702503-8abf6635-0f32-4c22-a69c-a71f050aee81.png"> | <img width="375" alt="Screenshot 2021-08-09 at 12 49 57" src="https://user-images.githubusercontent.com/2813677/128702486-1255d2ce-f705-41ab-9681-fac245a46e43.png">

**Comment by andrewwapling** [comment]
Hi @pedro16v thanks for documenting this. All looks good except two items to flag.

1. On the all courses version the 'All Courses' section header doesn't match the uppercase style. Also if we are purely listing all courses without the 'Continue Learning' component I believe it negates the need for the 'All Courses' section header. If we are adding the 'Continue Learning' component it makes sense as it creates consistent wayfinding within the screen.

2. There are some inconsistencies with the way 'Course Categories' are functioning within the design direction. The idea here was to not include an arrow for 'Course Categories' section header and instead navigate users to the full text based listing of categories via the secondary CTA button 'View all course categories' below the truncated list of x6 first categories. Please see design references for review:

• Home page (note no arrow on 'Course Categories' section and secondary CTA button 'View all course categories' below truncated list of text based category listing) – https://invis.io/52Y02L9YTRF#/454482332_Home_-_New_MVP 

• Category listing (text based) – https://invis.io/52Y02L9YTRF#/456556736_Course_Categories_-_No_Filter

Kindly review and let me know your thoughts here?

**Comment by pedro16v** [comment]
Hi @andrewwapling, here's a few notes.

1. I believe all your concerns [have been addressed](https://github.com/catalpainternational/canoe/issues/622#issuecomment-895741188). Here's how it's looking now:

![Screenshot 2021-08-19 at 12 09 27](https://user-images.githubusercontent.com/2813677/130058937-0f411e09-b7ea-47ea-8eec-f6b2df6637cf.png)

2. For this one, we're fixing a few details already on #939. We're leaving the `show more` logic for later as we have a reduced number of categories at the moment anyway. We should address the full behaviour in a next release to ensure that Bero is compatible with future implementations. I believe @Juliana-t wants to discuss it further. Let's do it then.

**Comment by pedro16v** [comment]
I think the short term solution for handling categories has been solved. 

@andrewwapling  — I have noted the need to go over your latest ideas and recommendations. To discuss in the near future with @Juliana-t .

**Comment by andrewwapling** [comment]
Great thanks @pedro16v @Juliana-t

**Comment by andrewwapling** [comment]
@pedro16v @Juliana-t let me know if you'd like to discuss the home page banner concepts above at some point?
