### ISSUE TITLE
Brand ACIAR Learn

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#920]
This is to create the branding assets

## Conditions of satisfaction
- [x] Follow the branding guide for ACIAR Learn - app screens and illustrations/images according to Bero customization guidelines

## Notes
* Assets to be developed and provided by ACIAR Learn team

**Comment by Juliana-t** [comment]
Sarah Narayan is working on the assets (sorry, for some reason can't tag you here!), @andrewwapling @megganeturner can you provide some support to Sarah on getting those assets for customization of Bero for ACIAR?

**Comment by sarahnarayan** [comment]
hellooo everyone. I've followed a list on theming & have some of these things ready. What do I do next?

**Comment by megganeturner** [comment]
Hi @sarahnarayan 😊  Can you please upload the assets to a folder in Google Drive and link it here?

I've found the equivalent file path in the JID Team Drive (is there a shared drive for ACIAR? Can you please share it with me so I can get these assets?) & it's under 09. Graphic Design - specifically within the `Assets for Bero` & `Logo` folders. The logo folder contains the icons & favicons, and the Assets for Bero folder contains all of the other customised images as defined in the [Wiki for Theming](https://github.com/catalpainternational/canoe/wiki/Canoe-knowledge-base#theming).

Can you also please let us know what the theme colour for ACIAR is? 😊 

Let me know if you have any questions or if anything here is unclear!

![Screen Shot 2021-08-23 at 2 45 06 pm](https://user-images.githubusercontent.com/12974326/130391205-cb41af57-fc73-42e5-8515-a3da0e060a62.png)

**Comment by sarahnarayan** [comment]
Hi @megganeturner. Thank you. I've asked Sarah T to add you onto the ACIAR Learn shared drive. (It doesn't allow me to add)  In the folder there is also a style guide. Please let me know if the items in the logo folder are correct? 

Theme colour: 

RGB 101 141 27
HEX/HTML 658D1B

**Comment by andrewwapling** [comment]
Hi @sarahnarayan @megganeturner I'm getting onto this one a bit late though just checking do you need any design support on this one? Or did you manage to hand over everything you needed to @megganeturner @sarahnarayan? Happy to help so please let me know if I can help with anything :)
