### ISSUE TITLE
I see my personal details on the Profile page

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#921]
## Overview
After logging in, users don't have a way of knowing which account they're logged into. Showing some basic user information would personalise their experience.

## Conditions of satisfaction
* On the profile screen, I can see:
  - [x] My name
  - [x] A placeholder avatar (the same generated for discussions)

## Resources
* Check on [InVision](https://projects.invisionapp.com/d/main?origin=v7#/console/20251865/429853514/preview?scrollOffset=2296)

<img width="320" alt="Screenshot 2021-08-06 at 13 44 47" src="https://user-images.githubusercontent.com/2813677/128512352-afe8cacd-ad78-4f2f-800a-e681ae00740a.png">

**Comment by pedro16v** [comment]
Profile and settings wireframes from @Juliana-t for @andrewwapling 's reference: https://docs.google.com/presentation/d/1LetV2rQ1Xwr8hfDBVt2m-A3yeHoldp6CGqWUQG_wF1U/edit

**Comment by andrewwapling** [comment]
@pedro16v @megganeturner  great to see the avatar element making it in! Really helps weight this section. A few small visual issues I can see immediately that I recommend refining include:

• The page title in the top nav bar is too big, please reduce and match design
• The Avatar circle is too small
• The Avatar initials are too large
• The name font weight looks a bit heavy
• The padding seems slightly off

Let's check these elements and try and match balance achieved in the design: https://invis.io/UQ11IZOWD8M2
