### ISSUE TITLE
I have the option to change my password from the Profile page

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#922]
## Overview
Users are able to change their password from within the app. The typical scenario is that a user has access to the current password but wishes to change it anyway. The process forces the user to enter the old password first, and then pick a new one. In cases where the user doesn’t know their password, they need to recover it (separate user story)

## Conditions of satisfaction
- [ ] There is an option to change my password
  - User will need to:
      - Enter current password
      - Enter a new password
      - Confirm new password

### Design resources
[Update your password screen](https://projects.invisionapp.com/d/main#/console/21435394/456691959/preview)
[Validation alert](https://projects.invisionapp.com/d/main#/console/21435394/456691960/preview)
[Change password active state](https://projects.invisionapp.com/d/main#/console/21435394/456691961/preview)
[Password changed - success message](https://projects.invisionapp.com/d/main#/console/21435394/456691962/preview)

**Comment by andrewwapling** [comment]
Hi @pedro16v as promised please see design direction below:

• Settings screen with change password tile (accessed via settings icon on profile page) – https://invis.io/MD113620ZJS6#/453258684_Settings
• Unfilled state – https://invis.io/MD113620ZJS6#/456691959_Settings_-_Password
• Validation state – https://invis.io/MD113620ZJS6#/456691960_Settings_-_Password_Validate
• Filled state – https://invis.io/MD113620ZJS6#/456691961_Settings_-_Password_Completed
• Success confirmation (modal roll up) – https://invis.io/MD113620ZJS6#/456691962_Settings_-_Password_Success

Kindly review and let me know if you're happy with this approach or if you have any queries at all. Thanks again, Andy

**Comment by Juliana-t** [comment]
@andrewwapling just wondering how this will fit in the broader profile/settings redesign work. Looking at the 'settings screen' I am not sure how it will suit the needs on Kumul Helt Skul, would work for PeP as it is i believe. Anyway, other screens and feedback looks great

**Comment by pedro16v** [comment]
Good point. For reference, this is the latest implementation of the Profile on KHS (staging). Please ignore the artefacts around clickable elements.

![Kumul Helt Skul - Profile](https://user-images.githubusercontent.com/2813677/128845754-ff8ecd1e-cd89-4b80-80fb-49fe6177a70d.png)

**Comment by andrewwapling** [comment]
Hi @pedro16v @Juliana-t I would recommend all instances of Bero following the same pattern for profile and settings. I can't see any issues with this pattern being applied effectively for KHS, PeP or any other implementation unless I'm missing something? 

The magic of this pattern is that it can easily scale up or down depending upon what we'd like to show. For example we can show more or less information to users on the profile screen depending upon deployment requirements: https://invis.io/XQ11IZNFNMTZ

Likewise the settings screen screen is designed in a modular way with tiles that allows additional sub sections to be added or removed depending upon relevance: https://invis.io/VW11IZNPD4UF

The screenshot you posted above fits in perfectly with this approach i.e. settings screen is access via cog, change password is accessed via the change password tile. If this element isn't required or relevant we can hide it from view.

**Comment by andrewwapling** [comment]
@pedro16v great to see the avatar element making it in! Really helps weight this section. A few visual issues I can see immediately include:

• The page title in the top nav bar is too big, please reduce and match design
• The Avatar circle is too small
• The Avatar initials are too large
• The name font weight looks a bit heavy
• The padding seems slightly off

Let's check these elements and try and match balance achieved in the design: https://invis.io/UQ11IZOWD8M2

**Comment by Juliana-t** [comment]
Looks good to me, having those links on the setting page to change password screen / sync screen / (whatever we may include in the feature screen - example language or notifications on/off)
On the avatar and user name, @pedro16v would you mind moving Andy's feedback to the issue where this is being tracked with Meggan? Thanks!

**Comment by andrewwapling** [comment]
Ok great thanks for confirming @Juliana-t – yes I believe this format for settings will be very effective to scale and customise. Sounds good re: Avatar issue, let me know if you require any additional detail on this one at this stage.

**Comment by pedro16v** [comment]
Copying @andrewwapling 's comment which had been posted in #615 

Hi @Juliana-t @pedro16v as promised I've created updated designs directions for the profile and settings screens for both logged and non logged users. Please see details below:

1. Full linked prototype: https://invis.io/MD113620ZJS6
2A. Profile (logged in users): https://invis.io/PT11JI08YUG5
2B. Profile (non logged users): https://invis.io/KS11JI0BDZ3U
3A. Settings (logged users): https://invis.io/VW11IZNPD4UF
3B. Settings (non logged users): https://invis.io/7K11JI0CTHSZ
4. Settings - General: https://invis.io/J511JI0DVN9G
5. Settings - Change Password Flow: https://invis.io/YJ11JI0HZ4H7
6. Top Push Down Notification for Non Logged users: https://invis.io/V411JI0JRBCZ
7. Global Toast Notification for Auto-Syncing concept: https://invis.io/HQ11JI0MPTNW

Kindly review and let me know your thoughts, feedback and any queries at all.

**Comment by pedro16v** [comment]
**In a nutshell:**
* Ignore the notifications component (for now) as well as `Offline sync` and `Advanced settings`
* Setting cog icon now opens a PeP-style settings screen
* Old settings go to `General settings` (like in PeP)
* A `Change password` option is added
* 


| A | B | C |
| - | - | - |
<img width="320" alt="Screenshot 2021-08-13 at 14 24 08" src="https://user-images.githubusercontent.com/2813677/129364236-e1745a02-6b6b-46c8-b6f3-7d505f4ed177.png"> | <img width="320" alt="Screenshot 2021-08-13 at 14 25 09" src="https://user-images.githubusercontent.com/2813677/129364233-10441852-3184-4652-81a8-456473814d11.png"> | <img width="320" alt="Screenshot 2021-08-13 at 14 25 15" src="https://user-images.githubusercontent.com/2813677/129364226-db282e8e-143e-4baa-b759-77254ffe4a8c.png">
<img width="320" alt="Screenshot 2021-08-13 at 14 24 35" src="https://user-images.githubusercontent.com/2813677/129364479-eca8a44f-603f-4d87-bb82-9cc701a83d33.png">| .| .
<img width="320" alt="Screenshot 2021-08-13 at 14 24 50" src="https://user-images.githubusercontent.com/2813677/129364526-118796e2-4229-4c1c-9697-6e8bf1f39375.png">|.|.

**Comment by Juliana-t** [comment]
Also adding PeP statistics (teaching topics and teaching activities) on the
stats component of the screen

**Comment by pedro16v** [comment]
> Also adding PeP statistics (teaching topics and teaching activities) on the stats component of the screen
> […](#)

Some data is already available on PeP staging.

@megganeturner please also check #965 before starting this.

**Comment by joanico** [comment]
It seems Ok
