### ISSUE TITLE
I can recover my password using my email

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#923]
## Overview
Although many users don't use an email account or often lose access to it, we should provide password recovery via email for the ones that can access it.

## Conditions of satisfaction
- [ ] On the login screen, I can select to recover my password via email
- [ ] User can enter their email or username and click on 'Request password reset'
- [ ] The app will inform me that "We've sent you a password reset email". "Check your email and click on the link to follow the password reset process."
- [ ] An email will be sent to the user's email, with a link to reset password
- [ ] Clicking on that link, the user will be able to visit a page where thet can set a new password and confirm my new password
  - [ ] Bero's password validation check is done
- [ ] Once the new password is setup, the user seems a success roll over and a button to login with their new password

## Resources
New Bero Login & Account Creation prototype here: https://invis.io/DE11PTCZYKN8
The forgot password section is also here: https://invis.io/5B121PW84AE3

**Comment by andrewwapling** [comment]
Hi @pedro16v @Juliana-t  as promised I've been working away on the password recovery flow for email (and mobile aka 'try another way').

Kindly review the linked prototype below and let me know if you're happy with this approach or if you have any feedback or queries at all.

Main prototype link: https://invis.io/9211LB9FXNAC

===

Screen breakdown:

**Login**
1. Login screen - users tap the 'Forgot password?' link to initiate the flow: https://invis.io/E211LBDOFASY

**Email Recovery**
1a. Account recovery via email screen (unfilled state): https://invis.io/TQ11LBDWZJ6V
1b. Account recovery via email screen (filled state): https://invis.io/TQ11LBDWZJ6V
2a. Recovery email sent confirmation screen: https://invis.io/GF11LBEBP7J3
2b. Recovery email sent again confirmation screen: https://invis.io/5311LBEF9BPW
3. Email template design with auto-generated reset password CTA link: https://invis.io/CD11LBEI9N6V

**Mobile Recovery**
1a. Account recovery via mobile screen (unfilled state): https://invis.io/N211LBEL7ZW5
1b. Account recovery via mobile screen (filled state): https://invis.io/EP11LBEMQ45F
2a. Recovery SMS sent confirmation screen: https://invis.io/4611LBEPBDTJ
2b. Recovery SMS sent again confirmation screen: https://invis.io/PN11LBEQ6CKM
3. SMS template design with auto-generated reset password CTA link: https://invis.io/GB11LBESEKUH

**Create New Password**
1. Create new password (unfilled): https://invis.io/Y311LBEUCETQ
2. Create new password (validation states): https://invis.io/RX11LBEY9DB4
3. Create new password (filled): https://invis.io/T511LBEZPC4J
4. Password reset success modal roll up: https://invis.io/DT11LBF0VFJ3

===

**Comment by Juliana-t** [comment]
@andrewwapling can you please confirm if the links to the UI mockups are for the latest stage of the design? Thanks!

**Comment by andrewwapling** [comment]
Hi @Juliana-t I would refer now to the new Bero Login & Account Creation prototype here: https://invis.io/DE11PTCZYKN8

The forgot password section is also here: https://invis.io/5B121PW84AE3

Let me know if there's any queries or if you require anything else at this stage.

**Comment by Juliana-t** [comment]
Issue was updated accordingly to the last UI/UX design and US

**Comment by joanico** [comment]
@PeteCoward I think this issue did not deploy yet to PeP staging.
We still get the old recovery password design no also doesn't send me a link to the recovery password via email.

**Comment by pedro16v** [comment]
> @PeteCoward I think this issue did not deploy yet to PeP staging. We still get the old recovery password design no also doesn't send me a link to the recovery password via email.

I did get an email but it seems to be unproperly configured. It navigates to `example.com`. This is the recovery link I got:

> https://example.com/bero_django_auth/reset/OQ/azksi9-cb45bc1b600bffb261756b7728e2c89d/

<img width="749" alt="Screenshot 2022-01-21 at 09 44 21" src="https://user-images.githubusercontent.com/2813677/150445096-0a331ebb-bc44-4cd6-b2c0-0ec9c45e4d6c.png">

**Comment by PeteCoward** [comment]
@pedro @joanico Try again please, should be fixed on jid-staging and pep-staging

**Comment by pedro16v** [comment]
Thanks @PeteCoward. It does work. The PeP version is still sending an email with a generic subject:

* PeP:
<img width="252" alt="Screenshot 2022-01-21 at 10 18 19" src="https://user-images.githubusercontent.com/2813677/150448577-68beb971-851c-4e35-9d35-b1e772bf8ced.png">

* KHS
<img width="279" alt="Screenshot 2022-01-21 at 10 19 27" src="https://user-images.githubusercontent.com/2813677/150448571-328e2711-b72f-4d0f-b4cb-51e74b4ab3ab.png">

**Comment by PeteCoward** [comment]
I got "Pacific Learn Account Recovery"

**Comment by joanico** [comment]
I only got "Kumul Helt Skul"
<img width="500" alt="Screen Shot 2022-01-24 at 9 32 50 AM" src="https://user-images.githubusercontent.com/12932898/150705100-68581c66-3a2f-46f3-bf00-101c2df38ec2.png">

**Comment by pedro16v** [comment]
@joanico check both https://pep-staging.temp.build/ and https://jid-staging.temp.build/ carefully. I got both working. Should be good to go.

@PeteCoward can we also set the sender name to "Kumul Helt Skul" or "Pacific Learn" instead of the plain email address? /cc @Juliana-t

**Comment by Juliana-t** [comment]
Yes please, to the sender name

**Comment by joanico** [comment]
@pedro16v, Yes  I got both working now, but I still get the sender name plain email address.

**Comment by PeteCoward** [comment]
I'll see what we can do, I think it is configurable

**Comment by joanico** [comment]
It seems to work as we expected

<img width="695" alt="Screen Shot 2022-02-09 at 9 24 15 AM" src="https://user-images.githubusercontent.com/12932898/153098390-571caeb3-8741-489c-b44b-a85115339e1b.png">
