### ISSUE TITLE
I am onboarded when I access Bero 

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#924]
## Overview
Users new to Bero should be taken through a set of explainer cards showing them how Bero works. The initial set of cards will probably be preloaded for most cases but we want to make it as flexible as possible so that people managing their own installations and content can define what their users see (using Wagtail for that).

To achieve this, the plan is to use a new type of card, with strict rules for what content it allows. This card structure will be based off @andrewwapling 's [onboarding prototype](https://projects.invisionapp.com/share/5Q11ME8XZXSA#/screens). The idea is to style and limit the entered text that will populate each section, as well as define a strict boundary for the image so that the balance is kept from card to card.

Check the image below to check which areas can be populated by users.

<img width="450" alt="Screenshot 2021-09-16 at 11 21 50" src="https://user-images.githubusercontent.com/2813677/133538985-eeb8ad88-c5d8-4cac-8b1d-3b26de0c5c8b.png">
<img width="450" alt="Screenshot 2021-09-16 at 11 21 55" src="https://user-images.githubusercontent.com/2813677/133539006-670c0dd6-93f7-4b39-84fc-3820fff45b92.png">

### Content authoring
* The onboarding section has no limit to the number of possible cards
* Card order can be set
* The last card has a call-to-action button which links to a target configurable on Wagtail.
  * The default target should be the homepage.

**Limits**
* Title: 30 char
* Summary: 70 char
* Description: 155 char
* Image: 144px x 167px (note: not necessarily the required upload size but the maximum limits we'll display so it won't overflow. As always, unsuitable images will cause unsuitable results)

For cards with a button:
* Button text: 15 char

### When Bero enforces login:
* When I login for the first time, I am taken to the first onboarding card.
  * There is an option to dismiss at any point
* When I close the last onboarding card, I am taken to the home screen
* The onboarding cards will not show the next time I visit or log in to Bero

### When Bero doesn't enforce login:
* When I open Bero for the first time, I am taken to the first onboarding card.
  * There is an option to dismiss at any point
* When I close the last onboarding card, I am taken to the home screen
* The onboarding cards will not show up while my session is active (in practical terms, I will see the onboarding cards again if I clear my caches)

## Resources
* Check on [InVision](https://projects.invisionapp.com/share/5Q11ME8XZXSA#/screens)

**Comment by andrewwapling** [comment]
Hi @pedro16v thanks for setting this issue up. Just an update from the design side @megganeturner I've looked to uplift the onboarding card pattern from using the learning activity card design to a distinct informative onboarding style. Please see new design direction below:

1. Share – https://invis.io/Y511ME8SX3QR
2. Download – https://invis.io/QG11ME8VPV68
3. Favourite – https://invis.io/KS11ME8WPYAD
4. Social Learning – https://invis.io/5Q11ME8XZXSA

The idea is that this pattern should replace all/any existing onboarding card modals. The design rationale here is to create a distinct experience to the lesson activity cards. Setting this expectation from a behavioural perspective will be important as the product scales. The same content as used in the previous designs above applies just a different design application. Kindly review and let me know if you have any queries at all :)

**Comment by pedro16v** [comment]
@Juliana-t @andrewwapling are these new cards approved and ready to go?

**Comment by andrewwapling** [comment]
Hi @pedro16v just awaiting review from David and rest of team on these :)

**Comment by pedro16v** [comment]
![Screenshot 2021-09-10 at 18 19 42](https://user-images.githubusercontent.com/2813677/132831609-dc74d3d3-016d-4757-9e9e-c3c4b34b6fb3.png)

**Comment by andrewwapling** [comment]
Hi @pedro16v just confirming that David and rest of the team are happy with this new design pattern. So I believe it can be slotted into the to do queue when appropriate :)

**Comment by pedro16v** [comment]
Just updated the first comment with new links, CoS and screenshots. Let me know if you find any trouble @megganeturner

**Comment by andrewwapling** [comment]
Thanks @pedro16v – @megganeturner let me know if you need anything from design side when you get to this one :)

**Comment by pedro16v** [comment]
Seems to work as intended. Just some implementation details:

* Making the image height have a min of 200px seems to create better balance.
* Reducing the font size in the card seems to make it closer to the original look

| InVision | Current | Suggestions|
| --- | --- | --- |
![Screenshot 2021-10-15 at 11 32 00](https://user-images.githubusercontent.com/2813677/137423834-bcf249b7-1e30-4a88-bca5-04fbf0206e68.png) | ![Screenshot 2021-10-15 at 11 31 21](https://user-images.githubusercontent.com/2813677/137423848-4d3f9c94-5756-45d8-bddc-b3919ceda5f5.png) | ![Screenshot 2021-10-15 at 11 35 36](https://user-images.githubusercontent.com/2813677/137423857-97794c06-3eb5-4d59-b262-6d07d9986dac.jpg)

**Comment by joanico** [comment]
@pedro16v  It's in JID staging but, I'm not sure in PeP because after I create the onboard card, but nothing shows in the interface even I login and logout also clear caches, any clarification for that?

**Comment by andrewwapling** [comment]
This is looking great @pedro16v @megganeturner – I agree regarding the font tweaks to match design more closely if possible.
