### ISSUE TITLE
As a Metabase authenticated user, I can access reports on the feedback users provided on teaching activities

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#928]
## Conditions of satisfaction
- [ ] Same as Metabase report on[ Kumul Helt Skul lesson report](https://stats.kumulheltskul.com/dashboard/18-feedback?workertype=Administration&workertype=CHW&workertype=HEO&workertype=Management&workertype=Medical&workertype=Midwife&workertype=Nurse&workertype=Other&workertype=Tester) but for Teaching activities feedback (PeP)

**Comment by Juliana-t** [comment]
@PeteCoward will the [feedback dashboard](https://stats.kumulheltskul.com/dashboard/18-feedback?workertype=Administration&workertype=CHW&workertype=HEO&workertype=Management&workertype=Medical&workertype=Midwife&workertype=Nurse&workertype=Other&workertype=Tester) prepared for KHS work for the teaching activities as well? On KHS we couldn't see it as we don't have the teaching part, so just confirming if the existing feedback dashboard/reports would be showing the teaching part on PeP instance

**Comment by Juliana-t** [comment]
updated according to new specifications for Release 5
