### ISSUE TITLE
As a Metabase authenticated user, I can access reports on discussion topics (social learning aspect of Bero)

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#929]
## Conditions of Satisfaction
- [ ] Discussion topics report
  - [ ] A table with all comments on discussion topics, each row is a comment
  - [ ] Table has the following columns:
    - [x] Category title
    - [x] Course title 
    - [x] Lesson title 
    - [ ] Discussion question 
    - [x] Comment 
    - [ ] Flagged yes-no 
    - [x] date of comment 
    ~~- [ ] user name~~ 
    - [x] User attributes (if any)
  - [ ] Report can be filtered by:
    - [x] category
    - [x] course
    - [x] lesson
    - [x] user attributes
    - [ ] flagged / non flagged
~~- [ ] user name~~

**Comment by Juliana-t** [comment]
updated according to specs for release 5

**Comment by Juliana-t** [comment]
So far we have prepare these questions and added it to a dashboard

**Comment by Juliana-t** [comment]
@PeteCoward I need your help here - most is there and possible to do using [this data table](https://stats.kumulheltskul.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo0MjQyLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjk2fSwidHlwZSI6InF1ZXJ5In0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==), but there are 2 information/columns that I believe we don't have there yet. Can you please have a look and see if we can get this data by joining it with another data table or if it requires engineer work to retrieve that information:
- [ ] information if a comment was flagged
- [ ] discussion question (text)

I am moving this issue back to the to do column

**Comment by Juliana-t** [comment]
Done!
