### ISSUE TITLE
As an authenticated user, I can access reports on exams (learn aspect of Bero)

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#930]
## Conditions of Satisfaction
* Admins can define who can access to this report, through the permissions
* Exam reports
  * This is a summary list of all exams, each row represents 1 exam
  * There are filters:
    * By category
    * By course
* There is a search (category, course)
* Table has the following columns: Type (Pre-learning survey or Exam) / Category title / Course title / Number of questions (on the exam) / Number of users (that took the exam) / Average score - all time (all users who attempted) / Average score - first attempt / Average score - last attempt / Average number of attempts
* Clicking on a row, will take the user to the exam report page (detailed)
    * Page displays details: Category title / Course title / Number of questions (on the exam) / Number of users (that took exam) / 
Average score - all time (all users who attempted) / Average score - first attempt / Average score - last attempt / Average number of attempts
    * List of all Questions on the exam with: % correct answers, % incorrect answers, Answer 1, Answer 2, ... - how many times were selected

**Comment by Juliana-t** [comment]
The report is on KHS production but a bug was found.
@PeteCoward  will deploy the fix for that with the deployment of release 4.2.
Once it is in prod, I will review and close the issue
