### ISSUE TITLE
As an authenticated user, I can export all reports and analytics as an excel

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#932]
## Overview
We need a way to export the raw data being collected in a way that can be easily analysed by a human on a spreadsheet software and added to a report.

## Conditions of satisfaction
* Each report page should be exportable to Excel or CSV
* Exported files should reflected any filter applied
* File name should be: `[Bero_instance_name]-[Report_name]-[date_and_time_of_export]`

**Comment by Juliana-t** [comment]
@PeteCoward can we close this issue? As we are using Metabase for Stats and analytics, all reports should be exportable through their UI
