### ISSUE TITLE
Sync reboot when connected to a hotspot with no internet - Can only see Bero splash screen

### ISSUE THREAD

**Issue by md8n** [catalpainternational/canoe#933]
# Description

Setup:
A device is receiving shared content via a WiFi hotspot that has no internet connection
Having received the shared content it performs the Sync reboot of the Bero app itself

The Bero app returns, but only the splash screen is shown to the user.

Investigating with remote debugging, the URL the phone is accessing is `https://pep-staging.temp.build/#sync`.
The console logs show that is has not accessed the manifest.

Restarting the App (while still connected to the hotspot with no internet access) it works fine and shows the normal landing page.  Alternatively changing the hotspot to one that has internet access it also works fine and shows to the Sync page

**Comment by PeteCoward** [comment]
what is the status of this @md8n ?

**Comment by md8n** [comment]
@PeteCoward if Nico's testing hasn't turned this up again, then it should be closed.

This was probably bypassed as an issue by other changes made to Appelflap itself.
