### ISSUE TITLE
Fix "Other Courses" title and description

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#941]
## Overview

Grouping all category-less courses in a "Other Courses" category,  creates a page with duplicated information.

The title should at least say "Other Courses". How configurable can this page be?

## Resources
**A** — Courses listing
**B** — Scroll down to find "Other Courses"
**C** — Navigate to "Other Courses" Category page. Note that the title and description are the same as A

| A | B | C |
| - | - | - |
<img width="375" alt="Screenshot 2021-08-09 at 14 39 06" src="https://user-images.githubusercontent.com/2813677/128716164-8124bfbe-116e-4364-a97a-4106a64c2595.png"> | <img width="375" alt="Screenshot 2021-08-09 at 14 39 12" src="https://user-images.githubusercontent.com/2813677/128716158-01077987-0a59-4414-9a6b-29c0fc0f4895.png"> | <img width="375" alt="Screenshot 2021-08-09 at 14 39 18" src="https://user-images.githubusercontent.com/2813677/128716129-c2748df0-13df-4a32-b5fa-d84a7c35bfd2.png">

**Comment by PeteCoward** [comment]
It is NOT another page.. It's the same page just with different bits shown or hidden, so it has the same title.

**Comment by PeteCoward** [comment]
I think it is wiser to almost always have either

A) No categories and only courses under the courses page
B) Categories with courses, but no courses without categories

Just for non-brain melting structural confusion.

**Comment by pedro16v** [comment]
After talking to @Juliana-t about this, we've decided to close this.
