### ISSUE TITLE
Download management

### ISSUE THREAD

**Issue by boerwastaken** [catalpainternational/canoe#947]
Normally, the webapp has no influence whatsoever over what happens to files after they've been downloaded. Management of the downloads is left to the user (naming them on download, cleaning up, mentally tracking which things they've already downloaded and shouldn't download again).

As we've noticed in Eskola, for first time users, this is a pretty terrible experience. Downloads are already not ideal \*, but for many users, to "get the thing to show" they just click on the link again, it'll download again, it'll open (hopefully, because they also have no idea how to do that themselves using a file manager), and pretty soon they'll have dozens of copies of the same file and no disk space left.

Thus, in the Bero Android app, downloads are managed for the user in a way so that if you try to download something that you've downloaded before, it'll just immediately open the already downloaded file. That behaviour preempts a lot of the problems that come with the orthodox here'-s-a-save-dialog-kthxbye approach.
To view a file, you just go to where you found it on the webpage (users turn out to remember quite readily where they got their files) and click the download button. As many times as you want.

However, since now we have effectively adopted those downloaded files, we probably need some UI elements for the following tasks:

- Cleaning up (perhaps not every download needs to be kept forever, perhaps space is dear, ...)
- Opening files that are no longer referenced from any webpage

Rather than implement this in Appelflap itself (and make people go booh and baah about the Android UI), I propose I implement another HTTP API (hey, they're cheap, everything's already in place!) that exposes the downloads, with their metadata. The upside of that approach is that management can be integrated into the Bero webapp, and can even be automated (if desired), and things can be designed & styled in the familiar webby way. And it keeps the Android code small. Attributes available for each download would be:

- Filename
- Size
- Date and time it was downloaded
- Mime type

Actions available through that API would be:

- Delete
- Launch (= open an Android "open with" dialog for this file)

\*) Why not make a webpage if the information could reasonably be contained in one?

**Comment by Juliana-t** [comment]
Thanks @boerwastaken - I can see the value of this but I would need to understand a couple of things before making a decision:
- what is the estimate effort required for this work (from your side, from the rest of the team @PeteCoward )
- how would it work on the webapp from the functional perspective (how it works) and experience perspective (what would the user do? or what would they see?)
- would that affect anyhow the way the download/offline things work at the moment - from the user perspective?

**Comment by boerwastaken** [comment]
> what is the estimate effort required for this work (from your side)
Some hours on the Appelflap side.

> how would it work on the webapp from the functional perspective

1. webapp grabs list of downloaded items from the API
2. displays them, with buttons for "open" and "delete"
3. if the user clicks "open" or "delete", send the appropriate simple HTTP API call

From the experience perspective:
- there'd be a corner of the webapp where one can view the aforementioned list, and click the buttons

> would that affect anyhow the way the download/offline things work at the moment - from the user perspective?

It doesn't affect how it works in the browser (out of necessity - the PWA has no powers to look at a user's files, nor to open files at will).
Given current use cases, the frontend work is not very urgent and can even be postponed until some form of urgency arises.

**Comment by boerwastaken** [comment]
[The abovementioned API is in place now](https://github.com/catalpainternational/appelflap/blob/master/docs/API/downloads.md)

Apart from the "open" and "delete" action, there's "share" which (depending on what apps you have) lets you send a download by email or whatsapp or save it to disk etc.

**Comment by andrewwapling** [comment]
This sounds like a great initiative @boerwastaken – I can definitely see this delivering value to users. Greater control over downloads could help people in many ways i.e. manage storage, refer to downloads and resources retrospectively, share important artefacts with peers etc. Look forward to exploring some design solutions for this experience :)

**Comment by Juliana-t** [comment]
I added this feature to our product roadmap, planned for the next Epic if no other urgent work is identified.
In the meantime, @andrewwapling when you have time, you can start exploring solutions for this
