### ISSUE TITLE
Onboarding: dismissible discussions helper tooltip

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#972]
## Overview

Following up on the design work done in #849

User testing found that users not always realise they have a Discussion tab next to Lessons. Similarly, it wasn't obvious to them that they could save content for offline use. We decided to make these part of the onboarding process for new users.

We'll create onboarding mechanism for the following features:
* Make content offline
* Discussions

### Make content offline
- [x] When I visit a Course for the first time
  - [x] The helper would fade in and highlight the download UI control
  - [x] The user can then dismiss it permanently.
- [x] For Bero installations that allow guest users, this behaviour should apply in every new session (after clearing caches)

![Screenshot 2021-08-19 at 11 50 47](https://user-images.githubusercontent.com/2813677/130057208-c6f490f1-d0c4-44e7-ad72-25fc6efa7787.png)

### Discussions
- [x] When I visit a Course for the first time **AND** I scroll past a certain point, the onboarding mechanism should show.
  - [x] Certain point: when there's less than X pixels left to the `tab-titles` container (LESSONS | DISCUSSION)
  - [x] Reaching this point, the helper would fade in and highlight the Discussions UI control. 
  - [x] The user can then dismiss it permanently.
- [x] For Bero installations that allow guest users, this behaviour should apply in every new session (after clearing caches)

![Screenshot 2021-08-19 at 11 20 11](https://user-images.githubusercontent.com/2813677/130054655-ca75c925-521c-4040-99d4-09bd9974e56a.png)

## Resources

- Check the InVision prototype:
  - Make content offline https://projects.invisionapp.com/share/7Y11HPE4KQ63#/screens/446572479
  - Discussions https://projects.invisionapp.com/share/52Y02L9YTRF#/screens/455859748

**Comment by megganeturner** [comment]
Just wondering if it's worth building an API to store onboarding completion data or if using localStorage is sufficient - how likely is it that users will log in from multiple devices? @PeteCoward @pedro16v keen to hear your thoughts on this?

For guest users sessionStorage should do the trick

Related issue: https://github.com/catalpainternational/canoe/issues/924

**Comment by pedro16v** [comment]
I believe that having the same user logging in from multiple devices is not something we'll be seeing much on the short term (with the exception of us testing different devices/browsers).

Using localStorage would mean that all onboarding features would be visible when clearing caches, using a different browser, using private mode, etc. Not particularly serious — how often does the typical user do any of these actions?
