### ISSUE TITLE
Standardisation of end of Lesson/Course screens

### ISSUE THREAD

**Issue by pedro16v** [catalpainternational/canoe#973]
## Overview

Based on the design work done on #753 we want to apply changes to the following screens so that we standardise how they look and what they do.

### Lesson completion

<img width="485" alt="Screenshot 2021-08-19 at 14 25 52" src="https://user-images.githubusercontent.com/2813677/130076722-60262c59-9b4c-4784-b6f5-3de821e98f6c.png">

**Headline**: Good job [Insert Name]!
**Copy**: You just completed Lesson Name successfully. Only {one} more lesson to go to complete Course Name.

**Primary CTA**: Next lesson [next lesson in course series]
**Secondary CTA**: Join the discussion [discussion tab anchored open for the course in question] 

Design direction link: https://projects.invisionapp.com/share/RG11E66RZBUH

| Current | Intended |
| - | - |
![Screenshot 2021-08-19 at 12 56 23](https://user-images.githubusercontent.com/2813677/130064588-9a194e44-09b2-41ad-b6b2-5fe1ef95a33e.png) | ![Screenshot 2021-08-19 at 12 54 40](https://user-images.githubusercontent.com/2813677/130064580-ee792242-aa49-4d22-a123-d1a8fb334784.png)

### Course completion

<img width="477" alt="Screenshot 2021-08-19 at 14 25 57" src="https://user-images.githubusercontent.com/2813677/130076828-38cef4cd-8661-4a88-8d3c-c986318dd88f.png">

**Headline**: Amazing work [Insert Name]!
**Copy**: You just completed Course Name successfully. Start another course or dive into the course discussion.

**Primary CTA**: Back to courses [back to course listing screen]
**Secondary CTA**: Join the discussion [discussion tab anchored open for the course in question] 

Design direction link: https://projects.invisionapp.com/share/B211E66UN3AS

| Current | Intended |
| - | - |
![Screenshot 2021-08-19 at 13 02 03](https://user-images.githubusercontent.com/2813677/130065274-e705c010-6f03-4139-ac8f-51ed040d5311.png) | ![Screenshot 2021-08-19 at 13 01 25](https://user-images.githubusercontent.com/2813677/130065272-ef73d967-c2b5-456a-bd38-b6506b6499dd.png)

### Last lesson completion (exam flow)

<img width="464" alt="Screenshot 2021-08-19 at 14 26 04" src="https://user-images.githubusercontent.com/2813677/130076876-0ba7f65b-9fb7-44e8-9441-09e8d4764ce0.png">

**Headline**: Amazing effort [Insert Name]!
**Copy**: You just completed the last lesson in Course Name successfully. You're now ready to undertake an exam to validate your learning.

**Primary CTA**: Commence exam [start exam flow]
**Secondary CTA**: Join the discussion [discussion tab anchored open for the course in question] 

Design direction link: https://projects.invisionapp.com/share/BQ11E66Z6WD2

| Current | Intended |
| - | - |
![Screenshot 2021-08-19 at 13 36 09](https://user-images.githubusercontent.com/2813677/130069342-e3fc8c67-ed3f-43f0-8552-c5598ae68712.png) | ![Screenshot 2021-08-19 at 13 10 17](https://user-images.githubusercontent.com/2813677/130069350-75f5374e-e265-4340-9416-5bfe25fed7c9.png)

### Review exam

<img width="456" alt="Screenshot 2021-08-19 at 14 26 11" src="https://user-images.githubusercontent.com/2813677/130076938-03a25936-52f9-4c29-b7f1-56e9d7393e2a.png">

**Headline**: You scored XX%  
Keep trying [Insert Name]!
**Copy**: You didn’t complete this exam successfully. You can review your answers now or retake the exam.

**Primary CTA**: Review & retake exam [start exam review flow]
**Secondary CTA**: Back to courses [back to course listing screen]

Design direction link: https://projects.invisionapp.com/share/E611E67UKFG3

| Current | Intended |
| - | - |
 ![Screenshot 2021-08-19 at 13 41 30](https://user-images.githubusercontent.com/2813677/130070134-01b2f6e5-a1dc-4244-89b5-562d8cf8b4e8.png) | ![Screenshot 2021-08-19 at 13 42 02](https://user-images.githubusercontent.com/2813677/130070127-665e4be1-79ab-4a70-8ba6-2a0c1ea03068.png)

### Retake exam

<img width="955" alt="Screenshot 2021-08-19 at 14 25 39" src="https://user-images.githubusercontent.com/2813677/130076999-b573c988-d29e-42ee-8ebc-45c5f4200e2d.png">

**Headline**: Are you ready to retake your exam [Insert Name]?
**Copy**: You have the opportunity to retake  the exam now and achieve a successful outcome. Alternatively you can return  to the course.

**Primary CTA**: Retake exam [start exam flow]
**Secondary CTA**: Back to course [back to course detail screen]

Design direction link: https://projects.invisionapp.com/share/3H11E687B647

| Current | Intended |
| - | - |
![Screenshot 2021-08-19 at 13 47 27](https://user-images.githubusercontent.com/2813677/130070872-10efec23-e6f2-424d-8165-5bceddf637ff.png) | ![Screenshot 2021-08-19 at 13 47 08](https://user-images.githubusercontent.com/2813677/130070877-07a647f9-7478-418d-bce8-684817d1517a.png)

**Comment by KaraChesal** [comment]
wow, these are really impressive, you'll gave to show me how you make it look so nice!

**Comment by pedro16v** [comment]
> wow, these are really impressive, you'll gave to show me how you make it look so nice!

Paper app on iPad using an Apple Pencil. Everyone is an artist.

**Comment by Juliana-t** [comment]
The flow seems good to me!

**Comment by Juliana-t** [comment]
@andrewwapling @pedro16v after some conversations with JID and ACIAR teams, it looks like resources may be more important to their courses and training programs than we originally thought.
So I have some recommendations:
- keep the proposed new standardisation for end of lesson / end of last lesson
- when user completes a course (by either completing all lessons or passing an exam), keep the 'Back to couses' (main CTA) and under 'View Resources' (secondary CTA)
From @andrewwapling side I would need the update of the screen, changing the secondary option from 'join the discussion' to 'View resources'. We will keep the join the discussion CTA at the end of lessons.
@pedro16v can you please update the issue once we have the reviewed UI?

**Comment by andrewwapling** [comment]
Hi @Juliana-t I've updated the course success confirmation screen as per above requirements:

https://invis.io/JP10KR0VA748#/459158719_Confirmation_-_Success_Course

**Comment by pedro16v** [comment]
Hi @megganeturner. All screens seem to be correctly updated except the one below. 

**Last lesson completion (exam flow)** 
* Need to remove `Back to Course` link
* Title should say "Amazing effort"

![Screenshot 2021-11-11 at 12 28 14](https://user-images.githubusercontent.com/2813677/141232723-85866f8f-02e5-4e07-a5d3-2eb47a35e12d.png)
