### ISSUE TITLE
Learning survey

### ISSUE THREAD

**Issue by Juliana-t** [catalpainternational/canoe#975]
### Overview
We want to offer the option for content managers to add  a customizable title to their course learning surveys through Wagtail. This way, they can define the best title for their survey, may it be a pre learning survey, a post learning survey or a mid training program learning survey. Later on, this should provide the M&E teams with statistics and reports (on Metabase), to view the results of a specific learning survey or even compare the results from  2 or more learning surveys, as a way to measure the impact of a training program.

### Conditions of satfisfaction
- [x] On the exam / learning survey page on Wagtail, content managers can customize the title of either the exam or the learning survey
  - [x] There is a new field on Wagtail ‘Exam title’ where the content manager can enter text
    - [x] Max chars 45
    - [x] If no title is defined, by default the title of an exam will be ‘Exam’ and a title of a pre-learning survey will be ‘Learning survey’
  - [x] On app UI the title displayed is the one defined on the Wagtail (or if none, the default title):
    - [x] Course detail page title before the exam/survey card
    - [x] ‘Good job’ screen - when all lessons of a course were completed by the learner
      - [x] Description text: ‘Take the [title of exam] now to complete…
      - [x] Button text: ‘Take [title of exam]’
    - [x] Code of conduct screen
      - [x] Title ‘Course [exam title]
      - [x] Description ‘To pass this [exam title] you need to…’
      - [x] Code of conduct box ‘You’re about to start a course [exam title]. Do you promise that you will complete this [exam title] on your own, without assistance from anyone?”
    - [x] ‘Not quite!’ screen (when use didn’t pass the exam)
      - [x] ‘You can review your answers, retake this [exam title] now, or finish it later.’
      - [x] Button ‘Retake [exam title]’
    - [x] Are you ready to retake your exam screen:
      - [x] Title ‘...to retake your [exam title]?’
      - [x] Description ‘... to retake your [exam title] now …’
      - [x] Button ‘Retake [exam title]’
    - [x] Amazing work screen
      - [x] Description ‘You passed this [exam title] with a score of…’
- [x] As already in place, surveys have no passing rate nor option to retake it. We just want to add the option for users to edit the title of the survey
  - [x] Answers are collected on our database (per user) so later we can provide disaggregated reports for M&E and allow content developers to compare results of 2 or more learning surveys or exams

**Comment by Juliana-t** [comment]
@megganeturner I updated the conditions of satisfaction to provide some further detail - please let me know if something is unclear!

**Comment by pedro16v** [comment]
@joanico I will look at this one myself.
